<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'Assets search');
?>
<?php echo $this->pageTitle($translate('Advanced search'), 1, $translate('Assets')); ?>
<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
    <?php echo $this->partial(
        'common/advanced-search-assets',
        ['query' => $this->params()->fromQuery(), 'resourceType' => 'user']
    ); ?>
    <div id="page-actions">
        <input type="submit" name="submit" value="<?php echo $this->escapeHtml($translate('Search')); ?>">
    </div>
</form>