<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<h3>
    <?php echo $escape($resource->name()); ?>
</h3>

<?php echo $this->thumbnail($resource, 'square', ['class' => 'asset-inline']); ?>

<?php
$altText = $resource->altText();
if ($altText):
?>
<div class="meta-group">
    <h4><?php echo $translate('Alt text'); ?></h4>
    <div class="value"><?php echo $escape($resource->altText()); ?></div>
</div>
<?php endif; ?>

<?php $this->trigger('view.details', array('entity' => $resource)); ?>
