<?php
$escape = $this->plugin('escapeHtml');

?>

<a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $this->translate('Close'); ?></span></a>

<?php if ($this->userIsAllowed('Omeka\Api\Adapter\AssetAdapter', 'create')): ?>
<h3 id="asset-upload-label"><?php echo $this->translate('Upload new asset'); ?></h3>
<form class="asset-upload" method="post" enctype="multipart/form-data" action="<?php echo $escape($this->url('admin/default', ['controller' => 'asset', 'action' => 'add'])); ?>">
    <input type="file" name="file" accept="image/jpeg,image/png,image/gif" required aria-labelledby="asset-upload-label">
    <button type="submit"><?php echo $this->translate('Upload'); ?></button>
    <ul class="errors"></ul>
</form>
<?php endif; ?>

<h3><?php echo $this->translate('Select asset'); ?></h3>
<?php if (count($assets) > 0): ?>
<?php echo $this->pagination('common/sidebar-pagination.phtml'); ?>
<div class="asset-list" data-delete-url="<?php echo $escape($this->url('admin/default', ['controller' => 'asset', 'action' => 'delete'])); ?>">
<?php foreach ($assets as $asset): ?>
    <div class="asset" data-asset-id='<?php echo $escape($asset->id()); ?>'>
        <?php if ($this->userIsAllowed('Omeka\Api\Adapter\AssetAdapter', 'delete')): ?>
        <span class="actions">
            <?php
            echo $this->hyperlink('', '#', [
                'class' => 'o-icon-delete remove-value delete-asset',
                'title' => $this->translate('Delete asset'),
            ]);
            echo $this->hyperlink('', '#', [
                'class' => 'o-icon-undo cancel-delete',
                'title' => $this->translate('Cancel delete'),
                'style' => 'display: none',
            ]);
            ?>
        </span>
        <?php endif; ?>
        <?php
        $hyperlink = $this->plugin('hyperlink');
        echo $hyperlink->raw(
            sprintf('<img src="%s"><span class="asset-name">%s</span>',
                $escape($asset->assetUrl()),
                $escape($asset->name())
            ),
            '#',
            ['class' => 'select-asset', 'data-asset-id' => $asset->id()]
        );
        ?>
    </div>
<?php endforeach; ?>
<?php else: ?>
<span class="no-resources"><?php echo $this->translate(sprintf('No %s found.', $this->translate('assets'))); ?></span>
<?php endif; ?>
</div>

<div id="delete-warning" style="display:none">
    <p><?php echo $this->translate("Are you sure you want to delete this asset? It will no longer be available to any sites currently using it.");?></p>
    <a class="button confirm-delete"><?php echo $this->translate("Confirm delete");?></a>
</div>
