<form id="advanced-search">
    <div class="confirm-main">
        <button type="button" class="sidebar-close o-icon-close" title="<?php echo $this->translate('Close'); ?>" aria-label="<?php echo $this->translate('Close'); ?>"></button>
        <h3><?php echo $this->translate('Search query edit'); ?></h3>
        <?php echo $this->partial('common/advanced-search', [
            'query' => $this->params()->fromQuery(),
            'resourceType' => $resourceType,
            'partialExcludelist' => $partialExcludelist,
        ]); ?>
    </div>
    <div class="confirm-panel">
        <button type="button" class="query-form-preview"><?php echo $this->translate('Preview'); ?></button>
        <button type="button" class="query-form-reset"><?php echo $this->translate('Reset'); ?></button>
        <button type="button" class="query-form-set"><?php echo $this->translate('Apply'); ?></button>
    </div>
</form>
