<a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $this->translate('Close'); ?></span></a>
<h3><?php echo $this->translate('Edit query'); ?></h3>
<form id="advanced-search">
    <?php echo $this->partial('common/advanced-search', ['query' => $this->params()->fromQuery(), 'resourceType' => 'item']); ?>
    <button type="button" class="query-form-set"><?php echo $this->translate('Set this query'); ?></button>
    <button type="button" class="query-form-reset red button"><?php echo $this->translate('Reset form'); ?></button>
</form>
