<?php
use Omeka\Entity\Job;

$this->htmlElement('body')->appendAttribute('class', 'jobs browse');
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Jobs')); ?>

<?php if (count($jobs)): ?>

<?php echo $this->pagination(); ?>

<table>
    <thead>
        <tr>
            <th><?php echo $this->sortLink($this->translate('ID'), 'id'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Class'), 'class'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Status'), 'status'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Owner'), 'owner_email'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($jobs as $job): ?>
        <?php
        if ($owner = $job->owner()) {
            $ownerText = $this->hyperlink($owner->email(), $this->url(
                'admin/id',
                array(
                    'controller' => 'user',
                    'action' => 'show',
                    'id' => $owner->id())
                )
            );
        } else {
            $ownerText = $this->translate('[no owner]');
        }
        ?>
        <tr>
            <td>
                <span class="resource-name">
                    <?php echo $escape($job->id()); ?>
                </span>
                <ul class="actions">
                    <?php if ('in_progress' == $job->status()): ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($job->url('show-details')); ?>"
                        data-sidebar-confirm-url="<?php echo $escape($job->url('stop')); ?>"
                        class="o-icon-stop sidebar-confirm"
                        aria-label="<?php echo $escape($this->translate('Stop')); ?>"
                        title="<?php echo $escape($this->translate('Stop')); ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($job->url('show-details')); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escape($this->translate('Details')); ?>"
                        title="<?php echo $escape($this->translate('Details')); ?>"></a></li>
                </ul>
            </td>
            <td><?php echo $escape($job->jobClass()); ?></td>
            <td><?php echo $escape($job->statusLabel()); ?></td>
            <td><?php echo $ownerText; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->pagination(); ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $this->translate('Stop Job'); ?></h2>
        <p><?php echo $this->translate('Are you sure you would like to attempt to stop this job?'); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any jobs.'); ?></p>
</div>

<?php endif; ?>

