<?php
use Omeka\Entity\Job;

$this->htmlElement('body')->appendAttribute('class', 'jobs browse');
$escape = $this->plugin('escapeHtml');
$sortHeadings = [
    [
        'label' => $this->translate('ID'),
        'value' => 'id'
    ],
    [
        'label' => $this->translate('Class'),
        'value' => 'class'
    ],
    [
        'label' => $this->translate('Status'),
        'value' => 'status'
    ],
    [
        'label' => $this->translate('Owner'),
        'value' => 'owner'
    ]
];
?>

<?php echo $this->pageTitle($this->translate('Jobs')); ?>

<?php if (count($jobs)): ?>

<?php echo $this->pagination(); ?>

<?php echo $this->sortSelector($sortHeadings); ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('ID'); ?></th>
            <th><?php echo $this->translate('Class'); ?></th>
            <th><?php echo $this->translate('Status'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($jobs as $job): ?>
        <?php
        if ($owner = $job->owner()) {
            $ownerText = $this->hyperlink($owner->email(), $this->url(
                'admin/id',
                [
                    'controller' => 'user',
                    'action' => 'show',
                    'id' => $owner->id()]
                )
            );
        } else {
            $ownerText = $this->translate('[no owner]');
        }
        ?>
        <tr>
            <td>
                <span class="resource-name">
                    <?php echo $job->link($escape($job->id())); ?>
                </span>
            </td>
            <td><?php echo $escape($job->jobClass()); ?></td>
            <td><?php echo $escape($job->statusLabel()); ?></td>
            <td><?php echo $ownerText; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->pagination(); ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $this->translate('Stop Job'); ?></h2>
        <p><?php echo $this->translate('Are you sure you would like to attempt to stop this job?'); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any jobs.'); ?></p>
</div>

<?php endif; ?>

<?php $this->trigger('view.browse.after'); ?>
