<?php
$this->htmlElement('body')->appendAttribute('class', 'media browse');
$confirmForm->prepare();
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Media')); ?>

<?php echo $this->searchFilters(); ?>

<?php if (count($medias) > 0): ?>

<?php echo $this->hyperlink($this->translate('Advanced media search'), $this->url(null, array('action' => 'search'), true), array('class' => 'advanced-search')); ?>

<?php echo $this->pagination(); ?>

<table>
    <thead>
        <tr>
            <th><?php echo $this->sortLink($this->translate('Title'), 'dcterms:title'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Class'), 'resource_class_label'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Owner'), 'owner_name'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Date Created'), 'created'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($medias as $media): ?>
        <?php
        if ($owner = $media->owner()) {
            $ownerText = $this->hyperlink(
                $owner->name(),
                $this->url('admin/id', array(
                    'controller' => 'user',
                    'action' => 'show',
                    'id' => $owner->id())
                )
            );
        } else {
            $ownerText = $this->translate('[no owner]');
        }
        ?>
            <tr>
                <td>
                    <img src="<?php echo $escape($media->thumbnailUrl('square')); ?>">
                    <span class="resource-name">
                        <?php echo $media->link($media->displayTitle(), 'show'); ?>
                    </span>
                    <ul class="actions">
                        <li><?php echo $media->link('', 'edit', array(
                            'class' => 'o-icon-edit',
                            'aria-label' => $escape($this->translate('Edit')),
                            'title' => $escape($this->translate('Edit')),
                        )); ?></li>
                        <li><a href="#"
                            data-sidebar-content-url="<?php echo $escape($media->url('show-details')); ?>"
                            data-sidebar-confirm-url="<?php echo $escape($media->url('delete')); ?>"
                            class="o-icon-delete sidebar-confirm"
                            aria-label="<?php echo $escape($this->translate('Delete')); ?>"
                            title="<?php echo $escape($this->translate('Delete')); ?>"></a></li>
                        <li><a href="#"
                            data-sidebar-content-url="<?php echo $escape($media->url('show-details')); ?>"
                            class="o-icon-more sidebar-content"
                            aria-label="<?php echo $escape($this->translate('Details')); ?>"
                            title="<?php echo $escape($this->translate('Details')); ?>"></a></li>
                    </ul>
                </td>
                <td><?php echo $escape($media->displayResourceClassLabel()); ?></td>
                <td><?php echo $ownerText; ?></td>
                <td><?php echo $escape($this->i18n()->dateFormat($media->created())); ?></td>
            </tr>
        <?php endforeach; ?>       
    </tbody>

</table>

<?php echo $this->pagination(); ?>


<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $this->translate('Delete Media'); ?></h2>
        <p><?php echo $this->translate('Are you sure you would like to delete this media?'); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any media.'); ?></p>
</div>

<?php endif; ?>

<?php $this->trigger('view.browse.after'); ?>
