<?php echo $this->navigation('Zend\Navigation\Site')->menu(); ?>
<?php echo $this->pageTitle($site->title()); ?>
<?php echo $this->pageTitle($this->translate('Items'), 2); ?>
<ul>
    <?php foreach ($site->pages() as $page): ?>
    <li><?php echo $page->link($page->title()); ?></li>
    <?php endforeach; ?>
</ul>
<?php echo $this->pagination(); ?>
<ul>
    <?php foreach ($items as $item): ?>
    <li><?php echo $item->link($item->displayTitle()); ?></li>
    <?php endforeach; ?>
</ul>
<?php echo $this->pagination(); ?>
<?php $this->trigger('view.browse.after'); ?>
