<?php $escape = $this->plugin('escapeHtml'); ?>
<?php echo $this->navigation('Zend\Navigation\Site')->menu(); ?>
<?php echo $this->pageTitle($site->title()); ?>
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<?php echo $item->displayValues(); ?>
<?php if ($item->media()): ?>
<div class="media-list">
    <?php foreach ($item->media() as $media): ?>
        <a href="<?php echo $media->url(); ?>" class="media resource">
            <img src="<?php echo $escape($media->thumbnailUrl('square')); ?>" alt="">
            <span class="media-title"><?php echo $escape($media->displayTitle()); ?></span>
        </a>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<?php $this->trigger('view.show.after'); ?>
