<?php
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
?>
<?php if ($itemSets): ?>
<div class="property">
    <h4><?php echo $this->translate('Item sets'); ?></h4>
    <?php foreach ($itemSets as $itemSet): ?>
    <div class="value">
        <a href="<?php echo $this->escapeHtml($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(null, ($filterLocale ? $this->lang() : null)); ?></a>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
