<?php
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
?>
<?php if ($itemSets): ?>
<dl class="item-sets">
    <div class="property">
        <dt><?php echo $this->translate('Item sets'); ?></dt>
        <?php foreach ($itemSets as $itemSet): ?>
        <dd class="value">
            <a href="<?php echo $this->escapeHtml($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(null, ($filterLocale ? $this->lang() : null)); ?></a>
        </dd>
        <?php endforeach; ?>
    </div>
</dl>
<?php endif; ?>
