<?php
$embedMediaSetting = $this->siteSetting('item_media_embed');
$itemMedia = $resource->media();
if ($embedMediaSetting == 1) {
    $sortedMedia = $this->sortMedia($itemMedia);
    $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
    $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
} else {
    $otherMedia = $itemMedia;
}
?>
<?php if (isset($lightMedia)): ?>
    <?php echo $this->lightGalleryOutput($lightMedia); ?>
<?php endif; ?>
<?php if (isset($otherMedia) && (count($otherMedia) > 0)): ?>
<div id="other-media" class="property">
    <h4><?php echo $this->translate('Other Media'); ?></h4>
    <div class="values">
        <?php foreach($otherMedia as $media): ?>
        <div class="value">
            <?php echo $media->linkPretty(); ?>
        </div>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
