<?php
$itemMedia = $resource->media();
$sortedMedia = $this->sortMedia($itemMedia);
$lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
$otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
?>
<?php echo $this->lightGalleryOutput($lightMedia); ?>
<?php if (isset($otherMedia) && (count($otherMedia) > 0)): ?>
<dl id="other-media">
    <div class="property">
    <dt><?php echo $this->translate('Other Media'); ?></dt>
    <?php foreach($otherMedia as $media): ?>
    <dd class="value">
        <?php echo $media->linkPretty(); ?>
    </dd>
    <?php endforeach; ?>
</dl>
<?php endif; ?>
