<?php
$showAttachedPages = $this->siteSetting('show_attached_pages', true);
$sitePages = $resource->sitePages($site->id());
?>
<?php if ($showAttachedPages && $sitePages): ?>
<div class="property">
    <h4><?php echo $this->translate('Site pages'); ?></h4>
    <div class="values">
        <?php foreach ($sitePages as $sitePage): ?>
        <div class="value"><?php echo $sitePage->link($sitePage->title()); ?></div>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
