<?php
use Omeka\Module\Manager;

$this->htmlElement('body')->appendAttribute('class', 'modules browse');
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Modules')); ?>

<form method="get" class="state-filter">
    <select name="state">
        <option value=""><?php echo $this->translate('All Modules'); ?></option>
        <?php foreach ($filterStates as $value => $option): ?>
        <option value="<?php echo $escape($value); ?>"<?php if ($value == $filterState): echo ' selected'; endif; ?>><?php echo $escape($option); ?></option>
        <?php endforeach; ?>
    </select>
</form>

<?php if ($modules): ?>

<table id="modules">
    <thead>
        <th><?php echo $this->translate('Module'); ?></th>
        <th><?php echo $this->translate('Status'); ?></th>
    </thead>
    <tbody>
        <?php foreach ($modules as $id => $module): ?>
        <tr>
            <td>
                <ul class="actions">

                    <?php
                    // configure control
                    if (Manager::STATE_ACTIVE == $module->getState()
                        && $module->isConfigurable()
                        && $this->userIsAllowed('Omeka\Module\Manager', 'configure')
                    ) {
                        echo '<li>' . $this->hyperlink('',
                            $this->url(
                                null,
                                array('action' => 'configure'),
                                array('query' => array('id' => $module->getId())
                            ), true),
                            array(
                                'class' => 'o-icon-configure',
                                'title' => $escape($this->translate('Configure')),
                                'aria-label' => $escape($this->translate('Configure'))
                            )
                        ) . '</li>';
                    }
                    ?>

                    <?php
                    // activate control
                    if (Manager::STATE_NOT_ACTIVE == $module->getState()
                        && $this->userIsAllowed('Omeka\Module\Manager', 'activate')
                    ) {
                        $form = $stateChangeForm('activate', $module->getId());
                        echo '<li>' . $this->form($form) . '</li>';
                    }
                    ?>

                    <?php
                    // deactivate control
                    if (Manager::STATE_ACTIVE == $module->getState()
                        && $this->userIsAllowed('Omeka\Module\Manager', 'deactivate')
                    ) {
                        $form = $stateChangeForm('deactivate', $module->getId());
                        echo '<li>' . $this->form($form) . '</li>';
                    }
                    ?>

                    <?php
                    // install control
                    if (Manager::STATE_NOT_INSTALLED == $module->getState()
                        && $this->userIsAllowed('Omeka\Module\Manager', 'install')
                    ) {
                        $form = $stateChangeForm('install', $module->getId());
                        echo '<li>' . $this->form($form) . '</li>';
                    }
                    ?>

                    <?php
                    // uninstall control
                    $canBeUninstalled = in_array(
                        $module->getState(),
                        array(Manager::STATE_ACTIVE, Manager::STATE_NOT_ACTIVE)
                    );
                    if ($canBeUninstalled && $this->userIsAllowed('Omeka\Module\Manager', 'uninstall')):
                    ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($this->url(null, array('action' => 'show-details'), array('query' => array('id' => $module->getId())), true)); ?>"
                        data-sidebar-confirm-url="<?php echo $escape($this->url(null, array('action' => 'uninstall'), array('query' => array('id' => $module->getId())), true)); ?>"
                        class="o-icon-uninstall sidebar-confirm"
                        aria-label="<?php echo $escape($this->translate('Uninstall')); ?>"
                        title="<?php echo $escape($this->translate('Uninstall')); ?>"></a></li>
                    <?php endif; ?>

                    <?php
                    // upgrade control
                    if (Manager::STATE_NEEDS_UPGRADE == $module->getState()
                        && $this->userIsAllowed('Omeka\Module\Manager', 'upgrade')
                    ) {
                        $form = $stateChangeForm('upgrade', $module->getId());
                        echo '<li>' . $this->form($form) . '</li>';
                    }
                    ?>

                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($this->url(null, array('action' => 'show-details'), array('query' => array('id' => $module->getId())), true)); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escape($this->translate('Details')); ?>"
                        title="<?php echo $escape($this->translate('Details')); ?>"></a></li>
                </ul>

                <?php if ($name = $module->getName()): ?>
                <span class="module-name"><?php echo $this->hyperlink($name, $module->getIni('module_link')); ?></span>
                <?php else: ?>
                [<?php echo $this->translate('name not found'); ?>]
                <?php endif; ?>
                <?php if (($versionIni = $module->getIni('version')) || ($versionDb = $module->getDb('version'))): ?>
                <span class="module-version"><?php echo sprintf($this->translate('version %s'), $escape($versionIni ?: $versionDb)); ?></span>
                <?php endif; ?>
                <?php if ($author = $module->getIni('author')): ?>
                <span class="module-author"><?php echo sprintf($this->translate('by %s'), $this->hyperlink($author, $module->getIni('author_link'))); ?></span>
                <?php endif; ?>
            </td>
            <td><?php echo $escape($states[$module->getState()]); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $this->translate('Uninstall Module'); ?></h2>
        <p><?php echo $this->translate('Are you sure you would like to uninstall this module?'); ?></p>
        <?php echo $this->form($uninstallForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any modules.'); ?></p>
</div>

<?php endif; ?>

<script>
$(".state-filter select").change(function() {
    $(this).closest('form').submit();
});
</script>
