<?php
$translate = $this->plugin('translate');
$this->headScript()->prependFile($this->assetUrl('js/admin.js', 'Omeka'));
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'install'); ?>
<?php
$form->prepare();
$form->setAttribute('action', $this->url('install'));
$form->setAttribute('method', 'post');
?>
<h1><?php echo $translate('Install Omeka S'); ?></h1>

<?php if (isset($preErrors)): ?>
<p><?php echo $translate('Some installation requirements were not satisfied.'); ?></p>
<ul class="pre-errors">
    <?php foreach ($preErrors as $error): ?>
        <li><?php echo $this->escapeHtml($this->translate($error)); ?></li>
    <?php endforeach; ?>
</ul>
<?php else: ?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formCollection($form->get('user')); ?>
<?php echo $this->formCollection($form->get('settings')); ?>
<?php echo $this->formRow($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>
<?php endif; ?>
