<?php
$translate = $this->plugin('translate');
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'install'); ?>
<?php
$form->prepare();
$form->setAttribute('action', $this->url('install'));
$form->setAttribute('method', 'post');
?>
<h1><?php echo $translate('Install Omeka S'); ?></h1>

<?php if (isset($preErrors)): ?>
<p><?php echo $translate('Some installation requirements were not satisfied.'); ?></p>
<ul class="pre-errors">
    <?php foreach ($preErrors as $error): ?>
        <li><?php echo $this->escapeHtml($error); ?></li>
    <?php endforeach; ?>
</ul>
<?php else: ?>
<?php echo $this->form($form); ?>
<?php endif; ?>
