<form id="advanced-search-form" method="post">

    <div class="resource-type field">
        <div class="field-meta">
            <legend>Filter by resource type</legend>
        </div>
        <div class="inputs">
            <label><input type="radio" name="resource-type" value="item" checked> Item</label>
            <label><input type="radio" name="resource-type" value="media"> Media</label>
        </div>
    </div>

    <div class="all-properties field">
        <ul class="actions">
            <li><a href="#" class="o-icon-add add-value"><span class="screen-reader-text">Add new value</span></a></li>
        </ul>
        <div class="field-meta">
            <legend>Search all properties</legend>
        </div>
        <div class="inputs">
            <div class="value">
                <select name="value[type][0]">
                    <option value="eq">has exact value</option>
                    <option value="neq">does not have exact value</option>
                    <option value="in">contains value</option>
                    <option value="nin">does not contain value</option>
                </select>
                <input type="text" name="value[query][0]">
                <button class="remove-value button">Remove value</button>
            </div>
        </div>
    </div>

    <div class="specific-properties field">
        <ul class="actions">
            <li><a href="#" class="o-icon-add add-value"><span class="screen-reader-text">Add new value</span></a></li>
        </ul>
        <div class="field-meta">
            <legend>Search specific property</legend>
        </div>
        <div class="inputs">
            <div class="value">
                <?php
                $propertySelect->setName('property[id][0]');
                echo $this->formSelect($propertySelect);
                ?>
                <select name="property[type][0]">
                    <option value="eq">has exact value</option>
                    <option value="neq">does not have exact value</option>
                    <option value="in">contains value</option>
                    <option value="nin">does not contain value</option>
                </select>
                <input type="text" name="property[query][0]">
                <button class="remove-value button">Remove value</button>
            </div>
        </div>
    </div>

    <div class="have-have-not field">
        <ul class="actions">
            <li><a href="#" class="o-icon-add add-value"><span class="screen-reader-text">Add new value</span></a></li>
        </ul>
        <div class="field-meta">
            <legend>Search resources</legend>
        </div>
        <div class="inputs">
            <div class="value">
                <select name="has_property[type][0]">
                    <option value="1">has property</option>
                    <option value="0">does not have property</option>
                </select>
                <?php
                $propertySelect->setName('has_property[id][0]');
                echo $this->formSelect($propertySelect);
                ?>
            </div>
        </div>
    </div>

    <div id="save-sidebar">
        <input type="submit" name="submit" value="Search" />
    </div>

</form>
