<form id="advanced-search" method="post" action="http://localhost/omeka-s/admin/item/browse">

    <div class="resource-type field">
        <div class="field-meta">
            <legend>Filter by resource type</legend>
        </div>
        <div class="inputs">
            <label><input type="radio" name="resource-type" value="item" checked> Item</label>
            <label><input type="radio" name="resource-type" value="media"> Media</label>
        </div>
    </div>

    <div id="value-queries" class="field">
        <ul class="actions">
            <li><a href="#" class="o-icon-add add-value"><span class="screen-reader-text">Add new value</span></a></li>
        </ul>
        <div class="field-meta">
            <legend>Search all properties</legend>
        </div>
        <div class="inputs">
            <div class="value">
                <select class="value-query-type">
                    <option value="eq">has exact value</option>
                    <option value="neq">does not have exact value</option>
                    <option value="in">contains value</option>
                    <option value="nin">does not contain value</option>
                </select>
                <input type="text" class="value-query-query">
                <button class="remove-value button">Remove value</button>
            </div>
        </div>
    </div>

    <div id="property-queries" class="field">
        <ul class="actions">
            <li><a href="#" class="o-icon-add add-value"><span class="screen-reader-text">Add new value</span></a></li>
        </ul>
        <div class="field-meta">
            <legend>Search specific property</legend>
        </div>
        <div class="inputs">
            <div class="value">
                <?php
                $propertySelect->setName('properties');
                echo $this->formSelect($propertySelect);
                ?>
                <select>
                    <option value="eq">has exact value</option>
                    <option value="neq">does not have exact value</option>
                    <option value="in">contains value</option>
                    <option value="nin">does not contain value</option>
                </select>
                <input type="text">
                <button class="remove-value button">Remove value</button>
            </div>
        </div>
    </div>

    <div id="has-property-queries" class="field">
        <ul class="actions">
            <li><a href="#" class="o-icon-add add-value"><span class="screen-reader-text">Add new value</span></a></li>
        </ul>
        <div class="field-meta">
            <legend>Search resources</legend>
        </div>
        <div class="inputs">
            <div class="value">
                <select>
                    <option value="1">has property</option>
                    <option value="0">does not have property</option>
                </select>
                <?php
                $propertySelect->setName('properties');
                echo $this->formSelect($propertySelect);
                ?>
            </div>
        </div>
    </div>

    <div id="save-sidebar">
        <input type="submit" name="submit" value="Search" />
    </div>

</form>

<script>
$('.add-value').click(function(event) {
    var clone = $('#value-queries .value').first().clone();
    clone.find('.value-query-type').val('eq');
    clone.find('.value-query-query').val(null);
    clone.appendTo('#value-queries .inputs');
});

$('#advanced-search').submit(function(event) {
    event.preventDefault();
    var submitQuery = {};
    $('#value-queries .value').each(function(index) {
        var query = $(this).find('.value-query-query');
        if (!$.trim(query.val())) {
            return; // do not add an empty query
        }
        var type = $(this).find('.value-query-type');
        submitQuery['value[' + type.val() + '][' + index + ']'] = query.val();
    });
    window.location.href = $('#advanced-search').attr('action') + '?' + $.param(submitQuery);
});
</script>
