<form id="advanced-search" method="get" action="http://localhost/omeka-s/admin/item/browse">

    <div class="resource-type field">
        <div class="field-meta">
            <legend>Filter by resource type</legend>
        </div>
        <div class="inputs">
            <label><input type="radio" name="resource-type" value="item" checked> Item</label>
            <label><input type="radio" name="resource-type" value="media"> Media</label>
        </div>
    </div>

    <div id="value-queries" class="field">
        <ul class="actions">
            <li><a href="#" class="o-icon-add add-value"><span class="screen-reader-text">Add new value</span></a></li>
        </ul>
        <div class="field-meta">
            <legend>Search all properties</legend>
        </div>
        <div class="inputs">
            <div class="value">
                <select class="query-type">
                    <option value="eq">has exact value</option>
                    <option value="neq">does not have exact value</option>
                    <option value="in">contains value</option>
                    <option value="nin">does not contain value</option>
                </select>
                <input type="text" class="query-query">
                <button class="remove-value button">Remove value</button>
            </div>
        </div>
    </div>

    <div id="property-queries" class="field">
        <ul class="actions">
            <li><a href="#" class="o-icon-add add-value"><span class="screen-reader-text">Add new value</span></a></li>
        </ul>
        <div class="field-meta">
            <legend>Search specific property</legend>
        </div>
        <div class="inputs">
            <div class="value">
                <?php
                $propertySelect->setName('properties')
                    ->setAttribute('class', 'query-property');
                echo $this->formSelect($propertySelect);
                ?>
                <select class="query-type">
                    <option value="eq">has exact value</option>
                    <option value="neq">does not have exact value</option>
                    <option value="in">contains value</option>
                    <option value="nin">does not contain value</option>
                </select>
                <input type="text" class="query-query">
                <button class="remove-value button">Remove value</button>
            </div>
        </div>
    </div>

    <div id="has-property-queries" class="field">
        <ul class="actions">
            <li><a href="#" class="o-icon-add add-value"><span class="screen-reader-text">Add new value</span></a></li>
        </ul>
        <div class="field-meta">
            <legend>Search resources</legend>
        </div>
        <div class="inputs">
            <div class="value">
                <select>
                    <option value="1">has property</option>
                    <option value="0">does not have property</option>
                </select>
                <?php
                $propertySelect->setName('properties');
                echo $this->formSelect($propertySelect);
                ?>
            </div>
        </div>
    </div>

    <div id="save-sidebar">
        <input type="submit" name="submit" value="Search" />
    </div>

</form>

<script>
// remove all property select names
$('.query-property').attr('name', null);

$('#value-queries .add-value').click(function(event) {
    var clone = $('#value-queries .value').first().clone();
    clone.find('.query-type').val('eq');
    clone.find('.query-query').val(null);
    clone.appendTo('#value-queries .inputs');
});

$('#property-queries .add-value').click(function(event) {
    var clone = $('#property-queries .value').first().clone();
    clone.find('.query-type').val('eq');
    clone.find('.query-property').val(null);
    clone.find('.query-query').val(null);
    clone.appendTo('#property-queries .inputs');
});

$('#advanced-search').submit(function(event) {
    event.preventDefault();
    $('#value-queries .value').each(function(index) {
        var query = $(this).find('.query-query');
        if (!$.trim(query.val())) {
            return; // do not process an empty query
        }
        var type = $(this).find('.query-type');
        $('<input>').attr('type', 'hidden')
            .attr('name', 'value[' + type.val() + '][]')
            .val(query.val())
            .appendTo('#advanced-search');
    });

    $('#property-queries .value').each(function(index) {
        var query = $(this).find('.query-query');
        if (!$.trim(query.val())) {
            return; // do not process an empty query
        }
        var property = $(this).find('.query-property');
        if (!$.isNumeric(property.val())) {
            return; // do not process invalid property
        }
        var type = $(this).find('.query-type');
        $('<input>').attr('type', 'hidden')
            .attr('name', 'property[' + property.val() + '][' + type.val() + '][]')
            .val(query.val())
            .appendTo('#advanced-search');
    });

    console.log($(this).serializeArray());
});
</script>
