<nav class="pagination" role="navigation">
    <form>
        <input type="text" name="page" id="page-input-top" value="<?php echo $currentPage; ?>" size="4">
        <span class="page-count">of <?php echo $pageCount; ?></span>
    </form>
    <?php if ($currentPage != 1): ?>
    <a href="<?php echo $this->escapeHtmlAttr($firstPageUrl); ?>" class="first o-icon-first button"><span class="screen-reader-text">First</span></a>
    <?php endif; ?>
    <?php if ($currentPage != 1): ?>
    <a href="<?php echo $this->escapeHtmlAttr($previousPageUrl); ?>" class="previous o-icon-previous button"><span class="screen-reader-text">Previous</span></a>
    <?php endif; ?>
    <?php if ($currentPage < $pageCount): ?>
    <a href="<?php echo $this->escapeHtmlAttr($nextPageUrl); ?>" class="next o-icon-next button"><span class="screen-reader-text">Next</span></a>
    <?php endif; ?>
    <?php if ($currentPage < $pageCount): ?>
    <a href="<?php echo $this->escapeHtmlAttr($lastPageUrl); ?>" class="last o-icon-last button"><span class="screen-reader-text">Last</span></a>
    <?php endif; ?>
</nav>
