<nav class="pagination" role="navigation">
    <form>
        <input type="text" name="page" id="page-input-top" value="<?php echo $currentPage; ?>" size="4">
        <span class="page-count">of <?php echo $pageCount; ?></span>
    </form>
    <?php if ($currentPage != 1): ?>
    <a href="<?php echo $firstPageUrl; ?>" class="first fa-angle-double-left button"><span class="screen-reader-text">First</span></a>
    <?php endif; ?>
    <?php if ($currentPage != 1): ?>
    <a href="<?php echo $previousPageUrl; ?>" class="previous fa-angle-left button"><span class="screen-reader-text">Previous</span></a>
    <?php endif; ?>
    <?php if ($currentPage < $pageCount): ?>
    <a href="<?php echo $nextPageUrl; ?>" class="next fa-angle-right button"><span class="screen-reader-text">Next</span></a>
    <?php endif; ?>
    <?php if ($currentPage < $pageCount): ?>
    <a href="<?php echo $lastPageUrl; ?>" class="last fa-angle-double-right button"><span class="screen-reader-text">Last</span></a>
    <?php endif; ?>
</nav>
