<?php foreach ($values as $prefix => $vocabulary): ?>
<div class="vocabulary">
    <?php if (!$hideVocabulary): ?>
    <h3><?php echo $vocabulary['vocabulary']->label(); ?></h3>
    <?php endif; ?>
    <?php foreach ($vocabulary['properties'] as $localName => $property): ?>
        <div class="property">
        <h4><?php echo $property['property']->label(); ?></h4>
        <?php foreach ($property['values'] as $value): ?>
            <?php 
                $valueType = $value->type(); 
                if ($valueType == 'resource') {
                    $valueType = $value->resource()->getControllerName();
                }
            ?>
            <div class="value <?php echo $valueType; ?>"><?php echo $value; ?></div>
        <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
</div>
<?php endforeach; ?>
