<?php
// Prepare the page layout.
switch ($page->layout()) {
    case 'grid':
        $pageLayoutClass = 'page-layout-grid';
        $gridColumns = (int) $page->layoutDataValue('grid_columns');
        $this->headLink()->appendStylesheet($this->assetUrl('css/page-grid.css', 'Omeka'));
        $this->headStyle()->appendStyle(<<<CSS
            .page-layout-grid {
                grid-template-columns: repeat({$gridColumns}, 1fr);
            }
        CSS);
        break;
    case '':
    default:
        $pageLayoutClass = 'page-layout-normal';
        break;
}
echo sprintf('<div class="blocks-inner %s">', $pageLayoutClass);
$layouts = [];
foreach ($page->blocks() as $block) {
    if (!array_key_exists($block->layout(), $layouts)) {
        // Prepare render only once per block layout type.
        $layouts[$block->layout()] = null;
        $this->blockLayout()->prepareRender($block->layout());
    }
    // Render each block according to page layout.
    switch ($page->layout()) {
        case 'grid':
            $gridColumns = (int) $page->layoutDataValue('grid_columns');
            $blockLayoutData = $block->layoutData();
            $getValidPosition = fn($columnPosition) => in_array($columnPosition, ['auto',...range(1, $gridColumns)]) ? $columnPosition : 'auto';
            $getValidSpan = fn($columnSpan) => in_array($columnSpan, range(1, $gridColumns)) ? $columnSpan : $gridColumns;
            echo sprintf(
                '<div style="grid-column: %s / span %s">%s</div>',
                $getValidPosition($blockLayoutData['grid_column_position'] ?? 'auto'),
                $getValidSpan($blockLayoutData['grid_column_span'] ?? $gridColumns),
                $this->blockLayout()->render($block)
            );
            break;
        case '':
        default:
            echo $this->blockLayout()->render($block);
            break;
    }
}
echo '</div>';
