<?php
$layouts = [];
$groupDepth = 0;
foreach ($page->blocks() as $block) {
    // The groupOpen and groupClose layouts get special treatment. We need to
    // track the group depth to ensure that all groups are closed by the end.
    if ('groupOpen' === $block->layout()) {
        $groupDepth++;
    } elseif ('groupClose' === $block->layout()) {
        if ($groupDepth) {
            $groupDepth--;
        } else {
            continue; // no group to close
        }
    }
    if (!array_key_exists($block->layout(), $layouts)) {
        // Prepare render only once per layout type.
        $layouts[$block->layout()] = null;
        $this->blockLayout()->prepareRender($block->layout());
    }
    echo $this->blockLayout()->render($block);
}
if ($groupDepth) {
    // Close all unclosed groups.
    echo str_repeat('</div>', $groupDepth);
}
