<?php
if ($page->columns()) {
    echo <<<STYLE
    <style>
    #grid {
        display: grid;
        grid-template-columns: repeat({$page->columns()}, 1fr);
        gap: 10px;
    }
    #grid > div {
        border: 1px solid black;
        min-height: 50px;
    }
    </style>
    <div id="grid">
    STYLE;
}
$layouts = [];
foreach ($page->blocks() as $block) {
    if (!array_key_exists($block->layout(), $layouts)) {
        // Prepare render only once per layout type.
        $layouts[$block->layout()] = null;
        $this->blockLayout()->prepareRender($block->layout());
    }
    if ($page->columns()) {
        switch ($block->location()) {
            case 's1':
                echo '<div style="grid-column: span 1">';
                break;
            case 's2':
                echo '<div style="grid-column: span 2">';
                break;
            case 's3':
                echo '<div style="grid-column: span 3">';
                break;
            case 'p1':
                echo '<div style="grid-column: 1">';
                break;
            case 'p2':
                echo '<div style="grid-column: 2">';
                break;
            case 'p3':
                echo '<div style="grid-column: 3">';
                break;
            default:
                echo '<div>';
        }
    }
    echo $this->blockLayout()->render($block);
    if ($page->columns()) {
        echo '</div>';
    }
}
if ($page->columns()) {
    echo '</div>';
}
