<?php
$this->htmlElement('body')->appendAttribute('class', 'page browse');
?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<?php if ($pages): ?>
<ul class="resource-list">
    <?php foreach ($pages as $page): ?>
    <li class="page resource"><h4><?php echo $page->link($page->title()); ?></h4></li>
    <?php endforeach; ?>
</ul>
<?php else: ?>
<p><?php echo $this->translate('No pages found'); ?></p>
<?php endif; ?>
<?php echo $this->pagination(); ?>
