<?php
$translate = $this->plugin('translate');
// Prepare the item set queries
$inIds = $query['item_set_id'] ?? [];
if (!is_array($inIds)) {
    $inIds = [$inIds];
}
$inIds = array_filter($inIds);
$notInIds = $query['not_item_set_id'] ?? [];
if (!is_array($notInIds)) {
    $notInIds = [$notInIds];
}
$notInIds = array_filter($notInIds);

if ($this->status()->isSiteRequest()) {
    if (!$this->layout()->site->siteItemSets()) {
        return;
    }
    $filterLocale = (bool) $this->siteSetting('filter_locale_values');
    $lang = $this->lang();

    $selectOptions = [
        'disable_group_by_owner' => true,
        'query' => ['site_id' => $this->layout()->site->id()],
        'lang' => ($filterLocale == 1 ? $lang : null)
    ];
} else {
    $selectOptions = [];
}
?>
<div id="item-sets" class="field removable multi-value" role="group">
    <div class="field-meta">
        <span id="by-item-set-label" class="label"><?php echo $translate('Search by item set'); ?></span>
        <?php echo $this->hyperlink('', '#', ['class' => 'expand', 'title' => $translate('Expand')]); ?>
        <div class="collapsible">
            <div class="field-description"><?php echo $translate('Searches for items that are assigned to any of these item sets.'); ?></div>
        </div>
        <button type="button" class="add-value o-icon-add button" aria-label="<?php echo $translate('Add new item set'); ?>" title="<?php echo $translate('Add new item set'); ?>"></button>
    </div>
    <div class="inputs">
        <?php if ($inIds || $notInIds): ?>
        <?php foreach ($inIds as $inId): ?>
        <div class="value">
            <select class="item-set-select-type">
                <option value="in" selected><?php echo $translate('In'); ?></option>
                <option value="not_in"><?php echo $translate('Not in'); ?></option>
            </select>
            <?php echo $this->itemSetSelect([
                'name' => 'item_set_id[]',
                'attributes' => [
                    'value' => $inId,
                    'class' => 'item-set-select',
                    'aria-labelledby' =>  'by-item-set-label'
                ],
                'options' => $selectOptions,
            ]); ?>
            <button type="button" class="o-icon-delete remove-value button" aria-label="<?php echo $translate('Remove value'); ?>" title="<?php echo $translate('Remove value'); ?>"></button>
        </div>
        <?php endforeach; ?>
        <?php foreach ($notInIds as $notInId): ?>
        <div class="value">
            <select class="item-set-select-type">
                <option value="in"><?php echo $translate('In'); ?></option>
                <option value="not_in" selected><?php echo $translate('Not in'); ?></option>
            </select>
            <?php echo $this->itemSetSelect([
                'name' => 'not_item_set_id[]',
                'attributes' => [
                    'value' => $notInId,
                    'class' => 'item-set-select',
                    'aria-labelledby' =>  'by-item-set-label'
                ],
                'options' => $selectOptions,
            ]); ?>
            <button type="button" class="o-icon-delete remove-value button" aria-label="<?php echo $translate('Remove value'); ?>" title="<?php echo $translate('Remove value'); ?>"></button>
        </div>
        <?php endforeach; ?>
        <?php else: ?>
        <div class="value">
            <select class="item-set-select-type">
                <option value="in" selected><?php echo $translate('In'); ?></option>
                <option value="not_in"><?php echo $translate('Not in'); ?></option>
            </select>
            <?php echo $this->itemSetSelect([
                'name' => 'item_set_id[]',
                'attributes' => [
                    'value' => null,
                    'class' => 'item-set-select',
                    'aria-labelledby' => 'by-item-set-label'
                ],
                'options' => $selectOptions,
            ]); ?>
            <button type="button" class="o-icon-delete remove-value button" aria-label="<?php echo $translate('Remove value'); ?>" title="<?php echo $translate('Remove value'); ?>"></button>
        </div>
        <?php endif; ?>
    </div>
</div>
<script>
$('form').on('submit', function(e) {
    $('#item-sets').find('.value').each(function() {
        const thisValue = $(this);
        const typeSelect = thisValue.find('.item-set-select-type');
        const itemSetSelect = thisValue.find('.item-set-select');
        if ('not_in' === typeSelect.val()) {
            itemSetSelect.attr('name', 'not_item_set_id[]');
        } else {
            itemSetSelect.attr('name', 'item_set_id[]');
        }
    });
});
</script>
