<?php
// Prepare the item set queries
$ids = isset($query['item_set_id']) ? $query['item_set_id'] : [];
if (!is_array($ids)) {
    $ids = [$ids];
}
$ids = array_filter($ids);
if (!$ids) {
    $ids = [null];
}
?>
<div id="item-sets" class="field removable multi-value" role="group">
    <div class="field-meta">
        <span id="by-item-set-label" class="label"><?php echo $this->translate('Search by item set'); ?></span>
        <?php echo $this->hyperlink('', '#', ['class' => 'expand', 'title' => $this->translate('Expand')]); ?>
        <div class="collapsible">
            <div class="field-description"><?php echo $this->translate('Searches for items that are assigned to any of these item sets.'); ?></div>
        </div>
    </div>
    <div class="inputs">
        <?php foreach ($ids as $id): ?>
        <div class="value">
            <?php echo $this->itemSetSelect([
                'name' => 'item_set_id[]',
                'attributes' => [
                    'value' => $id,
                    'aria-labelledby' =>  'by-item-set-label'
                ],
            ]); ?>
            <button type="button" class="o-icon-delete remove-value button"><?php echo $this->translate('Remove value'); ?></button>
        </div>
        <?php endforeach; ?>
        <a href="#" class="add-value button"><?php echo $this->translate('Add new item set'); ?></a>
    </div>
</div>
