<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$siteSetting = $this->plugin('siteSetting');
$propertySelect = $this->plugin('propertySelect');

$isSiteRequest = $this->status()->isSiteRequest();
$applyTemplates = $isSiteRequest ? $siteSetting('search_apply_templates') : false;

// Prepare the property queries.
$properties = $query['property'] ?? [];
$properties = array_filter($properties, function ($value) {
    return isset($value['text']) ? '' !== trim($value['text']) : true;
});
if (!$properties) {
    $properties[] = [];
}

if (isset($query['search'])) {
    unset($properties[0]['joiner']);
    array_unshift($properties, [
        'property' => '',
        'type' => 'in',
        'text' => $query['search'],
    ]);
}

$queryOption = function ($value, array $search, $key, $text) {
    $selected = null;
    if (isset($search[$key]) && $value === $search[$key]) {
        $selected = ' selected';
    }
    return sprintf('<option value="%s"%s>%s</option>', $value, $selected, $text);
};
$queryText = function (array $search, $index) use ($escape, $translate) {
    $text = $search['text'] ?? null;
    return sprintf('<input type="text" class="query-text" name="%s" value="%s" aria-label="%s">',
        $escape("property[$index][text]"),
        $escape($text),
        $escape($translate('Query text')));
};
?>

<div id="property-queries" class="field removable multi-value" role="group" aria-labelledby="by-value-label">
    <div class="field-meta">
        <span id="by-value-label" class="label"><?php echo $translate('Search by value'); ?></span>
        <button type="button" class="add-value o-icon-add button" aria-label="<?php echo $translate('Add new value'); ?>" title="<?php echo $translate('Add new value'); ?>"></button>
    </div>
    <div class="inputs">
        <?php
        $index = 0;
        foreach ($properties as $property):
            $stem = "property[$index]";
            $propertyList = isset($property['property']) ? (is_array($property['property']) ? $property['property'] : [$property['property']]) : [null];
        ?>
        <div class="value">
            <select class="joiner" name="<?php echo $escape($stem . '[joiner]'); ?>">
                <?php echo $queryOption('and', $property, 'joiner', $translate('AND')); ?>
                <?php echo $queryOption('or', $property, 'joiner', $translate('OR')); ?>
            </select>
            <?php echo $propertySelect([
                'name' => $stem . '[property]',
                'options' => [
                    'empty_option' => '[Any Property]', // @translate
                    'apply_templates' => $applyTemplates,
                ],
                'attributes' => [
                    'class' => 'query-property chosen-select',
                    'value' => $propertyList,
                    'aria-label' => $translate('Property'),
                    'multiple' => true,
                    'data-placeholder' => $translate('Select properties…'),
                ],
            ]); ?>
            <select class="query-type" name="<?php echo $escape($stem . '[type]'); ?>" aria-label="<?php echo $translate('Query type'); ?>">
                <?php echo $queryOption('eq', $property, 'type', $translate('is exactly')); ?>
                <?php echo $queryOption('neq', $property, 'type', $translate('is not exactly')); ?>
                <?php echo $queryOption('in', $property, 'type', $translate('contains')); ?>
                <?php echo $queryOption('nin', $property, 'type', $translate('does not contain')); ?>
                <?php echo $queryOption('res', $property, 'type', $translate('is resource with ID')); ?>
                <?php echo $queryOption('nres', $property, 'type', $translate('is not resource with ID')); ?>
                <?php echo $queryOption('ex', $property, 'type', $translate('has any value')); ?>
                <?php echo $queryOption('nex', $property, 'type', $translate('has no values')); ?>
                <?php echo $queryOption('lex', $property, 'type', $translate('is a linked resource')); ?>
                <?php echo $queryOption('lnex', $property, 'type', $translate('is not a linked resource')); ?>
            </select>
            <?php echo $queryText($property, $index); ?>
            <button type="button" class="o-icon-delete remove-value button" aria-label="<?php echo $translate('Remove value'); ?>" title="<?php echo $translate('Remove value'); ?>"></button>
        </div>
        <?php
            ++$index;
        endforeach;
        ?>
    </div>
</div>
