<?php
// Prepare the property queries.
$properties = isset($query['property']) ? $query['property'] : [];
$properties = array_filter($properties, function ($value) {
    return isset($value['text']) ? '' !== trim($value['text']) : true;
});
if (!$properties) {
    $properties[] = [];
}

if (isset($query['search'])) {
    unset($properties[0]['joiner']);
    array_unshift($properties, [
        'property' => '',
        'type' => 'in',
        'text' => $query['search']
    ]);
}

$queryOption = function($value, array $search, $key, $text) {
    $selected = null;
    if (isset($search[$key]) && $value === $search[$key]) {
        $selected = ' selected';
    }
    return sprintf('<option value="%s"%s>%s</option>', $value, $selected, $text);
};
$queryText = function(array $search, $index) {
    $text = isset($search['text']) ? $search['text'] : null;
    return sprintf('<input type="text" class="query-text" name="%s" value="%s" aria-label="%s">',
        $this->escapeHtml("property[$index][text]"),
        $this->escapeHtml($text),
        $this->escapeHtml($this->translate('Query text')));
}
?>

<div id="property-queries" class="field removable multi-value" role="group" aria-labelledby="by-value-label">
    <div class="field-meta">
        <span id="by-value-label" class="label"><?php echo $this->translate('Search by value'); ?></span>
    </div>
    <div class="inputs">
        <?php
        $index = 0;
        foreach ($properties as $property):
        $stem = "property[$index]";
        ?>
        <div class="value">
            <select class="joiner" name="<?php echo $this->escapeHtml($stem . '[joiner]'); ?>">
                <?php echo $queryOption('and', $property, 'joiner', $this->translate('AND')); ?>
                <?php echo $queryOption('or', $property, 'joiner', $this->translate('OR')); ?>
            </select>
            <?php echo $this->propertySelect([
                'name' => $stem . '[property]',
                'attributes' => [
                    'class' => 'query-property',
                    'value' => isset($property['property']) ? $property['property'] : null,
                    'aria-label' => $this->translate('Property'),
                ],
                'options' => [
                    'empty_option' => '[Any Property]', // @translate
                ]
            ]); ?>
            <select class="query-type" name="<?php echo $this->escapeHtml($stem . '[type]'); ?>" aria-label="<?php echo $this->translate('Query type'); ?>">
                <?php echo $queryOption('eq', $property, 'type', $this->translate('is exactly')); ?>
                <?php echo $queryOption('neq', $property, 'type', $this->translate('is not exactly')); ?>
                <?php echo $queryOption('in', $property, 'type', $this->translate('contains')); ?>
                <?php echo $queryOption('nin', $property, 'type', $this->translate('does not contain')); ?>
                <?php echo $queryOption('res', $property, 'type', $this->translate('is resource with ID')); ?>
                <?php echo $queryOption('nres', $property, 'type', $this->translate('is not resource with ID')); ?>
                <?php echo $queryOption('ex', $property, 'type', $this->translate('has any value')); ?>
                <?php echo $queryOption('nex', $property, 'type', $this->translate('has no values')); ?>
            </select>
            <?php echo $queryText($property, $index); ?>
            <button type="button" class="o-icon-delete remove-value button"><?php echo $this->translate('Remove value'); ?></button>
        </div>
        <?php
        $index++;
        endforeach;

        echo $this->hyperlink($this->translate('Add new value'), '#', ['class' => 'add-value button']);
        ?>
    </div>
</div>
