<div id="site_id_field" class="field" role="group"  aria-labelledby="site-id-field-label">
    <div class="field-meta">
        <label id="site-id-field-label" for="site_id"><?php echo $this->translate('Search by site'); ?></label>
        <button type="button" aria-expanded="false" aria-controls="site-id-description" class="expand" aria-label="<?php echo $this->translate('Expand'); ?>" title="<?php echo $this->translate('Expand'); ?>"></button>
        <div id="site-id-description" class="collapsible">
            <div class="field-description"><?php echo $this->translate('Searches for items that are assigned to this site.'); ?></div>
        </div>
    </div>
    <div class="inputs">
        <?php echo $this->siteSelect([
            'name' => 'site_id',
            'attributes' => [
                'id' => 'site_id',
                'value' => $query['site_id'] ?? null,
            ]
        ]); ?>
    </div>
</div>
