<?php
use Zend\Form\Element\Textarea;
$this->htmlElement('body')->appendAttribute('class', 'edit media sidebar-open');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'));
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
?>

<script type='text/javascript'>
var valuesJson = <?php echo json_encode($media->values()); ?>;
</script>

<h1><?php echo $this->translate('Edit Media'); ?>: "<?php echo $escape($media->displayTitle()); ?>"</h1>

<form method='post' id='edit-media'>
    <?php 
        //produces a <fieldset> with the id and class atts passed in.
        //on, e.g., the item add/edit pages, the id will work with the classes on 
        //the nav lis above. (see globals.js)  
        echo $this->partial(
                'common/resource-fields.phtml',
                array(
                    'id' => 'resource-values',
                    'class' => 'section active',
                    'form' => $form,
                    'resource' => $media
                ));
    ?>

    <fieldset id="page-actions">
        <?php if ($media->isPublic()): ?>
        <a href="#" class="o-icon-public button" aria-label="Make private" title="Make private"></a>
        <input type="hidden" name="o:is_public" value="1">
        <?php else: ?>
        <a href="#" class="o-icon-private button" aria-label="Make public" title="Make public"></a>
        <input type="hidden" name="o:is_public" value="0">
        <?php endif; ?>
        <input type="submit" name="add-item-submit" value="Save">
    </fieldset>
    <?php echo $this->formElement($form->get('csrf')); ?>

    <?php echo $this->media()->updateForm($media); ?>
</form>

<?php 
        echo $this->partial('common/resource-form-templates.phtml');
?>
