<?php
$this->htmlElement('body')->appendAttribute('class', 'edit media sidebar-open');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'));
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
?>

<script type='text/javascript'>
var valuesJson = <?php echo $values; ?>;
var selectedItemValueJson;
</script>

<h1><?php echo $this->translate('Edit media'); ?></h1>
<?php 
if (isset($errors)) {
    print_r($errors);
}
?>

<form method='post' id='edit-media'>
    <?php 
        //produces a <fieldset> with the id and class atts passed in.
        //on, e.g., the item add/edit pages, the id will work with the classes on 
        //the nav lis above. (see globals.js)  
        echo $this->partial(
                'common/resource-fields.phtml',
                array(
                    'id' => 'resource-values',
                    'class' => 'section active',
                    'form' => $form,
                    'resource' => $media
                ));
    ?>

    <fieldset id="page-actions">
        <input type="submit" name="add-item-submit" value="Save changes" />
        <a href="#" class="cancel button">Cancel</a>
    </fieldset>
    <?php echo $this->formElement($form->get('csrf')); ?>
    <input type='hidden' name='o:type' value='<?php echo $media->type(); ?>' />
</form>

<?php 
        echo $this->partial('common/resource-form-templates.phtml');
?>
