<?php
$escape = $this->plugin('escapeHtml');
?>

<div class="resource-details" data-resource-values="<?php echo $this->escapeHtmlAttr($values); ?>">
    <h2 class="o-title"><?php echo $media->link($media->displayTitle()); ?></h2>
    
    <div class="property">
        <h4>Part of Item</h4>
        <?php $mediaItem = $media->item(); ?>
        <div class="value"><?php echo $mediaItem->link($mediaItem->displayTitle()); ?></div>
    </div>
    <div class="property">
        <h4>Visibility</h4>
        <div class="value"><?php echo ($media->isPublic()) ? $this->translate('Public') : $this->translate('Private'); ?></div>
    </div>
    <div class="property">
        <h4>Type</h4>
        <div class="value"><?php echo $media->type(); ?></div>
    </div>
    <div class="property">
        <h4><?php echo $this->translate('MIME Type'); ?></h4>
        <div class="value"><?php echo $escape($media->mediaType()); ?></div>
    </div>
</div>