<?php 
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$mediaFound = count($media) > 0;
?>

<h3><?php echo $this->translate('Select media'); ?></h3>
<div class="search-nav">
    <div id="sidebar-resource-search" class="resource-search" data-search-url="<?php echo $escape($this->url(null, [], [], true)); ?>">
        <input type="text" name="search" value="<?php echo $escape($searchValue); ?>" id="resource-list-search">
        <button type="button" class="o-icon-search"><?php echo $this->translate('Search'); ?></button>
    </div>
    <?php if ($mediaFound): ?>
    <?php echo $this->pagination('common/sidebar-pagination.phtml'); ?>
    <?php endif; ?>
</div>

<div class="resource-list">
    <?php if ($mediaFound): ?>
        <?php foreach ($media as $m):?>
        <div class="resource item-set">
            <?php
            $content = sprintf(
                '%s<span class="resource-name">%s</span>',
                $this->thumbnail($m, 'square'),
                $escape($m->displayTitle())
            );
            echo $hyperlink->raw($content, '#', [
                'class' => 'sidebar-content select-resource resource-link',
                'data-sidebar-content-url' => $m->url('show-details'),
                'data-sidebar-selector' => '#resource-details',
            ]);
            ?>
        </div>
        <?php endforeach; ?>
    <?php else: ?>
        <span class="no-resources"><?php echo $this->translate(sprintf('No %s found.', $this->translate('media'))); ?></span>
    <?php endif; ?>
</div>
