<?php
$escape = $this->plugin('escapeHtml');
$allMedia = null;
$thumbnailUrl = null;
if ($attachedItem) {
    $allMedia = $attachedItem->media();
    $primaryMedia = $attachedItem->primaryMedia();
    if ($attachedMedia) {
        $thumbnailUrl = $attachedMedia->thumbnailUrl('square');
    } elseif ($primaryMedia) {
        $thumbnailUrl = $primaryMedia->thumbnailUrl('square');
    }
}
?>
<?php if ($attachedItem): ?>
<h3 class="item-title"><?php echo $escape($attachedItem->displayTitle()); ?></h3>
<div>
    <?php if ($thumbnailUrl): ?>
    <img class="item-thumbnail" src="<?php echo $escape($thumbnailUrl); ?>">
    <?php endif; ?>
</div>
<?php if ($allMedia): ?>
<ul>
    <?php foreach ($allMedia as $media): ?>
    <?php
    $attached = null;
    if ($attachedMedia && ($attachedMedia->id() === $media->id())) {
        $attached = 'attached';
    }
    ?>
    <li class="media <?php echo $attached; ?>" data-media-id="<?php echo $escape($media->id()); ?>">
        <img class="media-thumbnail" src="<?php echo $escape($media->thumbnailUrl('square')); ?>"> <?php echo $escape($media->displayTitle()); ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<?php else: ?>
<p><?php echo $this->translate('No item selected.'); ?></p>
<?php endif; ?>
