<?php
$this->htmlElement('body')->appendAttribute('class', 'site page browse');
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Pages')); ?>
<?php echo $site->link($this->translate('Add a new page'), 'add-page', array('class' => 'button')); ?>

<?php if ($pages = $site->pages()): ?>
<table id="page-list">
    <thead>
        <th><?php echo $this->translate('Title'); ?></th>
        <th><?php echo $this->translate('Slug'); ?></th>
        <th></th>
    </thead>
    <tbody>
    <?php foreach ($pages as $page): ?>
    <tr class="page value">
        <td>
            <span class="restore-value"><?php echo $this->translate('Page to be removed'); ?></span>
            <?php echo $this->hyperlink($page->title(), $page->siteUrl()); ?>
            <input type="hidden" name="o:page[][o:id]" value="<?php echo $escape($page->id()); ?>">
        </td>
        <td><?php echo $page->slug(); ?></td>
        <td>
            <ul class="actions">
                <li><?php echo $page->link('', 'edit', array(
                    'class' => 'o-icon-edit',
                    'aria-label' => $this->translate('Edit'),
                    'title' => $this->translate('Edit'),
                )); ?></li>
                <li><a href="#" class="o-icon-delete sidebar-confirm" aria-label="#" title="<?php echo $this->translate('Delete page'); ?>" data-page-title="<?php echo $escape($page->title()); ?>" data-sidebar-confirm-url="<?php echo $escape($page->url('delete')); ?>"></a></li>
            </ul>
        </td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $this->translate('Delete page'); ?></h2>
        <p><?php echo $this->translate(sprintf('Are you sure you would like to delete %s?', '"page-title"')); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
</div>
<?php endif; ?>

<script type="text/javascript">
var deleteText = $('#sidebar-confirm p');
var deleteTemplate = deleteText.text();
$('.sidebar-confirm').click(function() {
    deleteText.text(deleteTemplate);
    var pageTitle = $(this).data('page-title');
    console.log(deleteText.text());
    deleteText.text(deleteText.text().replace('page-title', pageTitle));
});
</script>