<?php $this->htmlElement('body')->appendAttribute('class', 'page'); ?>

<header>
    <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
    <nav><?php echo $this->navigation('Zend\Navigation\Site')->menu(); ?></nav>
</header>

<div id="content" role="main">
    <?php
        $nav =  $this->navigation('Zend\Navigation\Site');
        $container = $nav->getContainer();
        $activePage = $nav->findActive($container);
        $breadcrumbs = $this->navigation()->breadcrumbs();
    ?>
    <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs"><?php echo $breadcrumbs; ?></nav>
    <?php endif; ?>
    <?php echo $this->pageTitle($page->title(), 2); ?>
    <?php if ($activePage['page']->hasPages()): ?>
    <nav class="sub-menu"><?php echo $this->navigation()->menu()->renderSubMenu(); ?></nav>
    <?php endif; ?>

    <?php foreach ($page->blocks() as $block): ?>
    <?php echo $this->blockLayout()->render($block);?>
    <?php endforeach; ?>
    <?php echo $this->sitePagePagination(); ?>
</div>