<div class="<?php echo $this->escapeHtml(implode(' ', $classes)); ?>">
    <?php foreach($attachments as $attachment): ?>
    <?php $item = $attachment->item(); ?>
    <?php if ($item): ?>
    <div class="item resource">
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        if ($media):
            echo $media->render([
                'thumbnailType' => $thumbnailType,
                'link' => $link,
            ]);
        endif;
        ?>
        <?php if ($showTitleOption === 'item_title'): ?>
        <h3><?php echo $item->link($item->displayTitle()); ?></h3>
        <?php elseif ($showTitleOption === 'file_name'): ?>
        <h3><?php echo $media->displayTitle(); ?></h3>
        <?php endif; ?>
        <?php $caption = $attachment->caption(); ?>
        <?php if ($caption): ?>
        <div class="caption"><?php echo $caption; ?></div>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <?php endforeach; ?>
</div>
