<?php
$query = [
    'url' => $this->manifestUrl,
    'mirador_config' => json_encode([
        'window.sideBarOpen' => false,
        'selectedTheme' => $this->siteSetting('iiif_viewer_theme', 'light') === 'dark' ? 'dark' : 'light',
    ]),
];
?>
<?php if ($this->showTitle && $this->title): ?>
<h3><?php echo $this->escapeHtml($this->title); ?></h3>
<?php endif; ?>
<?php echo $this->iiifViewer($query, ['title' => $this->title]);
