<div class="list-of-sites">
    <div class="site-list">
        <?php
        foreach($sites as $site):
            if ($site->id() !== $currentSite->id()):
                echo $this->partial('common/site-list-entry', ['site' => $site, 'showSummary' => $summaries]);
            endif;
        endforeach;
        ?>
    </div>
    <?php
    if ($pagination):
        echo $this->pagination();
    endif;
    ?>
</div>
