<?php echo $this->navigation('Zend\Navigation\Site')->menu(); ?>
<h1><?php echo $this->escapeHtml($site->title()); ?></h1>
<?php echo $site->link($site->title()); ?>
<ul>
    <?php foreach ($site->pages() as $page): ?>
    <li><?php echo $page->link($page->title()); ?></li>
    <?php endforeach; ?>
</ul>
<?php echo $this->pagination(); ?>
<ul>
    <?php foreach ($items as $item): ?>
    <li><?php echo $item->link($item->displayTitle()); ?></li>
    <ul>
        <?php foreach ($item->media() as $media): ?>
        <li><?php echo $media->link($media->displayTitle()); ?></li>
        <?php endforeach; ?>
    </ul>
    <?php endforeach; ?>
</ul>
<?php echo $this->pagination(); ?>
