<h1>Edit User &ldquo;<?php echo $user->getUsername(); ?>&rdquo;</h1>
<?php
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formInput = $this->plugin('formInput');
$formErrors = $this->plugin('formElementErrors');
?>

<form  method="post">
<?php foreach ($form->getElements() as $element): ?>
<div class="field">
    <div class="field-meta">
        <?php echo $formLabel($element); ?>
    </div>
    <div class="inputs">
        <?php echo $formInput($element); ?>
    </div>
    <?php echo $formErrors($element); ?>
</div>
<?php endforeach; ?>
<button>Submit</button>
</form>
<pre><?php if (isset($errors)) {print_r($errors);} ?></pre>
