<?php $escape = $this->plugin('escapeHtml'); ?>
<?php $escapeAttr = $this->plugin('escapeHtmlAttr'); ?>
<h1>User &ldquo;<?php echo $escape($user->username()); ?>&rdquo;</h1>
<div id="page-actions">
    <a class="button" href="<?php echo $escapeAttr($user->url('edit')); ?>">Edit User</a>
</div>
<table>
<tr>
<th>Name</th>
<td><?php echo $escape($user->name()); ?></td>
</tr>
<tr>
<th>Email</th>
<td><?php echo $escape($user->email()); ?></td>
</tr>
<tr>
<th>Role</th>
<td><?php echo $escape($user->role()); ?></td>
</tr>
</table>
