<?php
$this->htmlElement('body')->appendAttribute('class', 'add users');
$form->prepare(); 
?>

<?php echo $this->pageTitle($this->translate('New user'), 1, $this->translate('Users')); ?>
<?php echo $this->trigger('view.add.before'); ?>
<?php echo $this->form()->openTag($form); ?>
<?php $this->trigger('view.add.form.before', ['form' => $form]); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Add'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php $this->trigger('view.add.form.after', ['form' => $form]); ?>
<?php echo $this->form()->closeTag(); ?>

<?php $this->trigger('view.add.after'); ?>
