<?php
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
$formErrors = $this->plugin('formElementErrors');
?>
<h1>Add User</h1>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <button>Submit</button>
</div>

<?php foreach ($form->getElements() as $element): ?>
<div class="field">
    <div class="field-meta">
        <?php echo $formLabel($element); ?>
    </div>
    <div class="inputs">
        <?php echo $formElement($element); ?>
    </div>
    <?php echo $formErrors($element, array('class' => 'messages')); ?>
</div>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
