<?php
$this->htmlElement('body')->appendAttribute('class', 'users browse');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>
<h1><?php echo $escape($this->translate('Users')); ?></h1>

<div id="page-actions">
    <?php if ($this->userIsAllowed('Omeka\Api\Adapter\UserAdapter', 'create')): ?>
        <?php echo $this->hyperlink($this->translate('Add new user'), $this->url(null, array('action' => 'add'), true), array('class' => 'button')); ?>
    <?php endif; ?>
</div>

<?php if (count($users)): ?>

<?php echo $this->pagination(); ?>

<table>
    <thead>
        <tr>
            <th><?php echo $this->sortLink($this->translate('Email'), 'email'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Role'), 'role'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Date Created'), 'created'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user): ?>
        <tr>
            <td>
                <span class="resource-name">
                    <?php echo $user->link($user->email() . ' (' . $user->name() . ')'); ?>
                </span>
                <ul class="actions">
                    <?php if ($user->userIsAllowed('update')): ?>
                    <li><?php echo $user->link('', 'edit', array(
                        'class' => 'o-icon-edit',
                        'aria-label' => $this->translate('Edit'),
                        'title' => $this->translate('Edit'),
                    )) ?></li>
                    <?php endif; ?>
                    <?php if ($user->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escapeAttr($user->url('show-details')); ?>"
                        data-sidebar-confirm-url="<?php echo $escapeAttr($user->url('delete')); ?>"
                        class="o-icon-delete sidebar-confirm"
                        aria-label="<?php echo $escapeAttr($this->translate('Delete')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Delete')); ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escapeAttr($user->url('show-details')); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escapeAttr($this->translate('Details')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Details')); ?>"></a></li>
                </ul>
            </td>
            <td><?php echo $escape($this->translate($user->displayRole())); ?></td>
            <td><?php echo $escape($this->i18n()->dateFormat($user->created())); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escapeAttr($this->translate('Close')); ?>"
        title="<?php echo $escapeAttr($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $escape($this->translate('Delete User')); ?></h2>
        <p><?php echo $escape($this->translate('Are you sure you would like to delete this user?')); ?></p>
        <form method="post">
            <button><?php echo $escape($this->translate('Confirm Delete')); ?></button>
        </form>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $escape($this->translate('Omeka could not find any users.')); ?></p>
</div>

<?php endif; ?>
