<?php $form->prepare(); ?>
<h1><?php echo $this->escapeHtml($this->translate(sprintf('Change Password for “%s”', $user->username()))); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->escapeHtml($this->translate('Submit')); ?></button>
    <a href="<?php echo $this->url('admin/default', array('controller'=>'user', 'action'=>'browse')); ?>" class="cancel button">Cancel</a>
</div>
<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\User')->menu(); ?>
</nav>
<?php echo $this->formElements($form); ?>
<?php echo $this->form()->closeTag(); ?>
