<?php $form->prepare(); ?>
<h1><?php echo $this->escapeHtml($this->translate(sprintf('Change Password for “%s”', $user->username()))); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->escapeHtml($this->translate('Submit')); ?></button>
</div>
<nav class="section-nav">
    <?php echo $this->navigation('Omeka\Navigation\User')->menu(); ?>
</nav>
<?php echo $this->formElements($form); ?>
<?php echo $this->form()->closeTag(); ?>
