<?php $form->prepare(); ?>
<h1><?php echo $this->escapeHtml($this->translate(sprintf('Edit API Keys for “%s”', $user->username()))); ?></h1>
<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <button><?php echo $this->escapeHtml($this->translate('Submit')); ?></button>
</div>

<nav class="section-nav">
    <?php echo $this->navigation('Omeka\Navigation\User')->menu(); ?>
</nav>

<?php if ($keys): ?>
<h2 id="keys-existing-heading"><?php echo $this->escapeHtml($this->translate('Keys')); ?></h2>
<table>
    <thead>
        <tr>
            <th>Label</th>
            <th>ID</th>
            <th>Delete?</th>
        </tr>
    </thead>
    <?php foreach ($keys as $id => $label): ?>
    <tr>
        <td><?php echo $this->escapeHtml($label); ?></td>
        <td><code><?php echo $this->escapeHtml($id); ?></code></td>
        <td>
            <input type="checkbox"
                name="delete[]"
                value="<?php echo $this->escapeHtmlAttr($id); ?>"
                aria-label="Mark key &ldquo;<?php echo $this->escapeHtmlAttr($label); ?>&rdquo; for deletion">
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>

<h2 id="keys-add-heading"><?php echo $this->escapeHtml($this->translate('Add a New Key')); ?></h2>
<?php echo $this->formElements($form); ?>
<?php echo $this->form()->closeTag(); ?>
