<?php $form->prepare(); ?>
<h1><?php echo sprintf($this->translate('Edit User: "%s"'), $this->escapeHtml($user->email())); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Save'); ?></button>
</div>
<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\User')->menu(); ?>
</nav>
<?php echo $this->formElements($form); ?>
<?php echo $this->form()->closeTag(); ?>
