<?php 
    $this->htmlElement('body')->appendAttribute('class', 'users show');
    $escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle(sprintf($this->translate('User: “%s”'), $user->email())); ?>

<div id="page-actions">
    <?php if ($user->userIsAllowed('update')): ?>
        <a class="button" href="<?php echo $escape($user->url('edit')); ?>"><?php echo $this->translate('Edit User'); ?></a>
    <?php endif; ?>
</div>

<div class="property">
    <h4><?php echo $this->translate('Email'); ?></h4>
    <div class="value">
        <?php echo $escape($user->email()); ?>
    </div>
</div>
<div class="property">
    <h4><?php echo $this->translate('Display Name'); ?></h4>
    <div class="value">
        <?php echo $escape($user->name()); ?>
    </div>
</div>
<div class="property">
    <h4><?php echo $this->translate('Role'); ?></h4>
    <div class="value">
        <?php echo $escape($user->displayRole()); ?>
    </div>
</div>
