<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'users show');
?>

<?php echo $this->pageTitle($user->email(), 1, $translate('Users')); ?>

<div id="page-actions">
    <?php if ($user->userIsAllowed('update')): ?>
        <a class="button" href="<?php echo $escape($user->url('edit')); ?>"><?php echo $translate('Edit user'); ?></a>
    <?php endif; ?>
</div>

<?php $this->trigger('view.show.before'); ?>
<div class="property">
    <h4><?php echo $translate('Email'); ?></h4>
    <div class="value">
        <?php echo $escape($user->email()); ?>
    </div>
</div>
<div class="property">
    <h4><?php echo $translate('Display name'); ?></h4>
    <div class="value">
        <?php echo $escape($user->name()); ?>
    </div>
</div>
<div class="property">
    <h4><?php echo $translate('Role'); ?></h4>
    <div class="value">
        <?php echo $escape($translate($user->displayRole())); ?>
    </div>
</div>
<div class="property">
    <h4><?php echo $translate('Is active'); ?></h4>
    <div class="value">
        <?php echo $escape($user->isActive() ? $translate('yes') : $translate('no')); ?>
    </div>
</div>
<div class="property sites">
    <h4><?php echo $this->translate('Sites'); ?></h4>
    <?php $sites = $user->sites(); ?>
    <?php if (empty($sites)): ?>
    <div class="value no-value">
        <?php echo $escape($this->translate('None')); ?>
    </div>
    <?php else: ?>
    <div class="value">
    <ul style="list-style: none; margin: 0; padding-left: 0;">
    <?php foreach ($sites as $site): ?>
        <li>
            <span class="actions" style="display: initial; margin-right: 6px;">
            <?php echo $this->hyperlink('', $site->siteUrl(), [
                'target' => '_blank',
                'class' => 'o-icon-external public',
                'title' => $this->translate('View public site'),
            ]); ?>
            </span>
            <?php echo $site->link($site->title()); ?>
        </li>
    <?php endforeach; ?>
    </ul>
    </div>
    <?php endif; ?>
</div>
<div class="property site-permissions">
    <h4><?php echo $this->translate('Site permissions'); ?></h4>
    <?php $sitePermissions = $user->sitePermissions(); ?>
    <?php if (empty($sitePermissions)): ?>
    <div class="value no-value">
        <?php echo $escape($this->translate('None')); ?>
    </div>
    <?php else: ?>
    <div class="value">
    <ul style="margin: 0;">
    <?php foreach ($sitePermissions as $sitePermission): ?>
        <li>
            <?php $site = $sitePermission->site(); ?>
            <?php echo sprintf('%s (%s)',
                $site->link($site->title(), 'users'),
                $escape($this->translate($sitePermission->role()))); ?>
        </li>
    <?php endforeach; ?>
    </ul>
    </div>
    <?php endif; ?>
</div>
<?php $this->trigger('view.show.after'); ?>
