<?php
$this->htmlElement('body')->appendAttribute('class', 'add item sidebar-open');
?>

<?php echo $this->pageTitle($this->translate('Add Item')); ?>

<?php
echo $this->partial('omeka/admin/item/form.phtml', [
    'form' => $form,
    'item' => null,
    'mediaForms' => $mediaForms,
    'submitLabel' => $this->translate('Add'),
    'formAfterEvent' => 'view.add.form.after',
    'sectionNavEvent' => 'view.add.section_nav',
]);
?>

<?php $this->trigger('view.add.after'); ?>
