<?php
$this->htmlElement('body')->appendAttribute('class', 'items browse');
$confirmForm->prepare();
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Items')); ?>

<?php echo $this->searchFilters(); ?>

<div id="page-actions">
    <?php if ($this->userIsAllowed('Omeka\Api\Adapter\ItemAdapter', 'create')): ?>
    <?php echo $this->hyperlink($this->translate('Add new item'), $this->url(null, array('action' => 'add'), true), array('class' => 'button')); ?>
    <?php endif; ?>
</div>

<?php if (count($items) > 0): ?>

<?php echo $this->hyperlink($this->translate('Advanced item search'), $this->url(null, array('action' => 'search'), true), array('class' => 'advanced-search')); ?>

<?php echo $this->pagination(); ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <?php echo $this->sortLink($this->translate('Title'), 'dcterms:title'); ?>
                <span class="mobile-heading"><?php echo $this->translate('Title'); ?></span>
            </th>
            <th>
                <?php echo $this->sortLink($this->translate('Class'), 'resource_class_label'); ?>
                <span class="mobile-heading"><?php echo $this->translate('Class'); ?></span>
            </th>
            <th>
                <?php echo $this->sortLink($this->translate('Owner'), 'owner_name'); ?>
                <span class="mobile-heading"><?php echo $this->translate('Owner'); ?></span>
            </th>
            <th>
                <?php echo $this->sortLink($this->translate('Date Created'), 'created'); ?>
                <span class="mobile-heading"><?php echo $this->translate('Date Created'); ?></span>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $item): ?>
        <?php
        if ($owner = $item->owner()) {
            $ownerText = $this->hyperlink(
                $owner->name(),
                $this->url('admin/id', array(
                    'controller' => 'user',
                    'action' => 'show',
                    'id' => $owner->id())
                )
            );
        } else {
            $ownerText = $this->translate('[no owner]');
        }
        ?>
        <tr>
            <td>
                <ul class="actions">
                    <?php if ($item->userIsAllowed('update')): ?>
                    <li><?php echo $item->link('', 'edit', array(
                        'class' => 'o-icon-edit',
                        'aria-label' => $this->translate('Edit'),
                        'title' => $this->translate('Edit'),
                    )); ?></li>
                    <?php endif; ?>
                    <?php if ($item->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($item->url('show-details')); ?>"
                        data-sidebar-confirm-url="<?php echo $escape($item->url('delete')); ?>"
                        class="o-icon-delete sidebar-confirm"
                        aria-label="<?php echo $escape($this->translate('Delete')); ?>"
                        title="<?php echo $escape($this->translate('Delete')); ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($item->url('show-details')); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escape($this->translate('Details')); ?>"
                        title="<?php echo $escape($this->translate('Details')); ?>"></a></li>
                </ul>
                <?php if ($media = $item->primaryMedia()): ?>
                <img src="<?php echo $escape($media->thumbnailUrl('square')); ?>">
                <?php endif; ?>
                <span class="resource-name">
                    <?php echo $item->link($item->displayTitle()); ?>
                </span>
                <?php if (!$item->isPublic()): ?>
                    <span class="o-icon-private"></span>
                <?php endif; ?>
            </td>
            <td><?php echo $escape($item->displayResourceClassLabel()); ?></td>
            <td><?php echo $ownerText; ?></td>
            <td><?php echo $escape($this->i18n()->dateFormat($item->created())); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->pagination(); ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $escape($this->translate('Delete Item')); ?></h2>
        <p><?php echo $escape($this->translate('Are you sure you would like to delete this item?')); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any items.'); ?></p>
</div>

<?php endif; ?>

<?php $this->trigger('view.browse.after'); ?>
