<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'edit item sidebar-open');
$deleteButton = '<a href="#" class="delete button">' . $this->translate('Delete') . '</a>';
$confirmForm->setAttribute('action', $item->url('delete'));
?>

<script type='text/javascript'>
var valuesJson = <?php echo json_encode($item->values()); ?>;
</script>

<?php echo $this->pageTitle(sprintf($this->translate('Edit Item: “%s”'), $item->displayTitle())); ?>

<?php
echo $this->partial('omeka/admin/item/form.phtml', [
    'form' => $form,
    'item' => $item,
    'mediaForms' => $mediaForms,
    'submitLabel' => $this->translate('Save'),
    'deleteButton' => $deleteButton
]);
?>

<?php
echo $this->partial('common/delete-confirm', [
    'record' => $this->translate('item'),
    'confirmForm' => $confirmForm
]);
?>

<?php $this->trigger('view.edit.after'); ?>
