<?php
$escape = $this->plugin('escapeHtml');
$this->headScript()->appendFile($this->assetUrl('js/sortable.js', 'Omeka'));

?>
<legend><?php echo $this->translate('Media'); ?></legend>
<?php foreach ($mediaForms as $type => $form): ?>
<span
    id="media-template-<?php echo $escape($type); ?>"
    data-template="<?php echo $escape($form['form']); ?>"
></span>
<?php endforeach; ?>

<div id="media-list">
<?php if ($resource && $resource->media()): ?>
    <?php
    $i = 0;
    foreach ($resource->media() as $media):
    ?>
    <div class="media value row">
        <ul class='actions'>
            <li>
            <?php if ($media->isPublic()): ?>
            <a href="#"
            class="o-icon-public"
            aria-label="<?php echo $escape($this->translate('Make private')); ?>"
            title="<?php echo $escape($this->translate('Make private')); ?>">
            </a>
            <input type="hidden" name="o:media[<?php echo $i; ?>][o:is_public]" value="1">
            <?php else: ?>
            <a href="#"
            class="o-icon-private"
            aria-label="<?php echo $escape($this->translate('Make public')); ?>"
            title="<?php echo $escape($this->translate('Make public')); ?>">
            </a>
            <input type="hidden" name="o:media[<?php echo $i; ?>][o:is_public]" value="0">
            <?php endif; ?>
            </li>
            <li><?php echo $media->link('', 'edit', [
                'class'      => 'o-icon-edit',
                'aria-label' => $this->translate('Edit'),
                'title'      => $this->translate('Edit'),
                'target'     => '_blank'
            ]); ?></li>
            <li>
                <a href='#'
                class='o-icon-delete remove-value'
                title=' <?php echo $escape($this->translate('Remove value')); ?>'
                aria-label='<?php echo $escape($this->translate('Remove value')); ?>'>
                </a>
            </li>
            <li>
                <a href='#'
                class='o-icon-undo restore-value'
                title='<?php echo $escape($this->translate('Undo remove value')); ?>'
                aria-label='<?php echo $escape($this->translate('Undo remove value')); ?>'>
                </a>
            </li>
        </ul>
        <span class='restore-value'><?php echo $this->translate('Media to be removed'); ?></span>
        <img src="<?php echo $escape($media->thumbnailUrl('square')); ?>">
        <span class="resource-name"><?php echo $escape($media->displayTitle()); ?></span>
        <input type="hidden" name="o:media[<?php echo $i; ?>][o:id]" value="<?php echo $escape($media->id()); ?>">
        <span class="sortable-handle"></span>
    </div>
    <?php
    $i++;
    endforeach;
    ?>
<?php else: ?>
    <div class="no-resources">
        <p><?php echo $this->translate('This resource has no media.<br>Start adding media using the sidebar to the right.'); ?></p>
    </div>
<?php endif; ?>
</div>
<button id="media-selector-button" class="mobile-only"><?php echo $this->translate('Add media'); ?></button>

<div id="media-selector" class="always-open sidebar">
    <a href="#" class="mobile-only sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $this->translate('Close Me'); ?></span></a>
    <h3><?php echo $this->translate('Add New Media'); ?></h3>
    <?php foreach ($mediaForms as $type => $form): ?>
    <button type="button" data-media-type="<?php echo $escape($type); ?>"><?php echo $escape($this->translate($form['label'])); ?></option>
    <?php endforeach; ?>
</div>

<script type="text/javascript">

var list = document.getElementById('media-list');
new Sortable(list, {
    draggable: ".media",
    handle: ".sortable-handle"
});

var index = <?php echo ($resource) ? count($resource->media()) : 0; ?>;

$('#media-selector button').click(function () {
    var type = $(this).data('media-type');
    if (!type) {
        return;
    }

    var template = $('#media-template-' + type).data('template');
    $('#media-list').append(
        template.replace(/__index__/g, index++)
    );
    $(this).val('');
    $('html, body').animate({
        scrollTop: ($('.media-field-wrapper').last().offset().top -100)
    },200);
    $('#media-list .no-resources').hide();
});

$('#item-media').on('click', 'a.remove-new-media-field', function (e) {
    e.preventDefault();
    $(this).parents(".media-field-wrapper").remove();
    if ($('.media-field-wrapper').length < 1) {
        $('#media-list .no-resources').show();
    }
});

</script>
