<?php
$escape = $this->plugin('escapeHtml');
?>
<legend><?php echo $this->translate('Item Sets'); ?></legend>
<table id="item-item-sets" class="<?php echo ($item && $item->itemSets()) ? '' : 'empty'; ?>">
    <thead>
    <tr>
        <th><?php echo $this->translate('Title'); ?></th>
        <th><?php echo $this->translate('Owner'); ?></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php if ($item && $item->itemSets()): ?>
    <?php foreach ($item->itemSets() as $itemSet): ?>
    <?php
    if ($owner = $itemSet->owner()) {
        $ownerText = $escape($itemSet->owner()->name());
    } else {
        $ownerText = $this->translate('[no owner]');
    }
    ?>
    <tr>
        <td><?php echo $escape($itemSet->displayTitle()); ?></td>
        <td><?php echo $ownerText; ?></td>
        <td><ul class="actions">
            <li><a
                class="o-icon-delete"
                href="#"
                title=" <?php echo $escape($this->translate('Remove item set')); ?>"
                aria-label=" <?php echo $escape($this->translate('Remove item set')); ?>">
            </a></li>
        </ul><input type="hidden" name="o:item_set[]" value="<?php echo $escape($itemSet->id()) ?>"></td>
    </tr>
    <?php endforeach; ?>
    <?php endif; ?>
    </tbody>
</table>

<div class="no-resources">
    <p><?php echo $this->translate('This item is part of no item sets. Add it to an item set using the interface to the right.'); ?></p>
</div>

<button id="item-set-selector-button" class="mobile-only"><?php echo $this->translate('Add to item set'); ?></button>

<?php
$itemSetTemplate = '
<tr>
    <td class="item-set-title"></td>
    <td class="owner-email">__owner-email__</td>
    <td><ul class="actions">
        <li><a href="#"
        class="o-icon-delete"
        title="' . $escape($this->translate('Remove item set')) . '"
        aria-label="' . $escape($this->translate('Remove item set')) . '">
        </a></li>
    </ul><input type="hidden" name="o:item_set[]"></td>
</tr>';
?>
<span id="item-set-template" data-template="<?php echo $escape($itemSetTemplate); ?>"></span>

<?php echo $this->itemSetSelector(); ?>

<script>
// Add the selected item set to the edit panel.
$('#item-set-selector .selector-child').click(function(event) {
    event.preventDefault();

    $('#item-item-sets').removeClass('empty');
    var itemSetId = $(this).data('item-set-id');

    if ($('#item-item-sets').find("input[value='" + itemSetId + "']").length) {
        return;
    }

    var row = $($('#item-set-template').data('template'));
    var itemSetTitle = $(this).data('child-search');
    var ownerEmail = $(this).data('owner-email');
    row.children('td.item-set-title').text(itemSetTitle);
    row.children('td.owner-email').text(ownerEmail);
    row.find('td > input').val(itemSetId);
    $('#item-item-sets > tbody:last').append(row);
});

// Remove an item set from the edit panel.
$('#item-item-sets').on('click', '.o-icon-delete', function(event) {
    event.preventDefault();

    var removeLink = $(this);
    var itemSetRow = $(this).closest('tr');
    var itemSetInput = removeLink.closest('td').find('input');
    itemSetInput.prop('disabled', true);

    // Undo remove item set link.
    var undoRemoveLink = $('<a>', {
        href: '#',
        class: 'fa fa-undo',
        title: 'Undo remove item set',
        click: function(event) {
            event.preventDefault();
            itemSetRow.toggleClass('delete');
            itemSetInput.prop('disabled', false);
            removeLink.show();
            $(this).remove();
        },
    });

    itemSetRow.toggleClass('delete');
    undoRemoveLink.insertAfter(removeLink);
    removeLink.hide();
});
</script>
