<?php
$escape = $this->plugin('escapeHtml');
?>

<h3><?php echo $this->translate('Select Item'); ?></h3>
<div class="search-nav">
    <div id="sidebar-resource-search" class="resource-search">
        <input type="text" value="<?php echo $escape($searchValue); ?>" id="resource-list-search">
        <button
        data-search-url="<?php echo $escape($this->url(null, [], [], true)); ?>"
        type="button" class="o-icon-search"><?php echo $this->translate('Search'); ?></button>
    </div>
<?php echo $this->pagination('common/sidebar-pagination.phtml'); ?>
</div>

<div class="resource-list">

<!-- here to let me work on the javascript and ajax for showing resource details -->
    <?php foreach ($items as $item):?>
    <div class="resource item" data-resource-values="<?php echo $escape(json_encode($item->valueRepresentation())); ?>">
        <?php if ($media = $item->primaryMedia()): ?>
        <img src="<?php echo $escape($media->thumbnailUrl('square')); ?>">
        <?php endif; ?>
        <span class="resource-name">
            <?php if ($showDetails): ?>
            <a href="#" class="sidebar-content" data-sidebar-content-url="<?php echo $escape($item->url('show-details')); ?>" data-sidebar-selector="#resource-details"><?php echo $escape($item->displayTitle()); ?></a>
            <?php else: ?>
            <a href="#" class="select-resource"><?php echo $escape($item->displayTitle()); ?></a>
            <?php endif; ?>
        </span>
    </div>
    <?php endforeach; ?>
</div>


