<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation|null $site
 * @var \Sparql\Form\SparqlForm $form
 * @var array $result array representation of a standard sparql response
 * @var \EasyRdf\Sparql\Result|\EasyRdf\Graph|null $resultEasyRdf Unused currently.
 * @var string $query
 * @var string $format "text" or "html"
 * @var string $interface "default" or "yasgui"
 * @var array $namespaces
 * @var string $errorMessage
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
?>

<?= $this->pageTitle($translate('Sparql'), 1, $translate('Triplestore')) ?>

<?= $this->partial('common/sparql-search') ?>
