<?php $form->prepare(); ?>

<?php echo $this->pageTitle(sprintf($this->translate('Edit User: “%s”'), $user->email())); ?>

<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Save'); ?></button>
</div>
<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\User')->menu(); ?>
</nav>
<?php
foreach ($form as $element) {
    echo $this->formRow($element);
}
?>
<?php echo $this->form()->closeTag(); ?>
