<?php $form->prepare(); ?>

<?php echo $this->pageTitle(sprintf($this->translate('Edit User: “%s”'), $user->email())); ?>

<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Save'); ?></button>
</div>
<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\User')->menu(); ?>
</nav>
<?php echo $this->formCollection($form, false); ?>
<?php $this->trigger('view.edit.form.after'); ?>
<?php echo $this->form()->closeTag(); ?>

<?php $this->trigger('view.edit.after'); ?>
