<?php $form->prepare(); ?>

<?php echo $this->pageTitle(sprintf($this->translate('Edit API Keys for “%s”'), $user->email())); ?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <button><?php echo $this->escapeHtml($this->translate('Submit')); ?></button>
    <a href="<?php echo $this->url('admin/default', ['controller'=>'user', 'action'=>'browse']); ?>" class="cancel button"><?php echo $this->translate('Cancel'); ?></a>
</div>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\User')->menu(); ?>
</nav>

<?php if ($keys): ?>
<h2 id="keys-existing-heading"><?php echo $this->translate('Keys'); ?></h2>
<table>
    <thead>
        <tr>
            <th><?php echo $this->translate('Label'); ?></th>
            <th><?php echo $this->translate('ID'); ?></th>
            <th><?php echo $this->translate('Delete'); ?>?</th>
        </tr>
    </thead>
    <?php foreach ($keys as $id => $label): ?>
    <tr>
        <td><?php echo $this->escapeHtml($label); ?></td>
        <td><code><?php echo $this->escapeHtml($id); ?></code></td>
        <td>
            <input type="checkbox"
                name="delete[]"
                value="<?php echo $this->escapeHtml($id); ?>"
                aria-label="Mark key &ldquo;<?php echo $this->escapeHtml($label); ?>&rdquo; for deletion">
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>

<h2 id="keys-add-heading"><?php echo $this->translate('Add a New Key'); ?></h2>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>
