<h2><a href="<?php echo $this->escapeHtml($user->url()); ?>"><?php echo $this->escapeHtml($user->name()); ?></a></h2>

<div class="meta-group">
    <h4><?php echo $this->translate('Items'); ?></h4>
    <div class="value"><?php echo $this->hyperlink($user->itemCount(), $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['owner_id' => $user->id()]])); ?></div>
</div>

<div class="meta-group">
    <h4><?php echo $this->translate('Item Sets'); ?></h4>
    <div class="value"><?php echo $this->hyperlink($user->itemSetCount(), $this->url('admin/default', ['controller' => 'item-set', 'action' => 'browse'], ['query' => ['owner_id' => $user->id()]])); ?></div>
</div>