<h1><?php echo $this->setting('installation_title', 'Omeka S'); ?></h1>
<h2><?php echo $this->translate('Advanced search'); ?></h2>

<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'items'], true)); ?>">
    <div id="page-actions">
        <?php echo $this->hyperlink($this->translate('Reset'), $this->url(null, [], true), ['class' => 'button']); ?>
        <input type="submit" name="submit" value="<?php echo $this->escapeHtml($this->translate('Search')); ?>">
    </div>
    <?php echo $this->partial('common/advanced-search', ['query' => $this->params()->fromQuery(), 'resourceType' => 'item']); ?>
</form>
