<h1><?php echo $this->setting('installation_title', 'Omeka S'); ?></h1>

<?php echo $this->partial(
  'omeka/search/form.phtml',
  ['fulltextSearch' => $this->escapeHtml($this->params()->fromQuery('fulltext_search'))]
); ?>

<?php echo $this->hyperlink($this->translate('Advanced item search'), $this->url(null, ['action' => 'advanced', 'class' => 'advanced-search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']); ?>

<h2><?php echo $this->translate('Item results'); ?></h2>

<?php echo $this->pagination(); ?>

<div class="item-results">
    <ul>
        <?php foreach ($items as $item): ?>
        <?php $sites = $item->sites(); ?>
        <li>
            <?php echo $item->displayTitle(); ?>
            <ul>
                <?php foreach ($sites as $site): ?>
                <li><?php echo $this->hyperlink($site->title(), $item->siteUrl($site->slug())); ?></li>
                <?php endforeach; ?>
            </ul>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php echo $this->pagination(); ?>
