<h1><?php echo $this->setting('installation_title', 'Omeka S'); ?></h1>
<h2><?php echo $this->translate('Item results'); ?></h2>

<form action="<?php echo $this->escapeHtml($this->url(null, [], true)); ?>">
    <input type="text" name="fulltext_search" value="<?php echo $this->escapeHtml($this->params()->fromQuery('fulltext_search')); ?>">
    <input type="submit">
</form>

<?php echo $this->pagination(); ?>
<?php echo $this->hyperlink($this->translate('Advanced search'), $this->url(null, ['action' => 'advanced'], ['query' => $this->params()->fromQuery()], true)); ?>

<ul>
    <?php foreach ($items as $item): ?>
    <?php $sites = $item->sites(); ?>
    <li>
        <?php echo $item->displayTitle(); ?>
        <ul>
            <?php foreach ($sites as $site): ?>
            <li><?php echo $this->hyperlink($site->title(), $item->siteUrl($site->slug())); ?></li>
            <?php endforeach; ?>
        </ul>
    </li>
    <?php endforeach; ?>
</ul>

<?php echo $this->pagination(); ?>
