<h1><?php echo $this->setting('installation_title', 'Omeka S'); ?></h1>
<?php echo $this->partial(
  'omeka/search/form.phtml',
  ['fulltextSearch' => $this->escapeHtml($this->params()->fromQuery('fulltext_search'))]
); ?>

<h2><?php echo $this->translate('Site page results'); ?></h2>

<?php echo $this->pagination(); ?>

<div class="site-results">
  <ul>
      <?php foreach ($sitePages as $sitePage): ?>
      <li><?php echo $this->hyperlink($sitePage->title(), $sitePage->siteUrl()); ?></li>
      <?php endforeach; ?>
  </ul>
</div>

<?php echo $this->pagination(); ?>
