<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'jobs browse');
?>

<?php echo $this->pageTitle($translate('Jobs')); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->browse()->renderSortSelector('jobs'); ?>
</div>
<?php $this->trigger('view.browse.before'); ?>

<?php if (count($jobs)): ?>
<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th aria-sort="<?php echo $this->browse()->getAriaSortValue('id'); ?>"><?php echo $this->sortLink($translate('ID'), 'id'); ?></th>
            <th aria-sort="<?php echo $this->browse()->getAriaSortValue('class'); ?>"><?php echo $this->sortLink($translate('Class'), 'class'); ?></th>
            <th aria-sort="<?php echo $this->browse()->getAriaSortValue('status'); ?>"><?php echo $this->sortLink($translate('Status'), 'status'); ?></th>
            <th aria-sort="<?php echo $this->browse()->getAriaSortValue('owner_email'); ?>"><?php echo $this->sortLink($translate('Owner'), 'owner_email'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($jobs as $job): ?>
        <?php
        if ($owner = $job->owner()) {
            $ownerText = $this->hyperlink($owner->email(), $this->url(
                'admin/id',
                [
                    'controller' => 'user',
                    'action' => 'show',
                    'id' => $owner->id()]
                )
            );
        } else {
            $ownerText = $translate('[No owner]');
        }
        ?>
        <tr>
            <td>
                <?php echo $job->link($escape($job->id())); ?>
            </td>
            <td><?php echo $escape($job->jobClass()); ?></td>
            <td><?php echo $escape($translate($job->statusLabel())); ?></td>
            <td><?php echo $ownerText; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $translate('Omeka could not find any jobs.'); ?></p>
</div>

<?php endif; ?>
