<?php
$this->htmlElement('body')->appendAttribute('class', 'jobs browse');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>

<h1><?php echo $escape($this->translate('Jobs')); ?></h1>

<?php if (count($jobs)): ?>

<?php echo $this->pagination(); ?>

<table>
    <thead>
        <tr>
            <th><?php echo $this->sortLink($this->translate('ID'), 'id'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Class'), 'class'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Status'), 'status'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Owner'), 'owner_username'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($jobs as $job): ?>
        <tr>
            <td>
                <span class="resource-name">
                    <?php echo $escape($job->id()); ?>
                </span>
                <ul class="actions">
                    <?php if ('in_progress' == $job->status()): ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escapeAttr($job->url('show-details')); ?>"
                        data-sidebar-confirm-url="<?php echo $escapeAttr($job->url('stop')); ?>"
                        class="o-icon-delete sidebar-confirm"
                        aria-label="<?php echo $escapeAttr($this->translate('Stop')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Stop')); ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escapeAttr($job->url('show-details')); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escapeAttr($this->translate('Details')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Details')); ?>"></a></li>
                </ul>
            </td>
            <td><?php echo $escape($job->jobClass()); ?></td>
            <td><?php echo $escape($job->status()); ?></td>
            <td><?php echo $this->hyperlink($job->owner()->username(), $this->url('admin/id', array('controller' => 'user', 'action' => 'show', 'id' => $job->owner()->id()))); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->pagination(); ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escapeAttr($this->translate('Close')); ?>"
        title="<?php echo $escapeAttr($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $escape($this->translate('Stop Job')); ?></h2>
        <p><?php echo $escape($this->translate('Are you sure you would like to attempt to stop this job?')); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $escape($this->translate('Omeka could not find any jobs.')); ?></p>
</div>

<?php endif; ?>

