<?php
if ($job->started()) {
    $started = $this->i18n()->dateFormat($job->started(), 'long', 'long');
} else {
    $started = $this->translate('[not started]');
}
if ($job->ended()) {
    $ended = $this->i18n()->dateFormat($job->ended(), 'long', 'long');
} else {
    $ended = $this->translate('[not ended]');
}
?>
<h2><?php echo sprintf($this->translate('Job #%s'), $this->escapeHtml($job->id())); ?></h2>
<div class="meta-group">
    <h4><?php echo $this->translate('Status'); ?></h4>
    <div class="value"><?php echo $job->statusLabel(); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Started'); ?></h4>
    <div class="value"><?php echo $started; ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Ended'); ?></h4>
    <div class="value"><?php echo $ended; ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Class'); ?></h4>
    <div class="value"><?php echo $job->jobClass(); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Owner'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($job->owner()->email()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Args'); ?></h4>
    <?php if ($job->args()): ?>
    <?php echo $this->hyperlink($this->translate('view args'),
        $this->url(null, array('action' => 'args'), true),
        array('target' => '_blank')) ?>
    <?php else: ?>
    <p><?php echo $this->translate('[no args]') ?></p>
    <?php endif; ?>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Log'); ?></h4>
    <?php if ($job->log()): ?>
    <?php echo $this->hyperlink($this->translate('view log'),
        $this->url(null, array('action' => 'log'), true),
        array('target' => '_blank')) ?>
    <?php else: ?>
    <p><?php echo $this->translate('[no log]') ?></p>
    <?php endif; ?>
</div>
