<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<div class="sidebar" id="page-list">
  <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $translate('Close'); ?></span></a>
  <div class="sidebar-content">
    <h3><?php echo $translate('Select Pages'); ?></h3>
  </div>
  <button type="button" class="option template" value=""></button>
  <div class="pages"></div>
</div>