<?php
$translate = $this->plugin('translate');
?>
<h3><?php echo $this->escapeHtml($translate($resourceClass->label())); ?></h3>
<div class="meta-group">
    <h4><?php echo $translate('Vocabulary'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($translate($resourceClass->vocabulary()->label())); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $translate('Term'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($resourceClass->term()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $translate('Comment'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($translate($resourceClass->comment())); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $translate('Items'); ?></h4>
    <div class="value"><?php echo $this->hyperlink($resourceClass->itemCount(), $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['resource_class_id' => $resourceClass->id()]])); ?></div>
</div>
<?php $this->trigger('view.details', array('entity' => $resourceClass)); ?>
