<?php
$this->htmlElement('body')->appendAttribute('class', 'vocabs browse');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>
<h1>Vocabularies</h1>
<div id="page-actions">
    <a href="#" class="button">Import new vocabulary</a>
</div>
<table>
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($vocabularies as $vocabulary): ?>
        <tr>
            <td>
                <a href="<?php echo $escapeAttr($vocabulary->url('show')); ?>"><span class="resource-name"><?php echo $escape($vocabulary->label()); ?></span></a>
                <ul class="actions">
                    <li><a href="#"
                        data-show-details-action="<?php echo $escapeAttr($vocabulary->url('show-details')); ?>"
                        class="o-icon-more sidebar-details"
                        aria-label="<?php echo $escapeAttr($this->translate('Details')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Details')); ?>"></a>
                    </li>
                </ul>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div id="sidebar">
    <a href="#"
        id="sidebar-close"
        class="o-icon-close"
        aria-label="<?php echo $escapeAttr($this->translate('Close')); ?>"
        title="<?php echo $escapeAttr($this->translate('Close')); ?>"></a>
    <div id="sidebar-content"></div>
</div>
