<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'items'], true)); ?>">
    <?php echo $this->partial('common/advanced-search', ['query' => $this->params()->fromQuery(), 'resourceType' => 'item']); ?>
    <div class="advanced-search-actions">
        <?php echo $this->hyperlink($this->translate('Reset'), $this->url(null, [], true), ['class' => 'button']); ?>
        <input type="submit" name="submit" value="<?php echo $this->escapeHtml($this->translate('Search')); ?>">
    </div>
</form>
