<?php
$element = new \Laminas\Form\Element\Select('has_features');
$element->setLabel($this->translate('Search by map feature presence'))
    ->setValueOptions([
        '1' => $this->translate('Has map features'),
        '0' => $this->translate('Has no map features'),
    ])
    ->setEmptyOption($this->translate('Select map feature presence…'))
    ->setValue($query['has_features'] ?? '')
    ->setAttribute('id', 'has_features');
echo $this->formRow($element);
?>
