<?php
$this->headLink()->prependStylesheet($this->assetUrl('css/advanced-search.css', 'Omeka'));

// Prepare the resource class query.
if (isset($query['resource_class_id'])) {
    $resourceClassId = $query['resource_class_id'] ;
} else {
    $resourceClassId = null;
}

// Prepare the item set queries
$itemSetIds = [[]];
if (isset($query['item_set_id'])) {
    $itemSetIds = [];
    foreach ($query['item_set_id'] as $id) {
        $itemSetIds[] = ['id' => $id];
    }
}

// Prepare the value queries.
$values = [[]];
if (isset($query['value'])) {
    $values = [];
    $types = ['eq', 'neq', 'in', 'nin'];
    foreach ($types as $type) {
        if (isset($query['value'][$type])) {
            foreach ($query['value'][$type] as $text) {
                $values[] = ['type' => $type, 'text' => $text];
            }
        }
    }
}

// Prepare the property queries.
$properties = [[]];
if (isset($query['property'])) {
    $properties = [];
    $types = ['eq', 'neq', 'in', 'nin'];
    foreach ($query['property'] as $id => $null) {
        foreach ($types as $type) {
            if (isset($query['property'][$id][$type])) {
                foreach ($query['property'][$id][$type] as $text) {
                    $properties[] = ['type' => $type, 'text' => $text, 'id' => $id];
                }
            }
        }
    }
}

// Prepare the has property queries.
$hasProperties = [[]];
if (isset($query['has_property'])) {
    $hasProperties = [];
    foreach ($query['has_property'] as $id => $type) {
        $hasProperties[] = ['id' => $id, 'type' => $type];
    }
}

// Convenience functions to minimize inline code.
$getId = function(array $search) {
    if (isset($search['id'])) {
        return $search['id'];
    }
    return null;
};
$queryOption = function($type, array $search, $text) {
    $selected = null;
    if (isset($search['type']) && $type === $search['type']) {
        $selected = ' selected';
    }
    return sprintf('<option value="%s"%s>%s</option>', $type, $selected, $text);
};
$queryText = function(array $search) {
    $text = null;
    if (isset($search['text'])) {
        $text = $search['text'];
    }
    return sprintf('<input type="text" class="query-text" value="%s">',  $this->escapeHtml($text));
}
?>
<div class="field">
    <div class="field-meta">
        <legend><?php echo $this->translate('Search by class'); ?></legend>
    </div>
    <div class="inputs">
        <?php echo $this->resourceClassSelect()->setValue($resourceClassId)->render('resource_class_id'); ?>
    </div>
</div>

<div id="value-queries" class="field removable">
    <div class="field-meta">
        <legend><?php echo $this->translate('Search all properties'); ?></legend>
    </div>
    <div class="inputs">
        <?php foreach ($values as $value): ?>
        <div class="value">
            <select class="query-type">
                <?php echo $queryOption('eq', $value, $this->translate('has exact value')); ?>
                <?php echo $queryOption('neq', $value, $this->translate('does not have exact value')); ?>
                <?php echo $queryOption('in', $value, $this->translate('contains value')); ?>
                <?php echo $queryOption('nin', $value, $this->translate('does not contain value')); ?>
            </select>
            <?php echo $queryText($value); ?>
            <button type="button" class="o-icon-delete remove-value button"><?php echo $this->translate('Remove value'); ?></button>
        </div>
        <?php endforeach; ?>
        <a href="#" class="add-value button"><?php echo $this->translate('Add new value'); ?></a>
    </div>
</div>

<div id="property-queries" class="field removable">
    <div class="field-meta">
        <legend><?php echo $this->translate('Search specific property'); ?></legend>
    </div>
    <div class="inputs">
        <?php foreach ($properties as $property): ?>
        <div class="value">
            <?php echo $this->propertySelect()->setValue($getId($property))->setAttributes(['class' => 'query-property'])->render('property'); ?>
            <select class="query-type">
                <?php echo $queryOption('eq', $property, $this->translate('has exact value')); ?>
                <?php echo $queryOption('neq', $property, $this->translate('does not have exact value')); ?>
                <?php echo $queryOption('in', $property, $this->translate('contains value')); ?>
                <?php echo $queryOption('nin', $property, $this->translate('does not contain value')); ?>
            </select>
            <?php echo $queryText($property); ?>
            <button type="button" class="o-icon-delete remove-value button"><?php echo $this->translate('Remove value'); ?></button>
        </div>
        <?php endforeach; ?>
        <a href="#" class="add-value button"><?php echo $this->translate('Add new value'); ?></a>
    </div>
</div>

<div id="has-property-queries" class="field removable">
    <div class="field-meta">
        <legend><?php echo $this->translate('Search resources'); ?></legend>
    </div>
    <div class="inputs">
        <?php foreach ($hasProperties as $hasProperty): ?>
        <div class="value">
            <select class="query-type">
                <?php echo $queryOption(1, $hasProperty, $this->translate('has property')); ?>
                <?php echo $queryOption(0, $hasProperty, $this->translate('does not have property')); ?>
            </select>
            <?php echo $this->propertySelect()->setValue($getId($hasProperty))->setAttributes(['class' => 'query-property'])->render('property'); ?>
            <button type="button" class="o-icon-delete remove-value button"><?php echo $this->translate('Remove value'); ?></button>
        </div>
        <?php endforeach; ?>
        <a href="#" class="add-value button"><?php echo $this->translate('Add new value'); ?></a>
    </div>
</div>

<?php if (isset($resourceType) && 'item' === $resourceType): ?>
<div id="item-sets" class="field removable">
    <div class="field-meta">
        <legend><?php echo $this->translate('Search by item set'); ?></legend>
        <a href="#" class="expand" aria-label=" Expand"></a>
        <div class="collapsible">
            <div class="field-description"><?php echo $this->translate('Searches for items that are assigned to any of these item sets.'); ?></div>
        </div>
    </div>
    <div class="inputs">
        <?php foreach ($itemSetIds as $itemSetId): ?>
        <div class="value">
            <?php echo $this->itemSetSelect()->setValue($getId($itemSetId))->render('item_set_id[]'); ?>
            <button type="button" class="o-icon-delete remove-value button"><?php echo $this->translate('Remove value'); ?></button>
        </div>
        <?php endforeach; ?>
        <a href="#" class="add-value button"><?php echo $this->translate('Add new item set'); ?></a>
    </div>
</div>
<?php endif; ?>

<?php $this->trigger('view.advanced_search'); ?>
