<div id="item-options" class="sidebar">
    <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $this->translate('Close Me'); ?></span></a>
    <h2><?php echo $this->translate('Item Options'); ?></h2>
    <div class="current-item" data-item-id="">
        <span class="item-title"></span>
        <button class="item-select" data-sidebar-content-url="<?php echo $this->url('admin/default',
            ['controller' => 'item', 'action' => 'sidebar-select'],
            ['query' => $site->itemPool()]
        ); ?>"><?php echo $this->translate('Select item'); ?></button>
    </div>
    <div>
        <label><?php echo $this->translate('Caption'); ?></label>
        <textarea class="caption wysiwyg"></textarea>
    </div>
    <div class="confirm-panel">
        <button><?php echo $this->translate('Apply changes'); ?></button>
    </div>
</div>