<?php
// Prepare the item set queries
$itemSetIds = [null];
if (isset($query['item_set_id'])) {
    $itemSetIds = $query['item_set_id'];
    if (!is_array($itemSetIds)) {
        $itemSetIds = [$itemSetIds];
    }
}
?>
<div id="item-sets" class="field removable" role="group" aria-labelledby="by-item-set-label">
    <div class="field-meta">
        <span id="by-item-set-label" class="label"><?php echo $this->translate('Search by item set'); ?></span>
        <a href="#" class="expand" aria-label=" Expand"></a>
        <div class="collapsible">
            <div class="field-description"><?php echo $this->translate('Searches for items that are assigned to any of these item sets.'); ?></div>
        </div>
    </div>
    <div class="inputs">
        <?php foreach ($itemSetIds as $itemSetId): ?>
        <div class="value">
            <?php echo $this->itemSetSelect([
                'name' => 'item_set_id[]',
                'attributes' => ['value' => $itemSetId],
            ]); ?>
            <button type="button" class="o-icon-delete remove-value button"><?php echo $this->translate('Remove value'); ?></button>
        </div>
        <?php endforeach; ?>
        <a href="#" class="add-value button"><?php echo $this->translate('Add new item set'); ?></a>
    </div>
</div>
