<?php
$escape = $this->plugin('escapeHtml');
?>
<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Subject'); ?></th>
            <th><?php echo $this->translate('Predicate'); ?></th>
            <th><?php echo $this->translate('Object'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($objectValues as $value): ?>
        <?php
        $resource = $value->valueResource();
        $property = $value->property();
        ?>
        <tr>
            <td><?php echo $this->translate('This'); ?></td>
            <td><?php echo $escape($property->label()); ?></td>
            <td><?php echo $resource->link($resource->displayTitle()); ?></td>
        </tr>
        <?php endforeach; ?>

        <?php foreach ($subjectValues as $value): ?>
        <?php
        $resource = $value->resource();
        $property = $value->property();
        ?>
        <tr>
            <td><?php echo $resource->link($resource->displayTitle()); ?></td>
            <td><?php echo $escape($property->label()); ?></td>
            <td><?php echo $this->translate('This'); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
