<?php $escape = $this->plugin('escapeHtml'); ?>

<fieldset class="resource-values field template">
    <div class="field-meta">
        <legend class="field-label"></legend>
        <a href="#" class="collapse" aria-label="<?php echo $escape($this->translate('Collapse')); ?>"></a>
        <div class="collapsible">
            <div class="field-description"></div>
            <div class="field-term" title="<?php echo $escape($this->translate('Property term for development use')); ?>"></div>
        </div>
    </div>
    <div class="inputs">
        <div class="values">
            <p class="no-values"><?php echo $this->translate('Select the first value type.'); ?></p>
        </div>
        <div class="add-values">
            <label class="add-value o-icon-add"><?php echo $this->translate('Add value'); ?></label>
            <a href="#" class="add-value button o-icon-literal" data-type="literal"><?php echo $this->translate('Text'); ?></a>
            <a href="#" class="add-value button o-icon-resource" data-type="resource"><?php echo $this->translate('Omeka Resource'); ?></a>
            <a href="#" class="add-value button o-icon-uri" data-type="uri"><?php echo $this->translate('URI'); ?></a>
        </div>
    </div>
</fieldset>

<?php echo $this->dataType()->getTemplates(); ?>
