<?php $escape = $this->plugin('escapeHtml'); ?>
<?php if (count($filters) > 0): ?>
<div class="search-filters">
    <?php foreach ($filters as $filterLabel => $filterValues): ?>
    <div class="filter">
        <span class="filter-label"><?php echo $escape($filterLabel); ?></span>
        <?php foreach ($filterValues as $filterValue): ?>
        <span class="filter-value"><?php echo $escape($filterValue); ?></span>
        <?php endforeach; ?>
    </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
