<form method="post">
    <button name="submit" value="install">Install</button>
</form>  

<?php if(!$success):?>
<h1>FAIL</h1>
<?php endif; ?>
<dl>
<?php foreach($messages as $taskMessage): ?>
    <dt>
    <?php echo $taskMessage['taskName']; ?>
    </dt>
    <?php foreach($taskMessage['messages'] as $message):?>
        <dd><?php echo $message['code'];?> <?php echo $message['message'];?></dd>
        <?php if($message['exception']):?>
        <?php $e = $message['exception']; ?>
        <dd>
        <?php echo $e->getMessage(); ?>
        </dd>
        <?php endif; ?>
    <?php endforeach; ?>
</dl>
<?php endforeach;?>
    
