<form  method="post">
<label for='username'>Username</label> <input type='text' name='username' /><br>
<label for='password'>Password</label> <input type='password' name='password' /><br>
<label for='name'>Name</label> <input type='text' name='name' /><br>
<label for='email'>Email</label> <input type='text' name='email' /><br>
<button>Submit</button>
</form>
<pre><?php print_r($installation_messages); ?></pre>
