<?php
$translate = $this->plugin('translate');
?>
<div class="language-wrapper">
    <button type="button" class="value-language o-icon-language" title="<?php echo $translate('Set language'); ?>" aria-label="<?php echo $translate('Set language'); ?>"></button>
    <label class="language-label">
        <span class="value-label-text"><?php echo $translate('Language'); ?></span>
        <input class="value-language" type="text" list="value-languages" data-value-key="@language">
    </label>
</div>
<textarea name="" class="input-value to-require" data-value-key="@value"></textarea>
