<?php
$translate = $this->plugin('translate');
?>
<?php echo $this->hyperlink('', '#', ['class' => 'value-language o-icon-language', 'title' => $translate('Set language'), ]); ?>
<input class="value-language" type="text" data-value-key="@language" aria-label="<?php echo $translate('Language'); ?>">
<select class="value-language" data-value-key="@language" aria-label="<?php echo $translate('Language'); ?>" disabled="disabled"></select>
<textarea name="" class="input-value to-require" data-value-key="@value"></textarea>
