<?php
$escape = $this->plugin('escapeHtml');
?>
<span class="o-icon-resource label"><?php echo $this->translate('Omeka resource'); ?></span>
<span class="default"><?php echo $this->translate('No resource selected'); ?></span>
<p class="selected-resource">
    <span class="o-title"></span>
    <input type="hidden" class="value to-require" data-value-key="value_resource_id">
</p>
<a href="#item-resource-select"  class="o-icon-items button resource-select" data-sidebar-content-url="<?php echo $escape($this->url('admin/default', ['controller' => 'item', 'action' => 'sidebar-select'], false)); ?>"><?php echo $this->translate('Items'); ?></a>
<a href="#itemset-resource-select" class="o-icon-item-sets button resource-select" data-sidebar-content-url="<?php echo $escape($this->url('admin/default', ['controller' => 'item-set', 'action' => 'sidebar-select'], false)); ?>"><?php echo $this->translate('Item Sets'); ?></a>
