<?php
$translate = $this->plugin('translate');
?>
<?php echo $this->hyperlink('', '#', ['class' => 'value-language o-icon-language', 'title' => $translate('Set language'), ]); ?>
<input class="value-language" type="text" list="value-languages" data-value-key="o:lang" aria-label="<?php echo $translate('Language'); ?>">
<div class="input">
    <label class="value">
        <?php echo $translate('URI'); ?>
        <input type="text" class="value to-require" data-value-key="@id">
    </label>
</div>
<div class="input">
    <label class="value-label">
        <?php echo $translate('Label'); ?>
        <textarea class="value-label" rows="1" data-value-key="o:label"></textarea>
    </label>
</div>
