<div class="input-body">
    <div class="input">
        <label class="value">
            <?php echo $this->translate('URI'); ?>
            <input type="text" class="value to-require touched" data-value-key="@id">
        </label>
    </div>
    <div class="input">
        <label class="value-label">
            <?php echo $this->translate('Label'); ?>
            <textarea class="value-label" rows="1" data-value-key="o:label"></textarea>
        </label>
    </div>
</div>
