<div class="input-body">
    <div class="language-wrapper">
        <button type="button" class="value-language o-icon-language" title="<?php echo $this->translate('Set language'); ?>" aria-label="<?php echo $this->translate('Set language'); ?>"></button>
        <label class="language-label">
            <span class="value-label-text"><?php echo $this->translate('Language'); ?></span>
            <input class="value-language" type="text" list="value-languages" data-value-key="@language">
        </label>
    </div>
    <textarea data-value-key="@value"></textarea>
</div>
