<?php
$this->headScript()->appendFile($this->assetUrl('js/admin-form.js', 'CustomVocab'));
$translate = $this->plugin('translate');
?>
<?php $form->prepare(); ?>
<?php echo $this->pageTitle($translate('Add'), 1, $translate('Custom Vocab')); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url('admin/custom-vocab', ['action' => 'browse'], true), ['class' => 'button']); ?>
    <button><?php echo $this->escapeHtml($translate('Save')); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>
