<div>
    <h2><?php echo $this->translate('Pages'); ?></h2>
    <?php if ($pages): ?>
    <ul>
        <?php foreach ($pages as $page): ?>
        <li><?php echo $page->link($page->title()); ?></li>
        <?php endforeach; ?>
    </ul>
    <?php echo $this->hyperlink(
        $this->translate('View all results'),
        $this->url(
            'site/page-search',
            ['controller' => 'index', 'action' => 'search'],
            ['query' => ['fulltext_search' => $this->params()->fromQuery('fulltext_search')]],
            true
        )
    ); ?>
    <?php else: ?>
    <p><?php echo $this->translate('No pages found'); ?></p>
    <?php endif; ?>
</div>
<div>
    <h2><?php echo $this->translate('Items'); ?></h2>
    <?php if ($items): ?>
    <ul>
        <?php foreach ($items as $item): ?>
        <li><?php echo $item->link($item->title()); ?></li>
        <?php endforeach; ?>
    </ul>
    <?php echo $this->hyperlink(
        $this->translate('View all results'),
        $this->url(
            'site/resource',
            ['controller' => 'item', 'action' => 'browse'],
            ['query' => ['fulltext_search' => $this->params()->fromQuery('fulltext_search')]],
            true
        )
    ); ?>
    <?php else: ?>
    <p><?php echo $this->translate('No items found'); ?></p>
    <?php endif; ?>
</div>
