<?php
$this->htmlElement('body')->appendAttribute('class', 'vocabs browse');
$confirmForm->prepare();
$escape = $this->plugin('escapeHtml');
$sortHeadings = [
    [
        'label' => $this->translate('Label'),
        'value' => 'label'
    ],
    [
        'label' => $this->translate('Prefix'),
        'value' => 'prefix'
    ],
    [
        'label' => $this->translate('Classes'),
        'value' => 'resource_class_count'
    ],
    [
        'label' => $this->translate('Properties'),
        'value' => 'property_count'
    ]
];
?>

<?php echo $this->pageTitle($this->translate('Vocabularies')); ?>

<div id="page-actions">
    <?php if ($this->userIsAllowed('Omeka\Api\Adapter\VocabularyAdapter', 'create')): ?>
    <?php echo $this->hyperlink($this->translate('Import new vocabulary'), $this->url(null, array('action' => 'import'), true), array('class' => 'button')); ?>
    <?php endif; ?>
</div>

<?php if (count($vocabularies) > 0): ?>

<?php echo $this->pagination(); ?>

<?php echo $this->sortSelector($sortHeadings); ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Label'); ?></th>
            <th><?php echo $this->translate('Prefix'); ?></th>
            <th><?php echo $this->translate('Classes'); ?></th>
            <th><?php echo $this->translate('Properties'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($vocabularies as $vocabulary): ?>
        <tr>
            <td>
                <span class="resource-name">
                    <?php echo $escape($vocabulary->label()); ?>
                </span>
                <ul class="actions">
                    <?php if (!$vocabulary->isPermanent()): ?>
                    <?php if ($vocabulary->userIsAllowed('update')): ?>
                    <li><?php echo $vocabulary->link('', 'edit', array(
                        'class' => 'o-icon-edit',
                        'aria-label' => $escape($this->translate('Edit')),
                        'title' => $escape($this->translate('Edit')),
                    )); ?></li>
                    <?php endif; ?>
                    <?php if ($vocabulary->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($vocabulary->url('show-details')); ?>"
                        data-sidebar-confirm-url="<?php echo $escape($vocabulary->url('delete')); ?>"
                        class="o-icon-delete sidebar-confirm"
                        aria-label="<?php echo $escape($this->translate('Delete')); ?>"
                        title="<?php echo $escape($this->translate('Delete')); ?>"></a></li>
                    <?php endif; ?>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($vocabulary->url('show-details')); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escape($this->translate('Details')); ?>"
                        title="<?php echo $escape($this->translate('Details')); ?>"></a>
                    </li>
                </ul>
            </td>
            <td><?php echo $escape($this->translate($vocabulary->prefix())); ?></td>
            <td><?php echo $this->hyperlink($vocabulary->resourceClassCount(), $this->url('admin/id', array('action' => 'classes', 'id' => $vocabulary->id()), true)); ?></td>
            <td><?php echo $this->hyperlink($vocabulary->propertyCount(), $this->url('admin/id', array('action' => 'properties', 'id' => $vocabulary->id()), true)); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->pagination(); ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $this->translate('Delete Vocabulary'); ?></h2>
        <p><?php echo $this->translate('Are you sure you would like to delete this vocabulary?'); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any vocabularies.'); ?></p>
</div>

<?php endif; ?>
