<?php $form->prepare(); ?>

<?php echo $this->pageTitle(sprintf($this->translate('Edit Vocabulary: “%s”'), $vocabulary->label())); ?>
<?php $this->trigger('view.edit.before'); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <a href="#" class="delete button"><?php echo $this->translate('Delete'); ?></a>
    <button><?php echo $this->translate('Save'); ?></button>
</div>
<?php $this->trigger('view.edit.form.before', ['form' => $form]); ?>
<?php echo $this->formCollection($form, false); ?>
<?php $this->trigger('view.edit.form.after', ['form' => $form]); ?>
<?php echo $this->form()->closeTag(); ?>
<?php echo $this->deleteConfirm($vocabulary, 'vocabulary'); ?>

<?php $this->trigger('view.edit.after'); ?>
