<?php 
$this->htmlElement('body')->appendAttribute('class', 'vocabs import');
$form->prepare(); 
?>

<?php echo $this->pageTitle($this->translate('Import Vocabulary')); ?>

<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Import'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>
