<?php 
$this->htmlElement('body')->appendAttribute('class', 'vocabs import');
$form->prepare(); 
?>

<?php echo $this->pageTitle($this->translate('Import Vocabulary')); ?>

<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Import'); ?></button>
</div>
<?php
foreach ($form as $element) {
    echo $this->formRow($element);
}
?>
<?php echo $this->form()->closeTag(); ?>
