<header>
    <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
    <nav><?php echo $this->navigation('Zend\Navigation\Site')->menu(); ?></nav>
</header>

<div id="content" role="main">
    <?php echo $this->pageTitle($media->displayTitle(), 2); ?>
    <?php echo $media->render(); ?>
    <?php echo $media->displayValues(); ?>
</div>

<?php $this->trigger('view.show.after'); ?>
