<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'modules configure');
?>

<?php echo $this->pageTitle($module->getName(), 1, $translate('Modules'), $translate('Configure')); ?>

<form method="post">
<div id="page-actions">
    <button><?php echo $translate('Submit'); ?></button>
</div>
<?php echo $configForm; ?>
<?php echo $this->formElement($csrfForm->get($csrfForm->getName() . '_csrf')); ?>
</form>
