<?php
$translate = $this->plugin('translate');
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'add resource-templates'); ?>

<?php echo $this->pageTitle($translate('New resource template'), 1, $translate('Resource templates')); ?>

<?php
echo $this->partial(
    'omeka/admin/resource-template/form.phtml',
    [
        'form' => $form,
        'propertyFieldset' => $propertyFieldset,
        'resourceTemplate' => null,
        'submitLabel' => $translate('Add'),
        'action' => 'add',
    ]
);
?>

<?php $this->trigger('view.add.after'); ?>
