<?php
$this->htmlElement('body')->appendAttribute('class', 'resource-templates browse');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>

<h1><?php echo $escape($this->translate('Resource Templates')); ?></h1>

<div id="page-actions">
    <?php if ($this->userIsAllowed('Omeka\Api\Adapter\ResourceTemplateAdapter', 'create')): ?>
    <?php echo $this->hyperlink($this->translate('Add new resource template'), $this->url(null, array('action' => 'add'), true), array('class' => 'button')); ?>
    <?php endif; ?>
</div>

<?php if (count($resourceTemplates)): ?>

<?php echo $this->pagination(); ?>

<table>
    <thead>
        <tr>
            <th><?php echo $this->sortLink($this->translate('Label'), 'label'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Class'), 'resource_class_label'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Items'), 'item_count'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($resourceTemplates as $resourceTemplate): ?>
        <tr>
            <td>
                <span class="resource-name">
                    <?php echo $resourceTemplate->link($resourceTemplate->label()); ?>
                </span>
                <ul class="actions">
                    <?php if ($resourceTemplate->userIsAllowed('update')): ?>
                    <li><?php echo $resourceTemplate->link('', 'edit', array(
                        'class' => 'o-icon-edit',
                        'aria-label' => $this->translate('Edit'),
                        'title' => $this->translate('Edit'),
                    )); ?></li>
                    <?php endif; ?>
                    <?php if ($resourceTemplate->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escapeAttr($resourceTemplate->url('show-details')); ?>"
                        data-sidebar-confirm-url="<?php echo $escapeAttr($resourceTemplate->url('delete')); ?>"
                        class="o-icon-delete sidebar-confirm"
                        aria-label="<?php echo $escapeAttr($this->translate('Delete')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Delete')); ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escapeAttr($resourceTemplate->url('show-details')); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escapeAttr($this->translate('Details')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Detail')); ?>"></a></li>
                 </ul>
            </td>
            <td><?php echo $escape($resourceTemplate->displayResourceClassLabel()); ?></td>
            <td><?php echo $this->hyperlink($resourceTemplate->itemCount(), $this->url('admin/default', array('controller' => 'item', 'action' => 'browse'), array('query' => array('resource_template_id' => $resourceTemplate->id())))); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escapeAttr($this->translate('Close')); ?>"
        title="<?php echo $escapeAttr($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $escape($this->translate('Delete Template')); ?></h2>
        <p><?php echo $escape($this->translate('Are you sure you would like to delete this resource template?')); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $escape($this->translate('Omeka could not find any resource templates.')); ?></p>
</div>

<?php endif; ?>

