<?php $this->htmlElement('body')->appendAttribute('class', 'edit resource-template sidebar-open'); ?>
<h1><?php echo $this->translate('Edit Resource Template'); ?></h1>
<?php
echo $this->partial(
    'omeka/admin/resource-template/form.phtml',
    array(
        'form' => $form,
        'propertyRows' => $propertyRows,
        'resourceClassId' => $resourceClassId,
        'submitLabel' => $this->translate('Edit resource template'),
    )
);
?>
