<?php
$form->prepare();
$this->htmlElement('body')->appendAttribute('class', 'resource-templates import');
echo $this->pageTitle($this->translate('Import'), 1, $this->translate('Resource templates'));
?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Review import'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>
