<?php
$translate = $this->plugin('translate');
$form->prepare();
$this->htmlElement('body')->appendAttribute('class', 'resource-templates import');
echo $this->pageTitle($translate('Import'), 1, $translate('Resource templates'));
?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $translate('Review import'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>
