<?php
$property = $propertyRow['o:property'];
$alternateLabel = $propertyRow['o:alternate_label'];
$alternateComment = $propertyRow['o:alternate_comment'];
$namePrefix = 'o:resource_template_property[' . $property->id() . ']';
?>
<tr>
    <td>
        <input type="hidden" name="<?php echo $this->escapeHtmlAttr($namePrefix . '[o:property][o:id]'); ?>" value="<?php echo $this->escapeHtmlAttr($property->id()); ?>">
        <?php echo $this->escapeHtml($property->label()); ?> (<?php echo $this->escapeHtml($property->vocabulary()->label()); ?>)<br>
        <span><?php echo $this->escapeHtml($property->term()); ?></span>
    </td>
    <td><input type="text" name="<?php echo $this->escapeHtmlAttr($namePrefix . '[o:alternate_label]'); ?>" value="<?php echo $this->escapeHtmlAttr($alternateLabel); ?>"></td>
    <td><textarea name="<?php echo $this->escapeHtmlAttr($namePrefix . '[o:alternate_comment]'); ?>"><?php echo $this->escapeHtml($alternateComment); ?></textarea></td>
    <td></td>
</tr>
