<?php
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>
<h2><?php echo $resourceTemplate->link($resourceTemplate->label()); ?></h2>
<?php if ($resourceTemplate->resourceClass()): ?>
<div class="meta-group">
    <h4>Class</h4>
    <div class="value"><?php echo $resourceTemplate->resourceClass()->label(); ?></div>
</div>
<?php endif; ?>
<?php foreach ($resourceTemplate->resourceTemplateProperties() as $resourceTemplateProperty): ?>
<?php 
$property = $resourceTemplateProperty['o:property']->getRepresentation();   
$propertyAltLabel =$escape($resourceTemplateProperty['o:alternate_label']);
$propertyAltComment =$escape($resourceTemplateProperty['o:alternate_comment']); 
?>
<div class="meta-group">
    <h4><?php echo ($propertyAltLabel) ? $propertyAltLabel : $property->label(); ?></h4>
    <div class="comment"><?php echo ($propertyAltComment) ? $propertyAltComment : $property->comment(); ?></div>
</div>
<?php endforeach; ?>
