<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'resource-templates show');
?>

<?php echo $this->pageTitle($resourceTemplate->label(), 1, $translate('Resource templates')); ?>

<div id="page-actions">
    <a class="button" href="<?php echo $this->escapeHtml($this->url(null, ['action' => 'export'], true)); ?>"><?php echo $translate('Export'); ?></a>
    <?php if ($resourceTemplate->userIsAllowed('update')): ?>
    <a class="button" href="<?php echo $escape($resourceTemplate->url('edit')); ?>"><?php echo $translate('Edit resource template'); ?></a>
    <?php endif; ?>
</div>

<?php if ($resourceTemplate->resourceClass()): ?>
<div class="class-row">
    <span class="class-label"><?php echo $translate('Class'); ?></span>
    <span class="class-value"><?php echo $translate($resourceTemplate->resourceClass()->label()); ?></span>
</div>
<?php endif; ?>

<div>
    <dl><?php foreach ($resourceTemplate->settings() as $key => $value): ?>
        <?php if (!$value) continue; ?>
        <dt><?php echo str_replace('_', ' ', $key); ?></dt>
        <?php if (is_array($value)): ?>
            <?php foreach ($value as $k => $v): ?>
        <dd><?php echo $escape((is_numeric($k) ? '' : $k . ' = ') . $v); ?></dd>
            <?php endforeach; ?>
        <?php else: ?>
        <dd><?php echo $escape($value); ?></dd>
        <?php endif; ?>
        <?php endforeach;
    ?></dl>
</div>

<table id="properties" class="tablesaw tablesaw-stack" data-tablesaw-mode="stack">
    <thead>
    <tr>
        <th><?php echo $translate('Original label'); ?></th>
        <th><?php echo $translate('Data type'); ?></th>
        <th><?php echo $translate('Alternate label'); ?></th>
        <th><?php echo $translate('Alternate comment'); ?></th>
        <th><?php echo $translate('Required?'); ?></th>
        <th><?php echo $translate('Private?'); ?></th>
        <th><?php echo $translate('Other settings'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($resourceTemplate->resourceTemplateProperties() as $resourceTemplateProperty): ?>
        <?php $property = $resourceTemplateProperty->property(); ?>
        <tr data-property-id="<?php echo $escape($property->id()); ?>">
            <td>
                <?php echo $escape($translate($property->label())); ?>
                <ul class="actions">
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-content-url' => $property->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?php echo $escape($resourceTemplateProperty->dataTypeLabel()); ?></td>
            <td><?php echo $escape($resourceTemplateProperty->alternateLabel()); ?></td>
            <td><?php echo $escape($resourceTemplateProperty->alternateComment()); ?></td>
            <td><?php echo $resourceTemplateProperty->isRequired() ? $translate('Yes') : $translate('No'); ?></td>
            <td><?php echo $resourceTemplateProperty->isPrivate() ? $translate('Yes') : $translate('No'); ?></td>
            <td><dl><?php foreach ($resourceTemplateProperty->settings() as $key => $value): ?>
                <?php if (!$value) continue; ?>
                <dt><?php echo str_replace('_', ' ', $key); ?></dt>
                <?php if (is_array($value)): ?>
                    <?php foreach ($value as $k => $v): ?>
                <dd><?php echo $escape((is_numeric($k) ? '' : $k . ' = ') . $v); ?></dd>
                    <?php endforeach; ?>
                <?php else: ?>
                <dd><?php echo $escape($value); ?></dd>
                <?php endif; ?>
            <?php endforeach;
            ?></dl></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php $this->trigger('view.show.after'); ?>
