<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$property = $propertyRow['o:property'];
$namePrefix = 'o:resource_template_property[' . bin2hex(random_bytes(8)) . ']';
$propertyId = $escape($property->id());
?>

<li class="property row" data-property-id="<?php echo $propertyId; ?>">

    <input class="property-id" type="hidden" name="<?php echo $namePrefix . '[o:property][o:id]'; ?>" value="<?php echo $escapeAttr($property->id()); ?>">
    <input class="original-label" type="hidden" name="<?php echo $namePrefix . '[o:original_label]'; ?>" value="<?php echo $escapeAttr($translate($property->label())); ?>">
    <input class="alternate-label" type="hidden" name="<?php echo $namePrefix . '[o:alternate_label]'; ?>" value="<?php echo $escapeAttr($propertyRow['o:alternate_label']); ?>">
    <input class="original-comment" type="hidden" name="<?php echo $namePrefix . '[o:original_comment]'; ?>" value="<?php echo $escapeAttr($translate($property->comment())); ?>">
    <input class="alternate-comment" type="hidden" name="<?php echo $namePrefix . '[o:alternate_comment]'; ?>" value="<?php echo $escapeAttr($propertyRow['o:alternate_comment']); ?>">
    <input class="is-required" type="hidden" name="<?php echo $namePrefix . '[o:is_required]'; ?>" value="<?php echo $escapeAttr($propertyRow['o:is_required']); ?>">
    <input class="is-private" type="hidden" name="<?php echo $namePrefix . '[o:is_private]'; ?>" value="<?php echo $escapeAttr($propertyRow['o:is_private']); ?>">
    <input class="data-type" type="hidden" name="<?php echo $namePrefix . '[o:data_type]'; ?>" value="<?php echo is_array($propertyRow['o:data_type']) ? $escapeAttr(implode(',', $propertyRow['o:data_type'])) : $escapeAttr($propertyRow['o:data_type']); ?>">
    <input class="default-value" type="hidden" name="<?php echo $namePrefix . '[o:settings][default_value]'; ?>" value="<?php echo array_key_exists('default_value', $propertyRow['o:settings']) ? $escapeAttr($propertyRow['o:settings']['default_value']) : ''; ?>">
    <input class="allowed-languages" type="hidden" name="<?php echo $namePrefix . '[o:settings][allowed_languages]'; ?>" value="<?php echo array_key_exists('allowed_languages', $propertyRow['o:settings']) && is_array($propertyRow['o:settings']['allowed_languages']) ? $escapeAttr(implode("\n", $propertyRow['o:settings']['allowed_languages'])) : ''; ?>">

    <span class="sortable-handle"></span>
    <span class="original-label-cell"><?php echo $escape($translate($property->label())); ?></span>
    <span class="alternate-label-cell"><?php echo $escape($propertyRow['o:alternate_label']); ?></span>

    <ul class="actions">
        <li><?php echo $this->hyperlink('', '#', [
            'class' => 'o-icon-more sidebar-content',
            'title' => $translate('Details'),
            'data-sidebar-content-url' => $property->url('show-details'),
            'data-sidebar-selector' => '#details',
        ]); ?></li>
        <li><?php echo $this->hyperlink('', '#', [
            'class' => 'o-icon-edit property-edit',
            'title' => $translate('Edit property'),
        ]); ?></li>
        <li><?php echo $this->hyperlink('', '#', [
            'class' => 'o-icon-delete property-remove',
            'title' => $translate('Remove property'),
        ]); ?></li>
        <li><?php echo $this->hyperlink('', '#', [
            'class' => 'o-icon-undo property-restore',
            'title' => $translate('Restore value'),
            'style' => 'display: none',
        ]); ?></li>
    </ul>
</li>
