<?php
$property = $propertyRow['o:property'];
$namePrefix = 'o:resource_template_property[' . $property->id() . ']';
$escape = $this->plugin('escapeHtml');
$propertyId = $escape($property->id());
?>
<li class="property row" data-property-id="<?php echo $propertyId; ?>">

    <input class="property-id" type="hidden" name="<?php echo $escape($namePrefix . '[o:property][o:id]'); ?>" value="<?php echo $escape($property->id()); ?>">
    <input class="original-label" type="hidden" name="<?php echo $escape($namePrefix . '[o:original_label]'); ?>" value="<?php echo $this->translate($property->label()); ?>">
    <input class="alternate-label" type="hidden" name="<?php echo $escape($namePrefix . '[o:alternate_label]'); ?>" value="<?php echo $escape($propertyRow['o:alternate_label']); ?>">
    <input class="original-comment" type="hidden" name="<?php echo $escape($namePrefix . '[o:original_comment]'); ?>" value="<?php echo $this->translate($property->comment()); ?>">
    <input class="alternate-comment" type="hidden" name="<?php echo $escape($namePrefix . '[o:alternate_comment]'); ?>" value="<?php echo $escape($propertyRow['o:alternate_comment']); ?>">
    <input class="is-required" type="hidden" name="<?php echo $escape($namePrefix . '[o:is_required]'); ?>" value="<?php echo $escape($propertyRow['o:is_required']); ?>">
    <input class="data-type" type="hidden" name="<?php echo $escape($namePrefix . '[o:data_type]'); ?>" value="<?php echo $escape($propertyRow['o:data_type']); ?>">

    <span class="sortable-handle"></span>
    <?php echo $escape($this->translate($property->label())); ?>

    <ul class="actions">
        <li><a href="#" class="o-icon-more sidebar-content" aria-label="<?php echo $escape($this->translate('Details')); ?>" title="<?php echo $escape($this->translate('Details')); ?>" data-sidebar-content-url="<?php echo $escape($property->url('show-details')); ?>" data-sidebar-selector="#details"></a></li>
        <li><a href="#" class="o-icon-edit property-edit" aria-label="<?php echo $escape($this->translate('Edit property')); ?>" title="<?php echo $escape($this->translate('Edit property')); ?>"></a></li>
        <li><a href="#" class="o-icon-delete property-remove" aria-label="<?php echo $escape($this->translate('Remove property')); ?>" title="<?php echo $escape($this->translate('Remove property')); ?>"></a></li>
        <li><a href="#" class="o-icon-undo property-restore" aria-label="<?php echo $escape($this->translate('Restore value')); ?>" title="<?php echo $escape($this->translate('Restore value')); ?>" style="display: none;"></a></li>
    </ul>
</li>
