<?php
$translate = $this->plugin('translate');
$assetUrl = $this->plugin('assetUrl');

$this->headMeta()
    ->setCharset('utf-8')
    ->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()
    ->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic')
    ->appendStylesheet($assetUrl('css/iconfonts.css', 'Omeka'))
    ->appendStylesheet($assetUrl('css/style.css', 'Omeka'));
$this->headScript()
    ->prependFile($assetUrl('vendor/jquery/jquery.min.js', 'Omeka'))
    ->appendFile($assetUrl('js/global.js', 'Omeka'), 'text/javascript', ['defer' => 'defer']);

$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <?php echo $this->htmlElement('body')->appendAttribute('class', 'minimal'); ?>
        <?php echo $userBar; ?>
        <div id="content" role="main">
            <?php echo $this->messages(); ?>
            <?php echo $this->content; ?>
        </div>
        <footer>
            <span class="powered-by"><?php echo $translate('Powered by Omeka S'); ?></span>
        </footer>
    </body>
</html>
