<?php
$this->htmlElement('body')->appendAttribute('class', 'add item-set');
?>

<?php echo $this->pageTitle($this->translate('Add Item Set')); ?>

<?php
echo $this->partial('omeka/admin/item-set/form.phtml', [
    'form' => $form,
    'itemSet' => null,
    'formAfterEvent' => 'view.add.form.after',
    'sectionNavEvent' => 'view.add.section_nav',
]);
?>

<?php $this->trigger('view.add.after'); ?>
