<?php
$this->htmlElement('body')->appendAttribute('class', 'edit item-set section-sidebar-open');
$escape = $this->plugin('escapeHtml');
$deleteButton = '<a href="#" class="delete button">' . $escape('Delete') . '</a>';
?>

<script type='text/javascript'>
var valuesJson = <?php echo json_encode($itemSet->values()); ?>;
</script>

<?php echo $this->pageTitle(sprintf($this->translate('Edit Item Set: “%s”'), $itemSet->displayTitle())); ?>

<?php
echo $this->partial('omeka/admin/item-set/form.phtml', [
    'form' => $form,
    'itemSet' => $itemSet,
    'submitLabel' => $this->translate('Save'),
    'deleteButton' => $deleteButton,
    'formAfterEvent' => 'view.edit.form.after',
    'sectionNavEvent' => 'view.edit.section_nav',
]);
?>

<?php echo $this->deleteConfirm($itemSet, 'item set'); ?>

<?php $this->trigger('view.edit.after'); ?>
