<?php
$this->htmlElement('body')->appendAttribute('class', 'edit item-set sidebar-open');
$escape = $this->plugin('escapeHtml');
$deleteButton = '<a href="#" class="delete button sidebar-confirm" 
    data-sidebar-confirm-url="' . $escape($itemSet->url('delete')) . 
    '">' . $escape('Delete') . '</a>';
?>

<script type='text/javascript'>
var valuesJson = <?php echo json_encode($itemSet->values()); ?>;
</script>

<?php echo $this->pageTitle(sprintf($this->translate('Edit Item Set: “%s”'), $itemSet->displayTitle())); ?>

<?php
echo $this->partial('omeka/admin/item-set/form.phtml', array(
    'form' => $form,
    'itemSet' => $itemSet,
    'submitLabel' => $this->translate('Save'),
    'deleteButton' => $deleteButton
));
?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $this->translate('Delete Item Set'); ?></h2>
        <p><?php echo $this->translate('Are you sure you would like to delete this item set?'); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
</div>

<?php $this->trigger('view.edit.after'); ?>
