<?php
$this->headMeta()->setCharset('utf-8');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', 'en'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <?php echo $this->htmlElement('body'); ?>

        <div role="main">
            <?php echo $this->messages(); ?>
            <?php echo $this->content; ?>
        </div>

    </body>
</html>
