<p><?php echo $this->translate('This is the API root for this Omeka S installation. Below is a list of available API resources and links to their endpoints. Some resources and features require authentication. See the <a href="https://omeka.org/s/docs/developer/api/rest_api/" target="_blank">Omeka S REST API documentation</a> for more information.'); ?></p>
<ul>
    <?php foreach ($apiResources as $apiResource): ?>
    <li><?php echo $this->hyperlink(
        $apiResource->id(),
        $this->url('api/default', ['resource' => $apiResource->id()], ['force_canonical' => true, 'query' => ['pretty_print' => true]], true)
    ); ?></li>
    <?php endforeach; ?>
</ul>
