<h1>Omeka S REST API</h1>
<p><?php echo $this->translate('This is the REST API root endpoint for this Omeka S installation. Below is a list of available API resources and links to their endpoints. Some resources and features require authentication.'); ?></p>
<ul>
    <?php foreach ($apiResources as $apiResource): ?>
    <li><?php echo $this->hyperlink(
        $apiResource->id(),
        $this->url('api/default', ['resource' => $apiResource->id()], ['force_canonical' => true, 'query' => ['pretty_print' => true]], true)
    ); ?></li>
    <?php endforeach; ?>
</ul>
<p><?php echo $this->hyperlink(
    $this->translate('Omeka S REST API documentation'),
    'https://omeka.org/s/docs/developer/api/rest_api/',
    ['target' => '_blank']
); ?></p>
