<?php
$this->htmlElement('body')->appendAttribute('class', 'site-pages add');
$form->prepare();
?>
<?php echo $this->pageTitle($this->translate('Add Page')); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Add'); ?></button>
</div>
<?php
foreach ($form as $element) {
    echo $this->formRow($element);
}
?>
<?php echo $this->form()->closeTag(); ?>
