<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'sites add');
$this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/site-item-pool.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/site-theme.js', 'Omeka'));
$form->prepare();
$sectionNavs = [
    'admin' => $this->translate('Admin'),
    'theme' => $this->translate('Theme'),
    'item-pool' => $this->translate('Item Pool')
];
?>
<?php echo $this->pageTitle('Add Site'); ?>
<?php $this->trigger('view.add.before'); ?>
<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <a href="#" class="o-icon-private button" aria-label=" <?php echo $this->translate('Make public'); ?>" title=" <?php echo $this->translate('Make public'); ?>"></a>
    <input type="hidden" name="o:is_public" value="0">
    <button><?php echo $this->translate('Add'); ?></button>
</div>

<?php echo $this->sectionNav($sectionNavs, 'view.add.section_nav'); ?>
<?php $this->trigger('view.add.form.before', ['form' => $form]); ?>
<fieldset id="admin" class="section active" aria-labelledby="admin-label">
    <?php echo $this->formCollection($form, false); ?>
</fieldset>

<fieldset id="theme" class="section" aria-labelledby="theme-label">
    <div class="selectable-themes">
        <?php foreach ($themes as $theme): ?>
        <?php $themeName = $theme->getName(); ?>
        <div class="theme <?php echo ($themeName == 'Default') ? 'active' : ''; ?>">
            <?php $localThumbnailUrl = OMEKA_PATH . $theme->getThumbnail(); ?>
            <?php $absoluteThumbnailUrl = $this->basePath() . $theme->getThumbnail(); ?>
            <?php $fallbackThumbnailUrl = $this->assetUrl('img/theme.jpg', 'Omeka'); ?>
            <div class="theme-thumbnail">
            <img src="<?php echo (file_exists($localThumbnailUrl)) ? $absoluteThumbnailUrl : $fallbackThumbnailUrl; ?>">
            </div>
            <h4><?php echo $themeName; ?></h4>
            <div class="theme-meta">
                <span class="theme-author">
                    <?php $themeAuthor = $theme->getIni('author'); ?>
                    <?php $themeAuthorLink = $theme->getIni('author_link'); ?>

                    <?php if (isset($themeAuthorLink)): ?>
                    <a href="<?php echo $escape($themeAuthorLink); ?>" target="_blank"><?php echo $escape($themeAuthor); ?></a>
                    <?php else: ?>
                    <?php echo $themeAuthor; ?>
                    <?php endif; ?>
                </span>
                <?php $themeDescription = ''; ?>
                <?php if (($themeDescription = $theme->getIni('description')) && ($themeDescription !== '')): ?>
                <span class="theme-description"><?php echo $escape($themeDescription); ?></span>
                <?php endif; ?>
            </div>
            <input type="hidden" name="o:theme" value="<?php echo $theme->getId(); ?>" <?php echo ($themeName == 'Default') ? '' : 'disabled'; ?>>
        </div>
        <?php endforeach; ?>
    </div>

</fieldset>

<fieldset id="item-pool" class="section" aria-labelledby="item-pool-label">
    <div id="advanced-search"><?php echo $this->partial('common/advanced-search', ['resourceType' => 'item']); ?></div>
</fieldset>
<?php $this->trigger('view.add.form.after', ['form' => $form]); ?>
<?php echo $this->form()->closeTag(); ?>
<?php $this->trigger('view.add.after'); ?>
