<?php
$this->htmlElement('body')->appendAttribute('class', 'sites add');
$escape = $this->plugin('escapeHtml');
$form->prepare();
?>
<?php echo $this->pageTitle(sprintf($this->translate('Edit Info for Site: “%s”'), $site->title())); ?>
<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <?php if ($site->isPublic()): ?>
    <a href="#" class="o-icon-public button" aria-label=" <?php echo $this->translate('Make private'); ?>" title=" <?php echo $this->translate('Make private'); ?>"></a>
    <input type="hidden" name="o:is_public" value="1">
    <?php else: ?>
    <a href="#" class="o-icon-private button" aria-label=" <?php echo $this->translate('Make public'); ?>" title=" <?php echo $this->translate('Make public'); ?>"></a>
    <input type="hidden" name="o:is_public" value="0">
    <?php endif; ?>
    <a href="<?php echo $site->siteUrl(); ?>" class="button"><?php echo $this->translate('View'); ?></a>
    <a href="#" class="delete button sidebar-confirm" data-sidebar-confirm-url="<?php echo $escape($site->url('delete')); ?>"><?php echo $this->translate('Delete'); ?></a>
    <button><?php echo $this->translate('Save'); ?></button>
</div>

<?php echo $this->formCollection($form, false); ?>

<?php echo $this->form()->closeTag(); ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $this->translate('Delete Site'); ?></h2>
        <p><?php echo $this->translate('Are you sure you would like to delete this site?'); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>
