<?php
$this->htmlElement('body')->appendAttribute('class', 'sites browse');
$confirmForm->prepare();
$escape = $this->plugin('escapeHtml');
$sortHeadings = [
    [
        'label' => $this->translate('Title'),
        'value' => 'title'
    ],
    [
        'label' => $this->translate('Owner'),
        'value' => 'owner_name'
    ]
];
?>

<?php echo $this->pageTitle($this->translate('Sites')); ?>

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Add new site'), $this->url('admin/site/add'), array('class' => 'button')); ?>
</div>

<?php if (count($sites) > 0): ?>

<?php echo $this->pagination(); ?>

<?php echo $this->sortSelector($sortHeadings); ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($sites as $site): ?>
        <?php
        if ($owner = $site->owner()) {
            $ownerText = $this->hyperlink(
                $owner->name(),
                $this->url('admin/id', array(
                    'controller' => 'user',
                    'action' => 'show',
                    'id' => $owner->id())
                )
            );
        } else {
            $ownerText = $this->translate('[no owner]');
        }
        ?>
        <tr>
            <td>
                <span class="resource-name">
                    <?php echo $site->link($site->title(), 'show'); ?>
                </span>
                <ul class="actions">
                    <li>
                    <?php if ($site->userIsAllowed('update')): ?>
                        <?php echo $site->link('', null, array(
                            'class' => 'o-icon-edit',
                            'aria-label' => $this->translate('Edit'),
                            'title' => $this->translate('Edit'),
                        )); ?>
                    <?php endif; ?>
                    </li>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($site->url('show-details')); ?>"
                        data-sidebar-confirm-url="<?php echo $escape($site->url('delete')); ?>"
                        class="o-icon-delete sidebar-confirm"
                        aria-label="<?php echo $escape($this->translate('Delete')); ?>"
                        title="<?php echo $escape($this->translate('Delete')); ?>"></a></li>
                </ul>
            </td>
            <td><?php echo $ownerText; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->pagination(); ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $this->translate('Delete Site'); ?></h2>
        <p><?php echo $this->translate('Are you sure you would like to delete this site?'); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any sites.'); ?></p>
</div>

<?php endif; ?>
