<?php
$this->htmlElement('body')->appendAttribute('class', 'sites item-pool');
$form->prepare();
$this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/site-item-pool.js', 'Omeka'));
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Item Pool')); ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formCollection($form, false); ?>

<div id="page-actions">
    <button><?php echo $this->translate('Save'); ?></button>
</div>

<p>
    <?php
    echo sprintf(
        $this->translate('There are currently %s items in this site’s pool.'),
        $this->hyperlink($itemCount,
            $this->url('admin/default', ['controller' => 'item'], ['query' => ['site_id' => $site->id()]])
        )
    );
    ?>
</p>

<div id="advanced-search"><?php echo $this->partial(
    'common/advanced-search',
    ['query' => $site->itemPool(), 'resourceType' => 'item']
); ?></div>

<?php echo $this->form()->closeTag(); ?>
