<?php
$this->htmlElement('body')->appendAttribute('class', 'sites item-pool');
$this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Item Pool')); ?>

<form method="POST" id="site-form">

<div id="page-actions">
    <button><?php echo $this->translate('Save'); ?></button>
</div>

<div id="advanced-search"><?php echo $this->partial('common/advanced-search', ['resourceType' => 'item', 'query' => $site->itemPool()]); ?></div>

</form>