<?php
$this->htmlElement('body')->appendAttribute('class', 'sites users sidebar-open');
$form->prepare();
$escape = $this->plugin('escapeHtml');
$delete = $this->translate('Delete');
$restore = $this->translate('Restore');
$roles = [
    'viewer' => $this->translate('Viewer'),
    'editor' => $this->translate('Editor'),
    'admin' => $this->translate('Admin'),
];
?>

<?php echo $this->pageTitle($this->translate('User Permissions')); ?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <button><?php echo $this->translate('Save'); ?></button>
</div>

<?php $sitePermissions = $site->sitePermissions(); ?>
    <table id="site-user-permissions" class="tablesaw tablesaw-stack <?php echo count($sitePermissions) ? '' : 'empty'; ?>" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th scope="col"><?php echo $this->translate('User'); ?></th>
                <th scope="col"><?php echo $this->translate('Role'); ?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $index = 0;
            foreach($sitePermissions as $sitePermission):
            $user = $sitePermission->user();
            ?>
            <tr class="user value">
                <td class="user-meta">
                    <span class="restore-value"><?php echo $this->translate('User to be removed'); ?></span>
                    <span class="user-name"><?php echo $escape($user->name()); ?> (<?php echo $escape($user->email()); ?>)</span>
                    <input type="hidden" class="user-id" name="o:site_permission[<?php echo $index; ?>][o:user][o:id]" value="<?php echo $escape($user->id()); ?>">
                </td>
                <td><select name="o:site_permission[<?php echo $index; ?>][o:role]">
                    <?php
                    foreach ($roles as $key => $value):
                    $selected = $key === $sitePermission->role() ? true : false;
                    ?>
                    <option value="<?php echo $key; ?>"<?php echo $selected ? ' selected' : null; ?>><?php echo $value; ?></option>
                    <?php endforeach; ?>
                </select></td>
                <td>
                    <ul class="actions">
                        <li><a href="#" class="o-icon-delete" aria-label="<?php echo $delete; ?>" title="<?php echo $delete; ?>"></a></li>
                        <li><a href="#" class="o-icon-undo" aria-label="<?php echo $restore; ?>" title="<?php echo $restore; ?>"></a></li>
                    </ul>
                </td>
                <?php $index++; ?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="no-resources">
        <p><?php echo $this->translate('This site has no users. Add users using the interface to the right.'); ?></p>
    </div>
    <div id="site-user-selector" class="selector sidebar active">
        <legend><?php echo $this->translate('Click on a user to add them to the site.'); ?></legend>
        <input type="text" class="selector-filter" placeholder="Filter users">
        <ul id="new-site-user">
            <li class="show"><?php echo $this->translate('All Users'); ?> (<?php echo count($users); ?>)
                <ul>
                <?php
                $usersByInitial = [];
                $initial = substr($users[0]->name(), 0, 1);
                foreach ($users as $user) {
                    $userInitial = substr($user->name(), 0, 1);
                    if ($userInitial !== $initial) {
                        $initial = $userInitial;
                    }
                    $usersByInitial[$initial][] = $user;
                }
                ?>
                <?php foreach ($usersByInitial as $initial => $users): ?>
                    <li class="selector-parent"><span>
                        <?php echo $initial; ?></span>
                        (<span class="selector-child-count"><?php echo count($usersByInitial[$initial]); ?></span>)
                        <ul>
                        <?php foreach($users as $user): ?>
                            <li class="selector-child" data-child-search="<?php echo $escape($user->name() . ' (' . $user->email() . ')'); ?>" data-user-id="<?php echo $escape($user->id()); ?>"><span><?php echo $escape($user->name()); ?><br><?php echo $escape($user->email()); ?></span></li>
                        <?php endforeach; ?>
                        </ul>
                <?php endforeach; ?>
                </ul>
            </li>
        </ul>
    </div>

<?php echo $this->formElement($form->get('csrf')); ?>
<?php echo $this->form()->closeTag(); ?>

<?php
$userRowTemplate = '
<tr class="user value">
    <td class="user-meta">
        <span class="restore-value">' . $this->translate('User to be removed') . '</span>
        <span class="user-name"></span>
        <input type="hidden" class="user-id" name="o:site_permission[__index__][o:user][o:id]">
    </td>
    <td><select name="o:site_permission[__index__][o:role]">';
foreach ($roles as $key => $value) {
    $userRowTemplate .= '<option value="' . $key . '">' . $value . '</option>';
}
$userRowTemplate .= '</select></td>
    <td>
        <ul class="actions">
            <li><a href="#" class="o-icon-delete" aria-label="' . $delete . '" title="' . $delete . '"></a></li>
            <li><a href="#" class="o-icon-undo" aria-label="' . $restore . '" title="' . $restore . '"></a></li>
        </ul>
    </td>
</tr>
';
?>

<span id="user-row-template" data-template="<?php echo $escape($userRowTemplate); ?>"></span>

<script>
$('#content').on('click', '.o-icon-delete,.o-icon-undo', function(e) {
    e.preventDefault();
    $(this).parents('tr').toggleClass('delete');
});

$('#content').on('click', '.o-icon-delete', function() {
    $(this).parents('tr').find('input[type="hidden"]').prop('disabled', true);
});

$('#content').on('click', '.o-icon-undo', function() {
    $(this).parents('.user.value').find('input[type="hidden"]').prop('disabled', false);
});

$('.selector .selector-child').click(function() {
    var user = $(this);
    var userId = user.data('user-id');
    var userText = user.data('child-search');
    var permissionsTable = $('#site-user-permissions');
    if (permissionsTable.find('.user-id[value="' + userId + '"]').length) {
        // Do not add existing users.
        return;
    }
    var index = permissionsTable.find('.user').length;
    if (!index) {
        permissionsTable.removeClass('empty');
    }
    var template = $($.parseHTML($('#user-row-template').data('template')));
    template.find('.user-name').text(userText);
    template.find('.user-id').val(userId);
    template.find(':input').each(function() {
        // Find and replace indexes for all inputs.
        var thisInput = $(this);
        var name = thisInput.attr('name').replace('[__index__]', '[' + index + ']');
        thisInput.attr('name', name);
    });
    permissionsTable.find('tbody').append(template);
});

</script>
