<?php
$escape = $this->plugin('escapeHtml');
?>
<header>
    <div class="logo"><a href="<?php echo $this->url('admin'); ?>"><?php echo $this->setting('installation_title', 'Omeka S'); ?></a></div>
    <div id="mobile-nav">
        <a href="#" class="o-icon-menu button"><span class="screen-reader-text"><?php echo $this->translate('Navigation Menu'); ?></span></a>
        <a href="#" class="o-icon-search button"><span class="screen-reader-text"><?php echo $this->translate('Search Site'); ?></span></a>
        <a href="#" class="o-icon-user button"><span class="screen-reader-text"><?php echo $this->translate('User Menu'); ?></span></a>
    </div>
    <div id="user">
        <?php if ($this->identity()): ?>
        <p><?php echo sprintf($this->translate('Welcome, %s'),  '<a href="' . $this->url('admin/id', array(
            'controller' => 'user',
            'id' => $this->identity()->getId(),
        )) . '">' . $escape($this->identity()->getName()) . '</a>'); ?></p>
        <p><a href="<?php echo $this->url('logout'); ?>"><?php echo $this->translate('Logout'); ?></a></p>
        <?php else: ?>
        <p><?php echo $this->translate('not logged in'); ?></p>
        <?php endif; ?>
    </div>
    <div id="search">
        <form action="" id="search-form">
            <?php $searchValue = isset($_GET['value']['in'][0]) ? $_GET['value']['in'][0] : ''; ?>
            <input type="text" name="value[in][]" value="<?php echo $escape($searchValue); ?>">
            <button type="button" id="advanced"><?php echo $this->translate('Advanced Options'); ?></button>
            <button type="submit"><?php echo $this->translate('Search'); ?></button>
            <fieldset id="advanced-options">
                <legend><?php echo $this->translate('Resource Type'); ?></legend>
                <input type="radio" name="resource-type" id="search-items" value="item" data-action="<?php echo $escape($this->url('admin/default', array('controller' => 'item', 'action' => 'browse'))); ?>" checked="checked"><label for="search-items"><?php echo $this->translate('Items'); ?></label>
                <input type="radio" name="resource-type" id="search-item-sets" value="item-set" data-action="<?php echo $escape($this->url('admin/default', array('controller' => 'item-set', 'action' => 'browse'))); ?>"><label for="search-item-sets"><?php echo $this->translate('Item Sets'); ?></label>
                <input type="radio" name="resource-type" id="search-media" value="media" data-action="<?php echo $escape($this->url('admin/default', array('controller' => 'media', 'action' => 'browse'))); ?>"><label for="search-media"><?php echo $this->translate('Media'); ?></label>
            </fieldset>
        </form>
    </div>
    <nav id="menu" role="navigation">
    <?php if (isset($site)): ?>
        <h4>
            <?php echo $site->link($site->title(), 'show'); ?>
        </h4>
        <a href="<?php echo $site->siteUrl(); ?>" class="o-icon-external public" aria-label="<?php echo $this->translate('View public site'); ?>" title="<?php echo $this->translate('View public site'); ?>"></a>
        <?php echo $this->navigation('Zend\Navigation\Site')->menu(); ?>
    <?php endif; ?>
        <?php $globalNav = $this->navigation('Zend\Navigation\Admin')->menu(); ?>
        <?php if (isset($site)): ?>
            <h4><?php echo $this->translate('Global navigation'); ?></h4>
            <a href="#" class="expand" aria-label="<?php echo $this->translate('Expand'); ?>" title="<?php echo $this->translate('Expand'); ?>"></a>
            <div class="collapsible"><?php echo $globalNav; ?></div>
        <?php else: ?>
            <?php echo $globalNav; ?>
        <?php endif; ?>
    </nav>
</header>

<script>
    $('#advanced').click(function(event) {
        event.preventDefault();
        $('#advanced-options').slideToggle('slow');
    });
</script>
