<?php
$this->htmlElement('html')->setAttribute('lang', 'en');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('css/tablesaw.bare.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/tablesaw.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/jquery.js', 'Omeka'));
$this->jsTranslate();
$this->trigger('view.layout');
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <?php echo $this->htmlElement('body'); ?>
        <div class="flex">
            <?php echo $this->partial('layout/header'); ?>
            <div id="content" role="main">
                <?php echo $this->messages(); ?>
                <?php echo $this->content; ?>
            </div>
        </div>
        <?php echo $this->partial('layout/footer'); ?>
    </body>
</html>
