<?php if ($resource->subjectValueTotalCount()): ?>
    <?php echo $resource->displaySubjectValues([
        'page' => $this->params()->fromQuery('page', 1),
        'perPage' => 25,
        'resourceProperty' => $this->params()->fromQuery('resource_property'),
    ]); ?>
<?php else: ?>
    <div class="no-resources">
        <p><?php echo $translate('No resources link to this resource.'); ?></p>
    </div>
<?php endif; ?>
