<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$label = isset($data['label']) && '' !== trim($data['label']) ? $data['label'] : null;
$query = isset($data['query']) && '' !== trim($data['query']) ? $data['query'] : null;

$queryElement = (new Omeka\Form\Element\Query('query'))
    ->setLabel($this->translate('Query'))
    ->setAttribute('data-name', 'query')
    ->setValue($query)
    ->setResourceType(('Omeka\Site\Navigation\Link\Browse' === get_class($link)) ? 'items' : 'item_sets')
    ->setPartialExcludelist(['common/advanced-search/site']);
?>
<label><?php echo $translate('Type'); ?> <input type="text" value="<?php echo $escape($translate($link->getName())); ?>" disabled></label>
<label><?php echo $translate('Label'); ?> <input type="text" data-name="label" value="<?php echo $escape($label); ?>"></label>
<label><?php echo $translate('Query'); ?><?php echo $this->formElement($queryElement); ?></label>
