<?php
$escape = $this->plugin('escapeHtml');
$label = isset($data['label']) && '' !== trim($data['label']) ? $data['label'] : null;
$query = isset($data['query']) && '' !== trim($data['query']) ? $data['query'] : null;
?>
<label><?php echo $this->translate('Type'); ?> <input type="text" value="<?php echo $escape($this->translate($link->getName())); ?>" disabled></label>
<label><?php echo $this->translate('Label'); ?> <input type="text" data-name="label" value="<?php echo $escape($label); ?>"></label>
<label><?php echo $this->translate('Query'); ?> <input type="text" data-name="query" value="<?php echo $escape($query); ?>"></label>
