<?php
$escape = $this->plugin('escapeHtml');
$label = isset($data['label']) && '' !== trim($data['label']) ? $data['label'] : null;
$siteSlug = isset($data['site-slug']) && '' !== trim($data['site-slug']) ? $data['site-slug'] : null;
?>
<label><?php echo $this->translate('Type'); ?> <input type="text" value="<?php echo $escape($this->translate($link->getName())); ?>" disabled></label>
<label class="required"><?php echo $this->translate('Label'); ?> <input type="text" data-name="label" value="<?php echo $escape($label); ?>"></label>
<label class="required"><?php echo $this->translate('Site slug'); ?> <input type="text" data-name="site-slug" value="<?php echo $escape($siteSlug); ?>" required></label>