<?php
$escape = $this->plugin('escapeHtml');
$label = isset($data['label']) && '' !== trim($data['label']) ? $data['label'] : null;
$targetSiteId = isset($data['target-site-id']) && '' !== trim($data['target-site-id']) ? $data['target-site-id'] : null;
?>
<label><?php echo $this->translate('Type'); ?> <input type="text" value="<?php echo $escape($this->translate($link->getName())); ?>" disabled></label>
<label class="required"><?php echo $this->translate('Label'); ?> <input type="text" data-name="label" value="<?php echo $escape($label); ?>"></label>
<label class="required"><?php echo $this->translate('Target site'); ?>
<?php
echo $this->siteSelect([
    'name' => 'target-site-id',
    'attributes' => [
        'data-name' => 'target-site-id',
        'value' => $escape($targetSiteId) ?? null,
    ]
]);
?>
</label>
