<?php
$this->htmlElement('body')->appendAttribute('class', 'add item');
$this->headScript()->appendFile($this->assetUrl('js/item-form.js', 'Omeka'));
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
$formErrors = $this->plugin('formElementErrors');

?>
<h1><?php echo $this->translate('Add Item'); ?></h1>
<?php 
if (isset($errors)) {
    print_r($errors);
}
?>

<nav class="section-nav">
    <ul>
        <li><a href="#" class="resource-values section active">Values</a></li>
        <li><a href="#" class="item-media section">Media</a></li>
        <li><a href="#" class="item-visibility section">Visibility</a></li>
    </ul>
</nav>

<form method='post' id='add-item'>
    <fieldset id='resource-values' class='section active'>
        <?php foreach ($form->getElements() as $name => $element): ?>
        <?php if ($element->getLabel()): ?>
        <div class="resource-values field" data-property-qname='<?php echo $element->getAttribute('data-property-qname'); ?>' data-property-id='<?php echo $element->getAttribute('data-property-id'); ?>'>
            <?php if ($name != 'o:resource_class[o:id]'): ?>
            <div class="field-actions">
                <a href="#" class="add-value button o-icon-add"><span class="screen-reader-text">Add Value</span></a>
            </div>
            <?php endif; ?>
            <div class='field-meta'>
            <?php echo $formLabel($element); ?>
                <div class='field-description'>
                    <p class="o-icon-info"><span class="screen-reader-text">More Info</span></p>
                </div>
            </div>

            <div class='inputs'>
                <div class='value'>
                    <?php if ($name != 'o:resource_class[o:id]'): ?>
                    <div class="input-options">
                            <a link="#" class="tab active o-icon-text"><span class="screen-reader-text">Text</span></a>
                            <a link="#" class="tab o-icon-items"><span class="screen-reader-text">Omeka Item</span></a>
                            <a link="#" class="tab o-icon-link"><span class="screen-reader-text">External Resource</span></a>
                     </div>
                     <?php endif; ?>
                     <div class="active type input-option text">
                     <?php echo $formElement($element); ?>
                     <?php if ($name != 'o:resource_class[o:id]'): ?>
                     <select class="value-language">
                     <option value="en">English</option>
                     </select>
                     <?php endif; ?>
                     </div>
                     <button class="remove-value">Remove value</button>
                </div>
            </div>

            <?php
            echo $formErrors($element);
            ?>
        </div>
        <?php else: ?>
        <!-- Display the hidden input for the property id -->
        <?php echo $formElement($element); ?>
        <?php endif; ?>
        <?php endforeach; ?>
        
        <div class='new resource-values field template'>
            <div class="field-actions">
                <a href="#" class="remove button o-icon-times"><span class="screen-reader-text">Remove</span></a>
                <a href="#" class="add-value button o-icon-add"><span class="screen-reader-text">Add Value</span></a>
            </div>
            <div class='field-meta'>
                <input type="text" title="new-property-name" placeholder="Property name">
                <div class='properties'>
                    <ul>
                        <li class='all-vocabs'>
                            Vocabularies (<span class='count'><?php echo count($vocabularies); ?></span>)
                            <ul>
                                <?php foreach ($vocabularies as $label => $vocabulary) : ?>
                                <li class='vocabulary'>
                                    <?php echo $label; ?>
                                    <ul>
                                        <?php foreach ($vocabulary as $propertyInfo) : ?>
                                        <li class='property' data-property-id='<?php echo $propertyInfo["id"]; ?>' data-property-qname='<?php echo $propertyInfo["qname"]; ?>'>
                                            <?php echo $propertyInfo['label']; ?>
                                            <div class='description'>
                                                <p class='o-icon-info'>
                                                    <span class='screen-reader-text'>More Info</span>
                                                </p>
                                                <p>
                                                <?php echo $propertyInfo['comment']; ?>
                                                </p>
                                            </div>
                                            <button class='set-property'>Set Property</button>
                                        </li>
                                        <?php endforeach; ?>
                                    </ul>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="inputs">
                <div class="value">
                    <div class="input-options">
                        <a link="#" class="tab active o-icon-text"><span class="screen-reader-text">Text</span></a>
                        <a link="#" class="tab o-icon-items"><span class="screen-reader-text">Omeka Item</span></a>
                        <a link="#" class="tab o-icon-link"><span class="screen-reader-text">External Resource</span></a>
                     </div>
                     <div class="active type input-option text">
                        <!-- input for the property value -->
                        <textarea name="" class="input-value"></textarea>
                        <input type='hidden' class="input-id" name="" value="" />
                         <select class="value-language">
                             <option value="en">English</option>
                         </select>
                     </div>
                </div>
            </div>
        </div>
        <a href="#" class="add-property button">Add property</a>
    </fieldset>

    <fieldset id="save-sidebar">
        <input type="submit" name="add-item-submit" value="Create Item" />
        <a href="#" class="cancel button">Cancel</a>
    </fieldset>
</form>

