<?php
$this->htmlElement('body')->appendAttribute('class', 'add item');
$this->headScript()->appendFile($this->assetUrl('js/item-form.js', 'Omeka'));
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
$formErrors = $this->plugin('formElementErrors');

?>
<h1><?php echo $this->translate('Add Item'); ?></h1>
<?php 
if (isset($errors)) {
    print_r($errors);
}
?>

<nav class="section-nav">
    <ul>
        <li><a href="#" class="resource-values section active">Values</a></li>
        <li><a href="#" class="item-media section">Media</a></li>
        <li><a href="#" class="item-visibility section">Visibility</a></li>
    </ul>
</nav>

<form method='post' id='add-item'>
    <fieldset id='resource-values' class='section active'>
        <?php foreach ($form->getElements() as $name => $element): ?>
        <?php if ($element->getLabel()): ?>
        <div class="resource-values field" data-property-qname='<?php echo $element->getAttribute('data-property-qname'); ?>' data-property-id='<?php echo $element->getAttribute('data-property-id'); ?>'>
            <?php if ($name != 'o:resource_class[o:id]'): ?>
            <div class="field-actions">
                <a href="#" class="add-value button o-icon-add"><span class="screen-reader-text">Add Value</span></a>
            </div>
            <?php endif; ?>
            <div class='field-meta'>
            <?php echo $formLabel($element); ?>
                <div class='field-description'>
                    <p class="o-icon-info"><span class="screen-reader-text">More Info</span></p>
                </div>
            </div>

            <div class='inputs'>
                <div class='value'>
                    <?php if ($name != 'o:resource_class[o:id]'): ?>
                    <div class="input-options">
                            <a link="#" class="tab active o-icon-text"><span class="screen-reader-text">Text</span></a>
                            <a link="#" class="tab o-icon-items"><span class="screen-reader-text">Omeka Item</span></a>
                            <a link="#" class="tab o-icon-link"><span class="screen-reader-text">External Resource</span></a>
                     </div>
                     <?php endif; ?>
                     <div class="active type input-option text">
                     <?php echo $formElement($element); ?>
                     <?php if ($name != 'o:resource_class[o:id]'): ?>
                     <?php $languageInputName = str_replace('@value', '@language', $name);  ?>
                     <label class='value-language' for='<?php echo $languageInputName; ?>'>Language</label>
                     <input class='value-language' type='text' name='<?php echo $languageInputName; ?>' />
                     <?php endif; ?>
                     </div>
                     <div class="items input-option">
                        <span class="default">No item selected</span>
                        <a href="#resource-select" class="button">Select Omeka Resource</a>
                    </div>
                     <button class="remove-value">Remove value</button>
                </div>
            </div>

            <?php
            echo $formErrors($element);
            ?>
        </div>
        <?php else: ?>
        <!-- Display the hidden input for the property id -->
        <?php echo $formElement($element); ?>
        <?php endif; ?>
        <?php endforeach; ?>
        
        <div class='new resource-values field template'>
            <div class="field-actions">
                <a href="#" class="remove button o-icon-times"><span class="screen-reader-text">Remove</span></a>
                <a href="#" class="add-value button o-icon-add"><span class="screen-reader-text">Add Value</span></a>
            </div>
            <div class='field-meta'>
                <input type="text" title="new-property-name" placeholder="Property name">
                <div class='properties'>
                    <ul>
                        <li class='all-vocabs'>
                            Vocabularies (<span class='count'><?php echo count($vocabularies); ?></span>)
                            <ul>
                                <?php foreach ($vocabularies as $label => $vocabulary) : ?>
                                <li class='vocabulary'>
                                    <?php echo $label; ?>
                                    <ul>
                                        <?php foreach ($vocabulary as $propertyInfo) : ?>
                                        <li class='property' data-property-id='<?php echo $propertyInfo["id"]; ?>' data-property-qname='<?php echo $propertyInfo["qname"]; ?>'>
                                            <?php echo $propertyInfo['label']; ?>
                                            <div class='description'>
                                                <p class='o-icon-info'>
                                                    <span class='screen-reader-text'>More Info</span>
                                                </p>
                                                <p>
                                                <?php echo $propertyInfo['comment']; ?>
                                                </p>
                                            </div>
                                            <button class='set-property'>Set Property</button>
                                        </li>
                                        <?php endforeach; ?>
                                    </ul>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="inputs">
                <div class="value">
                    <div class="input-options">
                        <a link="#" class="tab active o-icon-text"><span class="screen-reader-text">Text</span></a>
                        <a link="#" class="tab o-icon-items"><span class="screen-reader-text">Omeka Item</span></a>
                        <a link="#" class="tab o-icon-link"><span class="screen-reader-text">External Resource</span></a>
                     </div>
                     <div class="active type input-option text">
                        <!-- input for the property value -->
                        <textarea name="" class="input-value"></textarea>
                        <input type='hidden' class="input-id" name="" value="" />
                        <label class='value-language' for=''>Language</label>
                        <input class='value-language' type='text' name='' />
                     </div>
                     <button class="remove-value">Remove value</button>
                </div>
            </div>
        </div>
        <a href="#" class="add-property button">Add property</a>
    </fieldset>

    <fieldset id="save-sidebar">
        <input type="submit" name="add-item-submit" value="Create Item" />
        <a href="#" class="cancel button">Cancel</a>
    </fieldset>
</form>

<div id="sidebar" class='sidebar'>
    <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text">Close Me</span></a>
    <h1>Select Resource</h1>
    <div class="search-nav">
        <div class="resource-search">
            <input type="text" id="resource-list-search">
            <button type="submit" class="o-icon-search">Search</button>
        </div>
        <nav class="pagination">
            <h2 class="screen-reader-text">Pagination</h2>
            <ul>
                <li>Page <input type="text" class="page-input" value="1"> of 4</li>
                <li><a href="#" class="first o-icon-first button"><span class="screen-reader-text">First</span></a></li>
                <li><a href="#" class="previous o-icon-prev button"><span class="screen-reader-text">Previous</span></a></li>
                <li><a href="#" class="next o-icon-next button"><span class="screen-reader-text">Next</span></a></li>
                <li><a href="#" class="last o-icon-last button"><span class="screen-reader-text">Last</span></a></li>
            </ul>
        </nav>
    </div>
    <div class="resource-list">
        <div class="item">
            <div class="placeholder"></div>
            <span class="resource-name"><a href="#">Rocket Row</a></span>
            <button class="select">Select</button>
        </div>
    </div>
    <div id="resource-details" class="sidebar">
        <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text">Close Me</span></a>
        <h1>Rocket Row</h1>
        <aside>
            <div class="images">
                <a href="http://mallhistory.org/files/original/1391b4714c0a0b209a501ccef1712389.jpg"><div class="image"></div></a>
            </div>
            <div id="resource-citation" class="element">
                <h3>Citation</h3>
                <div class="element-text">&#8220;Rocket Row,&#8221; <em>Histories of the National Mall</em>, accessed May 19, 2014, http://mallhistory.org/items/show/484.</div>
            </div>
            <div id="resource-output-formats" class="element">
                <h3>Output Formats</h3>
                <div class="element-text">            
                    <ul id="output-format-list">
                        <li><a href="/items/show/484?output=atom">atom</a></li>
                        <li><a href="/items/show/484?output=dcmes-xml">dcmes-xml</a></li>
                        <li><a href="/items/show/484?output=json">json</a></li>
                        <li><a href="/items/show/484?output=omeka-json">omeka-json</a></li>
                        <li><a href="/items/show/484?output=omeka-xml">omeka-xml</a></li>
                    </ul>
                </div>
            </div>
        </aside>
        <div class="element-set">
        </div>
        <div id="select-item">
            <a href="#" class="button">Select Resource</a>
        </div>
    </div>
</div>