<?php 
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
?>
<?php foreach ($form->getElements() as $element): ?>
<?php if ($element->getLabel()): ?>
<div class="resource-values field">
    <div class="field-actions">
        <a href="#" class="add-value button o-icon-plus"><span class="screen-reader-text">Add Value</span></a>
    </div>
    <div class='field-meta'>
    <?php echo $formLabel($element); ?>
        <div class='field-description'>
            <p class="o-icon-info-circle"><span class="screen-reader-text">More Info</span></p>
        </div>
    </div>

    <div class='inputs'>
        <div class='value'>
            <?php if ($element->getLabel() != 'Class'): ?>
            <div class="input-options">
                    <a link="#" class="tab active o-icon-text"><span class="screen-reader-text">Text</span></a>
                    <a link="#" class="tab o-icon-items"><span class="screen-reader-text">Omeka Item</span></a>
                    <a link="#" class="tab o-icon-link"><span class="screen-reader-text">External Resource</span></a>
             </div>
             <?php endif; ?>
            <?php 
                echo $formElement($element);
            ?>
        </div>
    </div>
</div>
<?php else: ?>
<!-- Display the hidden input for the property id -->
<?php echo $formElement($element); ?>
<?php endif; ?>
<?php endforeach; ?>
