<?php
$class = $item->getResourceClass();
$classLabel = $class ? $class->getLabel() : '';
?>
<tr>
    <td><input type="checkbox" id="row-1"><label class="screen-reader-text" for="row-1">Select row</label></td>
    <td>
        <span class="record-name">
            <a href="<?php echo $this->escapeHtmlAttr($this->url('admin/id', array('action' => 'show', 'id' => $item->getId()), true)); ?>"><?php echo $this->escapeHtml($item->getDisplayTitle('[untitled]')); ?></a>
        </span>
        <ul class="actions">
            <li><a href="<?php echo $this->escapeHtmlAttr($this->url('admin/id', array('action' => 'edit', 'id' => $item->getId()), true)); ?>" class="fa-pencil"><span class="screen-reader-text">Edit</span></a></li>
            <li><a href="#" class="fa-ellipsis-h"><span class="screen-reader-text">Details</span></a></li>
            <li><a href="#" class="fa-trash-o"><span class="screen-reader-text">Delete</span></a></li>
        </ul>
    </td>
    <td><?php echo $this->escapeHtml($classLabel); ?></td>
    <td><?php echo $this->escapeHtml($item->getCreated()->format('M j, Y')); ?></td>
</tr>
