<?php
$this->htmlElement('body')->appendAttribute('class', 'items browse');
$esacpe = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>
<h1><?php echo $this->translate('Items'); ?></h1>

<div id="page-actions">
    <a href="<?php echo $escapeAttr($this->url(null, array('action' => 'add'), true)); ?>" class="button"><?php echo $this->translate('Add new item'); ?></a>
</div>

<?php echo $this->pagination(); ?>

<a href="batch-edit" class="batch-edit button"><?php echo $this->translate('Batch edit selected'); ?></a>

<table id="items-list">
    <thead>
        <tr>
            <th><input type="checkbox" id="select-all"><label class="screen-reader-text" for="select-all"><?php echo $this->translate('Select all'); ?></label></th>
            <th><?php echo $this->sortLink($this->translate('Title'), 'dcterms:title'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Class'), 'resource_class_label'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Date Created'), 'created'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $item): ?>
        <tr>
            <td><input type="checkbox" id="row-<?php echo $item->id(); ?>"><label class="screen-reader-text" for="row-<?php echo $item->id(); ?>"><?php echo $this->translate('Select row'); ?></label></td>
            <td>
                <span class="record-name">
                    <a href="<?php echo $escapeAttr($item->url()); ?>"><?php echo strip_tags($item->displayTitle('[untitled]')); ?></a>
                </span>
                <ul class="actions">
                    <li><a href="<?php echo $escapeAttr($item->url('edit')); ?>"
                        class="o-icon-edit"
                        aria-label="<?php echo $escapeAttr($this->translate('Edit')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Edit')); ?>"></a></li>
                    <li><a href="#"
                        data-show-details-action="<?php echo $escapeAttr($item->url('show-details')); ?>"
                        class="o-icon-more sidebar-details"
                        aria-label="<?php echo $escapeAttr($this->translate('Details')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Details')); ?>"></a></li>
                    <li><a href="#"
                        data-show-details-action="<?php echo $escapeAttr($item->url('show-details')); ?>"
                        data-delete-action="<?php echo $escapeAttr($item->url('delete')); ?>"
                        class="o-icon-delete sidebar-delete"
                        aria-label="<?php echo $escapeAttr($this->translate('Delete')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Delete')); ?>"></a></li>
                </ul>
            </td>
            <td><?php echo $esacpe($item->displayResourceClassLabel()); ?></td>
            <td><?php echo $esacpe($this->i18n()->dateFormat($item->created())); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div id="sidebar">
    <a href="#"
        id="sidebar-close"
        class="o-icon-close"
        aria-label="<?php echo $escapeAttr($this->translate('Close')); ?>"
        title="<?php echo $escapeAttr($this->translate('Close')); ?>"></a>
    <div id="sidebar-delete-content">
        <h2><?php echo $this->translate('Delete Item'); ?></h2>
        <p><?php echo $this->translate('Are you sure you would like to delete this item?'); ?></p>
        <form method="post">
            <button><?php echo $this->translate('Confirm Delete'); ?></button>
        </form>
    </div>
    <div id="sidebar-content"></div>
</div>
