<?php $this->htmlElement('body')->appendAttribute('class', 'items browse'); ?>
<h1>Items</h1>

<div id="page-actions">
    <a href="<?php echo $this->escapeHtmlAttr($this->url(null, array('action' => 'add'), true)); ?>" class="button">Add new item</a>
</div>

<?php echo $this->pagination(); ?>

<a href="batch-edit" class="batch-edit button"><?php echo $this->translate('Batch edit selected'); ?></a>

<table id="items-list">
    <thead>
        <tr>
            <th><input type="checkbox" id="select-all"><label class="screen-reader-text" for="select-all">Select all</label></th>
            <th><?php echo $this->sortLink('Title', 'dcterms:title'); ?></th>
            <th><?php echo $this->sortLink('Class', 'resource_class_label'); ?></th>
            <th><?php echo $this->sortLink('Date Created', 'created'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $item): ?>
        <tr>
            <td><input type="checkbox" id="row-<?php echo $item->id(); ?>"><label class="screen-reader-text" for="row-<?php echo $item->id(); ?>">Select row</label></td>
            <td>
                <span class="record-name">
                    <a href="<?php echo $this->escapeHtmlAttr($this->url('admin/id', array('action' => 'show', 'id' => $item->id()), true)); ?>"><?php echo strip_tags($item->displayTitle('[untitled]')); ?></a>
                </span>
                <ul class="actions">
                    <li><a href="<?php echo $this->escapeHtmlAttr($this->url('admin/id', array('action' => 'edit', 'id' => $item->id()), true)); ?>" class="o-icon-edit" aria-label="Edit" title="Edit"></a></li>
                    <li><a href="#"
                        data-show-details-action="<?php echo $this->escapeHtmlAttr($this->url('admin/id', array('action' => 'show-details', 'id' => $item->id()), true)); ?>"
                        class="o-icon-more sidebar-details"
                        aria-label="Details"
                        title="Details"></a></li>
                    <li><a href="#"
                        data-delete-action="<?php echo $this->escapeHtmlAttr($this->url('admin/id', array('action' => 'delete', 'id' => $item->id()), true)); ?>"
                        data-show-details-action="<?php echo $this->escapeHtmlAttr($this->url('admin/id', array('action' => 'show-details', 'id' => $item->id()), true)); ?>"
                        class="o-icon-delete sidebar-delete"
                        aria-label="Delete"
                        title="Delete"></a></li>
                </ul>
            </td>
            <td><?php echo $this->escapeHtml($item->displayResourceClassLabel()); ?></td>
            <td><?php echo $this->escapeHtml($this->i18n()->dateFormat($item->created())); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div id="sidebar">
    <a href="#" id="sidebar-close" class="o-icon-close" aria-label="Close details panel" title="Close"></a>
    <div id="sidebar-content"></div>
</div>

<div class="overlay"></div>

<div class="modal">
    <div class="modal-header">
        <a href="#" class="closeBtn o-icon-close" aria-label="Close me"></a>
        <h1></h1>
    </div>
    <div class="modal-content">
    </div>
</div>
