<h2 class="o-title"><a href="<?php echo $this->escapeHtmlAttr($item->url()); ?>"><?php echo strip_tags($item->displayTitle('[untitled]')); ?></a></h2>

<div class="o-description"><?php echo $item->displayDescription(); ?></div>

<?php foreach ($item->values() as $prefix => $vocabulary): ?>
    <div class="vocabulary">
        <h3><?php echo $vocabulary['vocabulary']->label(); ?></h3>
        <?php foreach ($vocabulary['properties'] as $localName => $property): ?>
            <div class="property">
            <h4><?php echo $property['property']->label(); ?></h4>
            <?php foreach ($property['values'] as $value): ?>
                <div class="value"><?php echo $value; ?></div>
            <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endforeach; ?>
