<?php
$this->htmlElement('body')->appendAttribute('class', 'site browse front');
$title = $this->setting('installation_title', 'Omeka S');
$subtitle = $this->translate('Sites');
$this->headTitle($subtitle);
?>
<h1><?php echo $title; ?></h1>
<h2 class="site-list-heading"><?php echo $subtitle; ?></h2>

<?php if ($sites): ?>
<div class="site-list">
<?php
foreach ($sites as $site):
    $summary = $site->summary();
?>
<div class="site">
    <?php echo $this->hyperlink($site->title(), $site->siteUrl(), ['class' => 'site-link']); ?>
    <?php if ($summary): ?>
    <p class="site-summary"><?php echo nl2br($this->escapeHtml($summary)); ?></p>
    <?php endif; ?>
</div>
<?php endforeach; ?>
</div>

<?php echo $this->pagination(); ?>

<?php endif; ?>
<p><?php echo sprintf(
    $this->translate('Go to the %s to start working with %s.'),
    $this->hyperlink($this->translate('Admin dashboard'), $this->url('admin')),
    $title
); ?></p>
