<?php
$translate = $this->plugin('translate');

$this->htmlElement('body')->appendAttribute('class', 'site browse front');
$title = $this->setting('installation_title', 'Omeka S');
$subtitle = $translate('Sites');
$this->headTitle($subtitle);
?>
<h1><?php echo $title; ?></h1>
<h2 class="site-list-heading"><?php echo $subtitle; ?></h2>

<?php if ($sites): ?>

<form action="<?php echo $this->escapeHtml($this->url('search', ['action' => 'results'])); ?>">
    <input type="text" name="fulltext_search">
    <input type="submit">
</form>

<div class="site-list">
<?php
foreach ($sites as $site):
    echo $this->partial('common/site-list-entry', ['site' => $site, 'showSummary' => true]);
endforeach;
?>
</div>

<?php echo $this->pagination(); ?>

<?php endif; ?>
<p><?php echo sprintf(
    $translate('Go to the %1$s to start working with %2$s.'),
    $this->hyperlink($translate('Admin dashboard'), $this->url('admin')),
    $title
); ?></p>
