<legend class="o-icon-text"><?php echo $this->translate('Text value'); ?></legend>
<a href="#" class="value-language o-icon-language" aria-label="<?php echo $this->translate('Set language'); ?>" title="<?php echo $this->translate('Set language'); ?>"></a>
<input class="value-language" type="text" data-value-key="@language">
<textarea name="" class="input-value" data-value-key="@value"></textarea>
