<?php 
$escape = $this->plugin('escapeHtml');
?>
<legend class="o-icon-resource"><?php echo $this->translate('Omeka resource'); ?></legend>
<span class="default"><?php echo $this->translate('No resource selected'); ?></span>
<p class="selected-resource">
    <span class="o-title"></span>
    <input type="hidden" class="value">
</p>
<a href="#item-resource-select"  class="o-icon-items button resource-select" data-sidebar-content-url="<?php echo $escape($this->url('admin/default', ['controller' => 'item', 'action' => 'sidebar-select'], false)); ?>"><?php echo $this->translate('Items'); ?></a>
<a href="#itemset-resource-select" class="o-icon-item-sets button resource-select" data-sidebar-content-url="<?php echo $escape($this->url('admin/default', ['controller' => 'item-set', 'action' => 'sidebar-select'], false)); ?>"><?php echo $this->translate('Item Sets'); ?></a>
