<header>
    <div class="logo"><a href="<?php echo $this->url('admin'); ?>">Omeka S</a></div>
    <div id="current-user">
        <?php if ($this->identity()): ?>
        <p>Welcome, <a href="<?php echo $this->url('admin/id', array(
            'controller' => 'user',
            'id' => $this->identity()->getId(),
        )); ?>"><?php echo $this->identity()->getName() ?></a></p>
        <p><a href="#">Logout</a></p>
        <?php else: ?>
        <p>not logged in</p>
        <?php endif; ?>
    </div>
    <div id="search">
        <input type="text" name="global-search">
        <button>Advanced Options</button>
        <button type="submit">Search</button>
    </div>
    <nav id="primary-nav">
        <ul>
            <li><a href="<?php echo $this->url('admin/default', array(
                'controller' => 'item',
                'action' => 'browse',
            )); ?>" class="icon-items">Items</a></li>
            <li><a href="#" class="icon-item-sets">Item Sets</a></li>
            <li><a href="<?php echo $this->url('admin/default', array(
                'controller' => 'vocabulary',
                'action' => 'browse',
            )); ?>" class="icon-vocabularies">Vocabularies</a></li>
            <li><a href="#" class="icon-media">Media</a></li>
            <li><a href="#" class="icon-modules">Modules</a></li>
            <li><a href="#" class="icon-users">Users</a></li>
            <li><a href="#" class="icon-sites">Sites</a></li>
            <li><a href="#" class="icon-settings">Settings</a></li>
        </ul>
    </nav>
</header>
