<header>
    <div class="logo"><a href="<?php echo $this->url('admin'); ?>">Omeka S</a></div>
    <div id="mobile-nav">
        <a href="#" class="icon-menu button"><span class="screen-reader-text">Navigation Menu</span></a>
        <a href="#" class="icon-search button"><span class="screen-reader-text">Search Site</span></a>
        <a href="#" class="icon-user button"><span class="screen-reader-text">User Menu</span></a>
    </div>
    <div id="current-user">
        <?php if ($this->identity()): ?>
        <p>Welcome, <a href="<?php echo $this->url('admin/id', array(
            'controller' => 'user',
            'id' => $this->identity()->getId(),
        )); ?>"><?php echo $this->identity()->getName() ?></a></p>
        <p><a href="<?php echo $this->url('logout'); ?>">Logout</a></p>
        <?php else: ?>
        <p>not logged in</p>
        <?php endif; ?>
    </div>
    <div id="search">
        <form id="search-form">
            <input type="text" name="global-search">
            <button>Advanced Options</button>
            <button type="submit">Search</button>
        </form>
    </div>
    <nav id="menu" role="navigation"><?php echo $this->navigation('navigation'); ?></nav>
    </nav>
</header>
