<header>
    <div class="logo"><a href="<?php echo $this->url('admin'); ?>">Omeka S</a></div>
    <div id="current-user">
        <?php if ($this->identity()): ?>
        <p>Welcome, <a href="<?php echo $this->url('admin/id', array(
            'controller' => 'user',
            'id' => $this->identity()->getId(),
        )); ?>"><?php echo $this->identity()->getName() ?></a></p>
        <p><a href="#">Logout</a></p>
        <?php else: ?>
        <p>not logged in</p>
        <?php endif; ?>
    </div>
    <div id="search">
        <input type="text" name="global-search">
        <button>Advanced Options</button>
        <button type="submit">Search</button>
    </div>
    <nav id="primary-nav"><?php echo $this->navigation('navigation'); ?></nav>
    </nav>
</header>
