<?php $this -> htmlElement('body')->appendAttribute('class', 'install'); ?>
<?php
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formInput = $this->plugin('formInput');
$formErrors = $this->plugin('formElementErrors');
$form->setAttribute('action', $this->url('install'));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>

<?php foreach ($form->getElements() as $element): ?>
<div class="field">
<?php 
    echo $formLabel($element);
    echo $formInput($element);
    echo $formErrors($element, array('class' => 'messages'));
 ?>
</div>
<?php endforeach; ?>
<button>Install</button>
<?php
echo $this->form()->closeTag();
?>
