<?php
$this->htmlElement('body')->appendAttribute('class', 'vocabs browse');
$escape = $this->plugin('escapeHtml');
$sortHeadings = [
    [
        'label' => $this->translate('Label'),
        'value' => 'label'
    ],
    [
        'label' => $this->translate('Prefix'),
        'value' => 'prefix'
    ],
    [
        'label' => $this->translate('Classes'),
        'value' => 'resource_class_count'
    ],
    [
        'label' => $this->translate('Properties'),
        'value' => 'property_count'
    ]
];
?>

<?php echo $this->pageTitle($this->translate('Vocabularies')); ?>

<div id="page-actions">
    <?php if ($this->userIsAllowed('Omeka\Api\Adapter\VocabularyAdapter', 'create')): ?>
    <?php echo $this->hyperlink($this->translate('Import new vocabulary'), $this->url(null, ['action' => 'import'], true), ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<?php if (count($vocabularies) > 0): ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>
<?php $this->trigger('view.browse.before'); ?>
<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Label'); ?></th>
            <th><?php echo $this->translate('Prefix'); ?></th>
            <th><?php echo $this->translate('Classes'); ?></th>
            <th><?php echo $this->translate('Properties'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($vocabularies as $vocabulary): ?>
        <tr>
            <td>
                <?php echo $escape($this->translate($vocabulary->label())); ?>
                <ul class="actions">
                    <?php if (!$vocabulary->isPermanent()): ?>
                    <?php if ($vocabulary->userIsAllowed('update')): ?>
                    <li><?php echo $vocabulary->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'title' => $this->translate('Edit'),
                    ]); ?></li>
                    <?php endif; ?>
                    <?php if ($vocabulary->userIsAllowed('delete')): ?>
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-content-url' => $vocabulary->url('delete-confirm'),
                        'class' => 'o-icon-delete sidebar-content',
                        'title' => $this->translate('Delete'),
                    ]); ?></li>
                    <?php endif; ?>
                    <?php endif; ?>
                    <li><?php echo $this->hyperlink('', '#', [
                        'data-sidebar-content-url' => $vocabulary->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $this->translate('Details'),
                    ]); ?></li>
                </ul>
            </td>
            <td><?php echo $escape($this->translate($vocabulary->prefix())); ?></td>
            <td><?php echo $this->hyperlink($vocabulary->resourceClassCount(), $this->url('admin/id', ['action' => 'classes', 'id' => $vocabulary->id()], true)); ?></td>
            <td><?php echo $this->hyperlink($vocabulary->propertyCount(), $this->url('admin/id', ['action' => 'properties', 'id' => $vocabulary->id()], true)); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any vocabularies.'); ?></p>
</div>

<?php endif; ?>
