<?php
$this->htmlElement('body')->appendAttribute('class', 'vocabs browse');
$confirmForm->prepare();
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>

<h1><?php echo $this->translate('Vocabularies'); ?></h1>

<div id="page-actions">
    <a href="<?php echo $escapeAttr($this->url(null, array('action' => 'import'), true)); ?>" class="button">Import new vocabulary</a>
</div>

<?php echo $this->pagination(); ?>

<table>
    <thead>
        <tr>
            <th><?php echo $this->sortLink($this->translate('Label'), 'label'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Prefix'), 'prefix'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Classes'), 'resource_class_count'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Properties'), 'property_count'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($vocabularies as $vocabulary): ?>
        <tr>
            <td>
                <span class="resource-name">
                    <?php echo $escape($vocabulary->label()); ?>
                </span>
                <ul class="actions">
                    <?php if (!$vocabulary->isPermanent()): ?>
                    <li><?php echo $vocabulary->link('', 'edit', array(
                        'class' => 'o-icon-edit',
                        'aria-label' => $this->translate('Edit'),
                        'title' => $this->translate('Edit'),
                    )); ?></li>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escapeAttr($vocabulary->url('show-details')); ?>"
                        data-sidebar-confirm-url="<?php echo $escapeAttr($vocabulary->url('delete')); ?>"
                        class="o-icon-delete sidebar-confirm"
                        aria-label="<?php echo $escapeAttr($this->translate('Delete')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Delete')); ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escapeAttr($vocabulary->url('show-details')); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escapeAttr($this->translate('Details')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Details')); ?>"></a>
                    </li>
                </ul>
            </td>
            <td><?php echo $escape($vocabulary->prefix()); ?></td>
            <td><?php echo $this->hyperlink($vocabulary->resourceClassCount(), $this->url('admin/id', array('action' => 'classes', 'id' => $vocabulary->id()), true)); ?></td>
            <td><?php echo $this->hyperlink($vocabulary->propertyCount(), $this->url('admin/id', array('action' => 'properties', 'id' => $vocabulary->id()), true)); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->pagination(); ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escapeAttr($this->translate('Close')); ?>"
        title="<?php echo $escapeAttr($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $escape($this->translate('Delete Vocabulary')); ?></h2>
        <p><?php echo $escape($this->translate('Are you sure you would like to delete this vocabulary?')); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>
