<?php $form->prepare(); ?>
<h1><?php echo $this->escapeHtml($this->translate(sprintf('Edit Vocabulary “%s”', $vocabulary->label()))); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->escapeHtml($this->translate('Save changes')); ?></button>
    <a href="<?php echo $this->url('admin/default', array('controller'=>'vocabulary', 'action'=>'browse')); ?>" class="cancel button">Cancel</a>
</div>
<?php echo $this->formElements($form); ?>
<?php echo $this->form()->closeTag(); ?>
