<?php 
$this->htmlElement('body')->appendAttribute('class', 'edit vocabularies');
$form->prepare(); 
?>

<?php echo $this->pageTitle($this->translate($vocabulary->label()), 1, $this->translate('Vocabularies'), $this->translate('Edit')); ?>
<?php $this->trigger('view.edit.before'); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <a href="#" class="delete button"><?php echo $this->translate('Delete'); ?></a>
    <button><?php echo $this->translate('Save'); ?></button>
</div>
<?php $this->trigger('view.edit.form.before', ['form' => $form]); ?>
<?php echo $this->formCollection($form, false); ?>
<?php $this->trigger('view.edit.form.after', ['form' => $form]); ?>
<?php echo $this->form()->closeTag(); ?>
<?php echo $this->deleteConfirm($vocabulary, 'vocabulary'); ?>

<?php $this->trigger('view.edit.after'); ?>
