<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'vocabularies import');
$form->prepare();
?>

<?php echo $this->pageTitle($translate('New vocabulary'), 1, $translate('Vocabularies')); ?>

<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <?php echo $this->cancelButton(); ?>
    <button><?php echo $translate('Import'); ?></button>
</div>
<?php echo $this->formCollection($form); ?>
<?php echo $this->form()->closeTag(); ?>
<script>
$('#vocabularyform').on('submit', function(e) {
    const namespaceUriInput = $('#o\\:namespace_uri');
    const namespaceUri = namespaceUriInput.val();
    // Confirm that the namespace URI ends with / or #.
    if (!(namespaceUri.endsWith('/') || namespaceUri.endsWith('#'))) {
        if (!window.confirm(namespaceUriInput.data('confirmMessage'))) {
            e.preventDefault();
        }
    }
});
</script>
