<div class="meta-group">
    <h4><?php echo $this->escapeHtml($vocabulary->label()); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($vocabulary->comment()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Prefix:'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($vocabulary->prefix()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Namespace URI:'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($vocabulary->namespaceUri()); ?></div>
</div>
