<?php $this->htmlElement('body')->appendAttribute('class', 'add resource-template sidebar-open'); ?>

<?php echo $this->pageTitle($this->translate('Add Resource Template')); ?>

<?php
echo $this->partial(
    'omeka/admin/resource-template/form.phtml',
    array(
        'form' => $form,
        'propertyRows' => $propertyRows,
        'resourceClassId' => $resourceClassId,
        'submitLabel' => $this->translate('Add'),
    )
);
?>

<?php $this->trigger('view.add.after'); ?>
