<?php
$this->htmlElement('body')->appendAttribute('class', 'resource-templates browse');
$escape = $this->plugin('escapeHtml');
$sortHeadings = [
    [
        'label' => $this->translate('Label'),
        'value' => 'label'
    ],
    [
        'label' => $this->translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $this->translate('Owner'),
        'value' => 'owner_name'
    ],
    [
        'label' => $this->translate('Items'),
        'value' => 'item_count'
    ]
];
?>

<?php echo $this->pageTitle($this->translate('Resource Templates')); ?>

<div id="page-actions">
    <?php if ($this->userIsAllowed('Omeka\Api\Adapter\ResourceTemplateAdapter', 'create')): ?>
    <?php echo $this->hyperlink($this->translate('Add new resource template'), $this->url(null, array('action' => 'add'), true), array('class' => 'button')); ?>
    <?php endif; ?>
</div>

<?php if (count($resourceTemplates)): ?>

<?php echo $this->pagination(); ?>

<?php echo $this->sortSelector($sortHeadings); ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('Label'); ?></th>
            <th><?php echo $this->translate('Class'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
            <th><?php echo $this->translate('Items'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($resourceTemplates as $resourceTemplate): ?>
        <?php
        if ($owner = $resourceTemplate->owner()) {
            $ownerText = $this->hyperlink(
                $owner->name(),
                $this->url('admin/id', array(
                    'controller' => 'user',
                    'action' => 'show',
                    'id' => $owner->id())
                )
            );
        } else {
            $ownerText = $this->translate('[no owner]');
        }
        ?>
        <tr>
            <td>
                <span class="resource-name">
                    <?php echo $resourceTemplate->link($resourceTemplate->label()); ?>
                </span>
                <ul class="actions">
                    <?php if ($resourceTemplate->userIsAllowed('update')): ?>
                    <li><?php echo $resourceTemplate->link('', 'edit', array(
                        'class' => 'o-icon-edit',
                        'aria-label' => $escape($this->translate('Edit')),
                        'title' => $escape($this->translate('Edit')),
                    )); ?></li>
                    <?php endif; ?>
                    <?php if ($resourceTemplate->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($resourceTemplate->url('show-details')); ?>"
                        data-sidebar-confirm-url="<?php echo $escape($resourceTemplate->url('delete')); ?>"
                        class="o-icon-delete sidebar-confirm"
                        aria-label="<?php echo $escape($this->translate('Delete')); ?>"
                        title="<?php echo $escape($this->translate('Delete')); ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($resourceTemplate->url('show-details')); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escape($this->translate('Details')); ?>"
                        title="<?php echo $escape($this->translate('Detail')); ?>"></a></li>
                 </ul>
            </td>
            <td><?php echo $escape($resourceTemplate->displayResourceClassLabel()); ?></td>
            <td><?php echo $ownerText; ?></td>
            <td><?php echo $this->hyperlink($resourceTemplate->itemCount(), $this->url('admin/default', array('controller' => 'item', 'action' => 'browse'), array('query' => array('resource_template_id' => $resourceTemplate->id())))); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $this->translate('Delete Template'); ?></h2>
        <p><?php echo $this->translate('Are you sure you would like to delete this resource template?'); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any resource templates.'); ?></p>
</div>

<?php endif; ?>

<?php $this->trigger('view.browse.after'); ?>
