<?php $this->htmlElement('body')->appendAttribute('class', 'edit resource-template'); ?>

<?php echo $this->pageTitle(sprintf($this->translate('Edit Resource Template: “%s”'), $resourceTemplate->label())); ?>

<?php
echo $this->partial(
    'omeka/admin/resource-template/form.phtml',
    [
        'form' => $form,
        'resourceTemplate' => $resourceTemplate,
        'propertyRows' => $propertyRows,
        'resourceClassId' => $resourceClassId,
        'submitLabel' => $this->translate('Save'),
        'confirmForm' => $confirmForm,
        'formAfterEvent' => 'view.edit.form.after',
    ]
);
?>

<?php $this->trigger('view.edit.after'); ?>
