<?php $this->htmlElement('body')->appendAttribute('class', 'edit resource-template sidebar-open'); ?>

<?php echo $this->pageTitle(sprintf($this->translate('Edit Resource Template: “%s”'), $resourceTemplate->label())); ?>

<?php
echo $this->partial(
    'omeka/admin/resource-template/form.phtml',
    array(
        'form' => $form,
        'resourceTemplate' => $resourceTemplate,
        'propertyRows' => $propertyRows,
        'resourceClassId' => $resourceClassId,
        'submitLabel' => $this->translate('Save'),
        'confirmForm' => $confirmForm
    )
);
?>

<?php $this->trigger('view.edit.after'); ?>
