<?php
$form->prepare();
$this->htmlElement('body')->appendAttribute('class', 'resource-template');
echo $this->pageTitle(sprintf($this->translate('Resource Template: Review “%s”'), $template['o:label']));
?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Complete import'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>

<?php if ($notFound['class'] || $notFound['properties']): ?>
<h3 style="color: red;">Not Able to Import</h3>
<table>
<thead>
    <tr>
        <th>Type</th>
        <th>Namespace URI</th>
        <th>Local Name</th>
    </tr>
</thead>
<tbody>
    <?php if ($notFound['class']): ?>
    <tr>
        <td>Class</td>
        <td><?php echo $notFound['class']['namespace_uri']; ?></td>
        <td><?php echo $notFound['class']['local_name']; ?></td>
    </tr>
    <?php endif; ?>
    <?php foreach ($notFound['properties'] as $property): ?>
    <tr>
        <td>Property</td>
        <td><?php echo $property['namespace_uri']; ?></td>
        <td><?php echo $property['local_name']; ?></td>
    </tr>
    <?php endforeach; ?>
</tbody>
</table>
<?php endif; ?>

<h3 style="color: green;">Able to Import</h3>

<?php if ($template['o:resource_class']): ?>
<?php $vocab = $vocabs[$template['o:resource_class']['namespace_uri']]; ?>
<div class="class-row">
    <span class="class-label"><?php echo $this->translate('Class'); ?></span>
    <span class="class-value"><?php echo sprintf('%s:%s', $vocab->prefix(), $template['o:resource_class']['local_name']); ?></span>
</div>
<?php endif; ?>

<table id="properties" class="tablesaw" data-tablesaw-mode="stack">
<thead>
    <tr>
        <th><?php echo $this->translate('Property'); ?></th>
        <th><?php echo $this->translate('Alternate Label'); ?></th>
        <th><?php echo $this->translate('Alternate Comment'); ?></th>
        <th><?php echo $this->translate('Required?'); ?></th>
    </tr>
</thead>
<tbody>
<?php foreach ($template['o:resource_template_property'] as $property): ?>
<?php $vocab = $vocabs[$property['namespace_uri']]; ?>
    <tr>
        <td><?php echo sprintf('%s:%s', $vocab->prefix(), $property['local_name']); ?></td>
        <td><?php echo $property['o:alternate_label']; ?></td>
        <td><?php echo $property['o:alternate_comment']; ?></td>
        <td><?php echo $property['o:is_required'] ? 'Yes' : 'No'; ?></td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
