<?php
$form->prepare();
$this->htmlElement('body')->appendAttribute('class', 'resource-template');
echo $this->pageTitle(sprintf($this->translate('Resource Template: Review “%s”'), $template['o:label']));
?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Complete import'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>

<?php if ($template['o:resource_class']): ?>
<?php $vocab = $vocabs[$template['o:resource_class']['namespace_uri']]; ?>
<div class="class-row">
    <span class="class-label"><?php echo $this->translate('Class'); ?></span>
    <span class="class-value"><?php echo sprintf('%s:%s', $vocab->prefix(), $template['o:resource_class']['local_name']); ?></span>
</div>
<?php endif; ?>

<table id="properties" class="tablesaw" data-tablesaw-mode="stack">
<thead>
    <tr>
        <th><?php echo $this->translate('Property'); ?></th>
        <th><?php echo $this->translate('Alternate Label'); ?></th>
        <th><?php echo $this->translate('Alternate Comment'); ?></th>
        <th><?php echo $this->translate('Required?'); ?></th>
    </tr>
</thead>
<tbody>
<?php foreach ($template['o:resource_template_property'] as $property): ?>
<?php
$hasVocab = isset($vocabs[$property['namespace_uri']]);
$hasProperty = isset($property['o:property']['o:id']);
if (!$hasVocab) {
    $uri = '<span style="color:red;">' . $property['namespace_uri'] . $property['local_name'] . '</span>';
} elseif (!$hasProperty)  {
    $uri = $vocabs[$property['namespace_uri']]->prefix() . ':<span style="color:red;">' . $property['local_name'] . '</span>';
} else {
    $uri = $vocabs[$property['namespace_uri']]->prefix() . ':' . $property['local_name'];
}
?>
    <tr style="background-color:#<?php echo $hasProperty ? 'cdffcd;' : 'ffe6e6'; ?>">
        <td><?php echo sprintf('%s<br>%s', $property['label'], $uri); ?></td>
        <td><?php echo $property['o:alternate_label']; ?></td>
        <td><?php echo $property['o:alternate_comment']; ?></td>
        <td><?php echo $property['o:is_required'] ? 'Yes' : 'No'; ?></td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
