<?php
$escape = $this->plugin('escapeHtml');
?>
<h2><?php echo $this->translate($resource->link($resource->label())); ?></h2>
<?php foreach ($resource->resourceTemplateProperties() as $resourceTemplateProperty): ?>
<?php
$property = $resourceTemplateProperty->property();
$propertyAltLabel = $escape($resourceTemplateProperty->alternateLabel());
$propertyAltComment = $escape($resourceTemplateProperty->alternateComment());
?>
<div class="meta-group">
    <h4><?php echo ($propertyAltLabel) ? $propertyAltLabel : $property->label(); ?></h4>
    <div class="comment"><?php echo ($propertyAltComment) ? $propertyAltComment : $property->comment(); ?></div>
</div>
<?php endforeach; ?>
