<div class="annotation-value">
    <?php echo $this->propertySelect([
        'name' => 'annotation-property',
        'attributes' => [
            'class' => 'annotation-property',
        ],
    ]); ?>
    <select class="annotation-type">
        <option value="literal"><?php echo $this->translate('Text'); ?></option>
        <option value="uri"><?php echo $this->translate('URI'); ?></option>
    </select>
    <textarea class="annotation-literal-value"></textarea>
    <input type="text" class="annotation-uri-uri" placeholder="<?php echo $this->escapeHtml($this->translate('URI')); ?>" style="display: none;">
    <input type="text" class="annotation-uri-label" placeholder="<?php echo $this->escapeHtml($this->translate('Label')); ?>" style="display: none;">
    <a href="#" class="o-icon-delete remove-annotation-value" title="<?php echo $this->escapeHtml($this->translate('Remove value')) ?>" aria-label="<?php echo $this->escapeHtml($this->translate('Remove value')) ?>"></a>
    <a href="#" class="o-icon-undo restore-annotation-value" title="<?php echo $this->escapeHtml($this->translate('Restore value')) ?>" aria-label="<?php echo $this->escapeHtml($this->translate('Restore value')) ?>" style="display: none;"></a>
</div>
