<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$mediaInput = null;
$altLabelInput = null;
$headingInput = null;
$descriptionInput = null;
$form->prepare();
?>
<div class="sidebar" id="asset-options">
  <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $translate('Close'); ?></span></a>
  <div class="sidebar-content">
    <h3><?php echo $translate('Asset Options'); ?></h3>
    <span class="selected-asset">
        <img class="selected-asset-image" src="" alt="">
        <div class="selected-asset-name"></div>
        <input type="hidden" name="selected-asset-id" class="selected-asset-id">
        <button type="button" class="asset-attachment-select" data-sidebar-content-url="<?php echo $this->escapeHtml($this->url('admin/default', ['controller' => 'asset', 'action' => 'sidebar-select'])); ?>"><?php echo $translate('Select'); ?></button>
    </span>
    <div class="alt-label">
      <h3><?php echo $translate('Page link'); ?></h3>
      <span class="none-selected"><?php echo $translate('[No page selected]'); ?></span>
      <button type="button"><?php echo $translate('Select'); ?></button>
      <button type="button"><?php echo $translate('Clear'); ?></button>
    </div>
  </div>

  <div id="asset-options-confirm-panel" class="confirm-panel">
    <button><?php echo $translate('Apply changes'); ?></button>
  </div>
</div>