<?php echo $this->formElement($element->getAssetElement()); ?>
<?php echo $this->translate('Vertical anchor position'); ?>
<?php echo $this->formElement($element->getPositionYElement()); ?>
<?php echo $this->translate('Horizontal anchor position'); ?>
<?php echo $this->formElement($element->getPositionXElement()); ?>
<?php echo $this->translate('Size'); ?>
<?php echo $this->formElement($element->getSizeElement()); ?>
