<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$expandString = $translate('Expand');
?>
<div class="confirm-main">
    <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $translate('Close'); ?></span></a>
    <h3><?php echo $translate('Block layout configuration'); ?></h3>
    <div class="sidebar-group">
        <?php $templateField = $blockLayoutDataForm->get('template_name'); ?>
        <a href="#" class="expand" aria-label="<?php echo $expandString; ?>" title="<?php echo $expandString; ?>">
            <?php echo $this->formLabel($templateField); ?>
        </a>
        <div class="collapsible">
            <?php echo $this->formSelect($templateField); ?>
        </div>
    </div>
    <div class="sidebar-group">
        <?php $classField = $blockLayoutDataForm->get('class'); ?>
        <a href="#" class="expand" aria-label="<?php echo $expandString; ?>" title="<?php echo $expandString; ?>">
            <?php echo $this->formLabel($classField); ?>
        </a>
        <div class="collapsible">
            <?php echo $this->formInput($classField); ?>
        </div>
    </div>
    <div class="sidebar-group">
        <a href="#" class="expand" aria-label="<?php echo $expandString; ?>" title="<?php echo $expandString; ?>">
            <span class="label"><?php echo $translate('Alignment'); ?></span>
        </a>
        <div class="collapsible"> 
            <?php echo $this->formRow($blockLayoutDataForm->get('alignment_block')); ?>
            <?php echo $this->formRow($blockLayoutDataForm->get('alignment_text')); ?>
        </div>
    </div>
    <div class="sidebar-group">
        <a href="#" class="expand" aria-label="<?php echo $expandString; ?>" title="<?php echo $expandString; ?>">
            <spans class="label"><?php echo $translate('Constraints'); ?></span>
        </a>
        <div class="collapsible"> 
            <?php echo $this->formRow($blockLayoutDataForm->get('max_width')); ?>
            <?php echo $this->formRow($blockLayoutDataForm->get('min_height')); ?>
        </div>
    </div>
    <div class="sidebar-group padding">
        <a href="#" class="expand" aria-label="<?php echo $expandString; ?>" title="<?php echo $expandString; ?>">
            <span class="label"><?php echo $translate('Padding'); ?></span>
        </a>
        <div class="collapsible"> 
            <?php echo $this->formElement($blockLayoutDataForm->get('padding')); ?>
        </div>
    </div>
    <div class="sidebar-group">
        <a href="#" class="expand" aria-label="<?php echo $expandString; ?>" title="<?php echo $expandString; ?>">
           <span class="label"><?php echo $translate('Background'); ?></span>
        </a>
        <div class="collapsible"> 
            <?php echo $this->formRow($blockLayoutDataForm->get('background_color')); ?>
            <?php echo $this->formRow($blockLayoutDataForm->get('background_image')); ?>
        </div>
    </div>
</div>
<div class="confirm-panel">
    <button id="apply-block-layout-data"><?php echo $translate('Apply changes'); ?></button>
</div>