<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$pageLayoutGridColumnPositionOptions = ['auto' => $translate('Auto placement')];
foreach (range(1, 12) as $value) {
    $pageLayoutGridColumnPositionOptions[$value] = sprintf($translate('Position %s'), $value);
}
$pageLayoutGridColumnSpanOptions = [];
foreach (range(1, 12) as $value) {
    $pageLayoutGridColumnSpanOptions[$value] = sprintf($translate('Span %s'), $value);
}
$pageLayoutGridColumnPosition = $pageLayoutData['grid_column_position'] ?? '';
$pageLayoutGridColumnSpan = $pageLayoutData['grid_column_span'] ?? '';
?>

<div class="block value" data-block-layout="<?php echo $escape($layout); ?>">
    <div class="block-header collapse">
        <span class="sortable-handle"></span>
        <span class="block-type"><?php echo $translate($layoutLabel); ?></span>
        <span class="restore-value"><?php echo $translate('Block to be removed'); ?></span>
        <span class="block-page-layout-grid-controls">
            <select name="o:block[__blockIndex__][o:page_layout_data][grid_column_position]" class="block-page-layout-grid-column-position-select" data-block-page-layout-grid-column-position="<?php echo $escape($pageLayoutGridColumnPosition); ?>">
                <?php foreach ($pageLayoutGridColumnPositionOptions as $key => $value): ?>
                <option value="<?php echo $escape($key); ?>"<?php echo ($pageLayoutGridColumnPosition == $key) ? ' selected' : '' ?>><?php echo $value; ?></option>
                <?php endforeach; ?>
            </select>
            <select name="o:block[__blockIndex__][o:page_layout_data][grid_column_span]" class="block-page-layout-grid-column-span-select" data-block-page-layout-grid-column-span="<?php echo $escape($pageLayoutGridColumnSpan); ?>">
                <?php foreach ($pageLayoutGridColumnSpanOptions as $key => $value): ?>
                <option value="<?php echo $escape($key); ?>"<?php echo ($pageLayoutGridColumnSpan == $key) ? ' selected' : '' ?>><?php echo $value; ?></option>
                <?php endforeach; ?>
            </select>
        </span>
        <ul class="actions">
            <li><a href="#" class="o-icon-expand collapse" aria-label="<?php echo $translate('Collapse'); ?>" title="<?php echo $translate('Collapse'); ?>"></a></li>
            <li><a href="#" class="o-icon-delete remove-value" aria-label="<?php echo $translate('Remove value'); ?>" title="<?php echo $translate('Remove value'); ?>"></a></li>
            <li><a href="#" class="o-icon-undo restore-value inactive" aria-label="<?php echo $translate('Restore value'); ?>" title="<?php echo $translate('Restore value'); ?>"></a></li>
        </ul>
    </div>
    <div class="block-content collapsible">
    <input type="hidden" name="o:block[__blockIndex__][o:layout]" value="<?php echo $escape($layout); ?>">
    <?php echo $blockContent; ?>
    </div>
</div>
