<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>

<div class="block value" data-block-layout="<?php echo $escape($layout); ?>">
    <div class="block-header collapse">
        <span class="sortable-handle"></span>
        <span class="block-type"><?php echo $translate($layoutLabel); ?></span>
        <span class="restore-value"><?php echo $translate('Block to be removed'); ?></span>
        <ul class="actions">
            <li><a href="#" class="o-icon-expand collapse" aria-label="<?php echo $translate('Collapse'); ?>" title="<?php echo $translate('Collapse'); ?>"></a></li>
            <li><a href="#" class="o-icon-delete remove-value" aria-label="<?php echo $translate('Remove value'); ?>" title="<?php echo $translate('Remove value'); ?>"></a></li>
            <li><a href="#" class="o-icon-undo restore-value inactive" aria-label="<?php echo $translate('Restore value'); ?>" title="<?php echo $translate('Restore value'); ?>"></a></li>
        </ul>
    </div>
    <div class="block-content collapsible">
    <input type="hidden" name="o:block[__blockIndex__][o:layout]" value="<?php echo $escape($layout); ?>">
    <?php echo $blockContent; ?>
    </div>
</div>
