<?php
$escape = $this->plugin('escapeHtml');
?>
<div class="template value" data-data-type="<?php echo $escape($this->dataType); ?>" role="group">
    <input type="hidden" class="property">
    <input type="hidden" class="type">
    <div class="input-body"><?php echo $this->dataType()->getTemplate($dataType); ?></div>
    <div class="input-footer">
        <span class="restore-value"><?php echo $this->translate('Value to be removed'); ?></span>
        <ul class="actions">
            <li><?php echo $this->hyperlink('', '#', ['class' => 'o-icon-delete remove-value', 'title' => $this->translate('Remove value')]); ?></li>
            <li><?php echo $this->hyperlink('' , '#', ['class' => 'o-icon-undo restore-value', 'title' => $this->translate('Restore value')]); ?></li>
        </ul>
    </div>
</div>
