<?php
$this->form->setAttribute('action', $resource->url('delete'));
$this->form->setButtonLabel('Confirm delete'); // @translate
?>
<?php if ($this->wrapSidebar): ?>
<div id="delete" class="sidebar">
    <a href="#" class="sidebar-close o-icon-close" aria-label="<?php echo $this->escapeHtml($this->translate('Close')); ?>" title="<?php echo $this->escapeHtml($this->translate('Close')); ?>"></a>
<?php endif; ?>
    <div id="sidebar-confirm">
        <?php $resourceLabel = $this->translate($this->resourceLabel); ?>
        <h3><?php echo sprintf($this->translate('Delete %s'), $resourceLabel); ?></h3>
        <p><?php echo sprintf($this->translate('Are you sure you would like to delete this %s?'), $resourceLabel); ?></p>
        <?php echo $this->form($this->form); ?>
    </div>
<?php if ($this->wrapSidebar): ?>
</div>
<?php endif; ?>
