<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$required = $element->getAttribute('required');
$showRequired = $element->getOption('show_required');
$isRequired = null === $showRequired ? $required : $showRequired;
$class = $isRequired ? 'field required' : 'field';
$escapeInfo = (false !== $element->getOption('escape_info'));
$fieldId = ($element->getAttribute('id')) ? 'id="' . $escape($element->getAttribute('id')) . '_field"' : '';
?>
<?php if (null === $label || 'hidden' === $element->getAttribute('type')): ?>
<?php echo $this->formElement($element); ?>
<?php else: ?>
<div class="<?php echo $class ?>" <?php echo $fieldId; ?>>
    <div class="field-meta">
        <?php echo $this->formLabel($element); ?>
        <?php if ($info = $element->getOption('info')): ?>
        <a href="#" class="expand" aria-label=" <?php echo $escape($translate('Expand')); ?>"></a>
        <div class="collapsible">
            <div class="field-description"><?php echo $escapeInfo ? $escape($translate($info)) : $translate($info); ?></div>
            <?php if ($documentation = $element->getOption('documentation')): ?>
            <a href="<?php echo $documentation; ?>" class="docs-link"><?php echo $translate('Learn more'); ?></a>
            <?php endif; ?>
        </div>
        <?php endif; ?>
    </div>
    <div class="inputs">
        <?php echo $this->formElement($element); ?>
    </div>
    <?php echo $this->formElementErrors($element, ['class' => 'messages']); ?>
</div>
<?php endif; ?>
