<div class="field">
    <div class="field-meta">
        <?php echo $this->formLabel($element); ?>
        <?php if ($info = $element->getOption('info')): ?>
        <a href="#" class="expand o-icon-right" aria-label="Expand"></a>
        <div class="field-description"><?php echo $this->escapeHtml($info); ?></div>
        <?php endif; ?>
    </div>
    <div class="inputs">
        <?php echo $this->formElement($element); ?>
    </div>
    <?php echo $this->formElementErrors($element, array('class' => 'messages')); ?>
</div>
