<div class="field">
    <div class="field-meta">
        <?php echo $this->formLabel($element); ?>
        <?php if ($info = $element->getOption('info')): ?>
        <div class="field-description">
            <a href="#" class="o-icon-info"><span class="screen-reader-text"><?php echo $this->escapeHtml($this->translate('More Info')); ?></span></a>
            <p class="field-comment"><?php echo $this->escapeHtml($info); ?></p>
        </div>
        <?php endif; ?>
    </div>
    <div class="inputs">
        <?php echo $this->formElement($element); ?>
    </div>
    <?php echo $this->formElementErrors($element, array('class' => 'messages')); ?>
</div>
