<?php
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>
<div id="item-set-selector" class='selector sidebar active'>
    <p><?php echo $this->translate('Click on an item set to add it to the edit panel.'); ?></p>
    <input type="text" class="selector-filter" placeholder=" <?php echo $escapeAttr($this->translate('Filter item sets')); ?>">
    <ul>
        <li class="show"><?php echo $this->translate('All Item Sets'); ?> (<span class="selector-total-count"><?php echo $totalItemSetCount; ?></span>)
            <ul>
                <?php foreach ($itemSetOwners as $email => $itemSetOwner): ?>
                <?php
                $owner = $itemSetOwner['owner'];
                $itemSets = $itemSetOwner['item_sets'];
                ?>
                <li class='selector-parent'>
                    <span><?php echo $escape($owner->name()); ?></span> (<span class="selector-child-count"><?php echo count($itemSets); ?></span>)
                    <ul>
                        <?php foreach ($itemSets as $itemSet): ?>
                        <li class='selector-child'
                            data-child-label="<?php echo $escapeAttr($itemSet->displayTitle()); ?>"
                            data-item-set-id="<?php echo $escapeAttr($itemSet->id()); ?>"
                            data-owner-email="<?php echo $escapeAttr($email); ?>">
                            <div class="description">
                                <p class="o-icon-info"><span class="screen-reader-text"><?php echo $this->translate('More Info'); ?></span></p>
                                <p class="field-comment"><?php echo $escape($itemSet->displayDescription()); ?></p>
                            </div>
                            <span><?php echo $escape($itemSet->displayTitle()); ?></span>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
                <?php endforeach; ?>
            </ul>
        </li>
    </ul>
</div>
