<?php
$escape = $this->plugin('escapeHtml');

$fragment = 'item-linked';
if ('Omeka\Api\Representation\ItemSetRepresentation' === get_class($objectResource)) {
    $fragment = 'item-set-linked';
}
$pagination = $this->pagination(null, $totalCount, $page, $perPage);
$pagination->setFragment($fragment);
?>
<div id="linked-resources">
<div class="linked-header">
    <div id="linked-filter">
        <h4>Filter by property</h4>
        <select id="filter-property" name="property" data-url="<?php echo $escape($this->url(null, [], true)); ?>" data-fragment="<?php echo $escape($fragment); ?>">
            <option value="">All</option>
            <?php foreach ($properties as $prop): ?>
            <option value="<?php echo $escape($prop->id()); ?>"<?php echo $prop->id() == $property ? ' selected="selected"' : ''; ?>><?php echo $escape(sprintf('%s (%s)', $prop->label(), $prop->term())); ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <?php echo ($totalCount > $perPage) ? $pagination : ''; ?>
</div>

<?php foreach ($subjectValues as $term => $values): ?>
<h4><?php echo $escape($values[0]->property()->label()); ?></h4>
<?php foreach ($values as $value): ?>
<div class="linked-resource">
    <?php echo $value->resource()->linkPretty(); ?>
    <?php if ($value->resource()->resourceClass()): ?>
    <span class="resource-class"><?php echo sprintf('%s', $value->resource()->resourceClass()->label()); ?></span>
    <?php endif; ?>
</div>
<?php endforeach; ?>
<?php endforeach; ?>

<?php echo ($totalCount > $perPage) ? '<div class="linked-footer">' . $pagination . '</div>' : ''; ?>

</div>

<script>
$('#filter-property').on('change', function(e) {
    var thisSelect = $(this);
    var property = thisSelect.find(':selected').val();
    var url = thisSelect.data('url');
    var fragment = thisSelect.data('fragment');
    window.location = url + '?' + $.param({property: property}) + '#' + fragment;
});
</script>
