<?php
$escape = $this->plugin('escapeHtml');

$fragment = 'item-linked';
if ('Omeka\Api\Representation\ItemSetRepresentation' === get_class($objectResource)) {
    $fragment = 'item-set-linked';
}

$firstText = ($page <= 1)
    ? $this->translate('first')
    : sprintf(
        '<a href="%s">%s</a>',
        $escape($this->url(null, [], ['query' => ['page' => 1], 'fragment' => $fragment], true)),
        $this->translate('first')
    );
$previousText = ($page <= 1)
    ? $this->translate('previous')
    : sprintf(
        '<a href="%s">%s</a>',
        $escape($this->url(null, [], ['query' => ['page' => $page - 1], 'fragment' => $fragment], true)),
        $this->translate('previous')
    );
$nextText = (($page * $perPage) >= $totalCount)
    ? $this->translate('next')
    : sprintf(
        '<a href="%s">%s</a>',
        $escape($this->url(null, [], ['query' => ['page' => $page + 1], 'fragment' => $fragment], true)),
        $this->translate('next')
    );
$lastText = (($page * $perPage) >= $totalCount)
    ? $this->translate('last')
    : sprintf(
        '<a href="%s">%s</a>',
        $escape($this->url(null, [], ['query' => ['page' => ceil($totalCount / $perPage)], 'fragment' => $fragment], true)),
        $this->translate('last')
    );
$pagination = sprintf('%s | %s | %s | %s (%s total links)', $firstText, $previousText, $nextText, $lastText, $totalCount);
?>
<?php echo $pagination; ?>

<?php foreach ($subjectValues as $term => $values): ?>
<h3><?php echo $escape($values[0]->property()->label()); ?></h3>
<?php foreach ($values as $value): ?>
<p><?php echo $value->resource()->linkPretty(); ?></p>
<?php endforeach; ?>
<?php endforeach; ?>

<?php echo $pagination; ?>
