<?php
$translate = $this->plugin('translate');
?>
<div class="media media-field-wrapper">
    <div class="media-header">
    <span class="sortable-handle"></span>
        <h4><?php echo $translate($ingester->getLabel()); ?></h4>
        <ul class="actions">
            <li>
                <?php echo $this->hyperlink('', '#', ['class' => 'o-icon-public', 'title' => $translate('Make private')]); ?>
                <input type="hidden" name="o:media[__index__][o:is_public]" value="1">
            </li>
            <li>
                <?php echo $this->hyperlink('', '#', ['class' => 'o-icon-delete remove-new-media-field', 'title' => $translate('Remove value')]); ?>
            </li>
        </ul>
    </div>
    <?php echo $this->formRow($titleValue); ?>
    <?php echo $this->formRow($titleProperty); ?>
    <?php echo $this->formRow($titleType); ?>
    <?php echo $ingester->form($this, $options); ?>
    <input type="hidden" name="o:media[__index__][o:ingester]" value="<?php echo $this->escapeHtml($ingesterName); ?>">
</div>
