<label><span class="label-text"><?php echo $this->translate('Top'); ?></span><?php echo $this->formElement($element->getTopElement()); ?></label>
<label><span class="label-text"><?php echo $this->translate('Right'); ?></span><?php echo $this->formElement($element->getRightElement()); ?></label>
<label><span class="label-text"><?php echo $this->translate('Bottom'); ?></span><?php echo $this->formElement($element->getBottomElement()); ?></label> 
<label><span class="label-text"><?php echo $this->translate('Left'); ?></span><?php echo $this->formElement($element->getLeftElement()); ?></label>
