<?php echo $this->translate('Top'); ?>
<?php echo $this->formElement($element->getTopElement()); ?>
<?php echo $this->translate('Right'); ?>
<?php echo $this->formElement($element->getRightElement()); ?>
<?php echo $this->translate('Bottom'); ?>
<?php echo $this->formElement($element->getBottomElement()); ?>
<?php echo $this->translate('Left'); ?>
<?php echo $this->formElement($element->getLeftElement()); ?>
