<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<div class="sidebar" id="page-list">
  <button type="button" class="sidebar-close o-icon-close" title="<?php echo $translate('Close'); ?>" aria-label="<?php echo $translate('Close'); ?>"></button>
  <div class="sidebar-content">
    <h3><?php echo $translate('Select Pages'); ?></h3>
    <div class="pages">
        <?php foreach ($sitePages as $sitePage): ?>
          <button class="option" type="button" value="<?php echo $escape($sitePage->id()); ?>" data-page-slug="<?php echo $escape($sitePage->slug()); ?>"><?php echo $escape($sitePage->title()); ?></button>
        <?php endforeach; ?>
    </div>
  </div>
</div>