<?php
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>
<div id="property-selector" class='selector sidebar active'>
    <?php if ($propertySelectorText) :?>
    <p><?php echo $propertySelectorText; ?></p>
    <?php else: ?>
    <p><?php echo $this->translate('Click on a property to add it to the edit panel.'); ?></p>
    <?php endif; ?>
    <input type="text" class="selector-filter" placeholder="Filter properties">
    <ul>
        <li class="show"><?php echo $escape($this->translate('All Properties')); ?> (<span class="selector-total-count"><?php echo $totalPropertyCount; ?></span>)
            <ul>
                <?php foreach ($vocabularies as $vocabulary): ?>
                <?php
                $properties = $vocabulary->properties();
                if (!$properties) {
                    // Do not render vocabularies without properties.
                    continue;
                }
                ?>
                <li class='selector-parent'
                    data-vocabulary-id="<?php echo $escapeAttr($vocabulary->id()); ?>">
                    <span><?php echo $escape($vocabulary->label()); ?></span> (<span class="selector-child-count"><?php echo $escape(count($vocabulary->properties())); ?></span>)
                    <ul>
                        <?php foreach ($properties as $property): ?>
                        <li class='selector-child'
                            data-child-search="<?php echo $escapeAttr($property->label()); ?>"
                            data-property-id="<?php echo $escapeAttr($property->id()); ?>"
                            data-property-term="<?php echo $escapeAttr($property->term()); ?>">
                            <div class="description">
                                <p class="o-icon-info"><span class="screen-reader-text"><?php echo $escape($this->translate('More Info')); ?></span></p>
                                <p class="field-comment"><?php echo $escape($property->comment()); ?></p>
                            </div>
                            <span><?php echo $escape($property->label()); ?></span>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
                <?php endforeach; ?>
            </ul>
        </li>
    </ul>
</div>
