<fieldset id='<?php echo $id; ?>' class='<?php echo $class; ?>'>

    <div class="resource-values field" id="resource-template" >
        <div class="field-meta">
            <label>Resource Template</label>
            <div class='field-description'>
                <p class="o-icon-info"><span class="screen-reader-text">More Info</span></p>
                <p>A pre-defined template for resource creation.</p>
            </div>
        </div>
        <div class="inputs">
            <?php $atts = array();
                  if (isset($item)) {
                      $resourceTemplate = $item->resourceTemplate();
                      if ($resourceTemplate) {
                          $atts = array('value' => $item->resourceTemplate()->id());
                      }
                  }
            ?>
            <?php echo $this->resourceTemplateSelect('o:resource_template[o:id]', $atts); ?>
        </div>
    </div>

    <div class="resource-values field" id="resource-class">
        <div class="field-meta">
            <label>Class</label>
            <div class='field-description'>
                <p class="o-icon-info"><span class="screen-reader-text">More Info</span></p>
                <p> A type for the resource. Different types have different default properties attached to them. </p>
            </div>
        </div>
        <div class="inputs">
            <?php $atts = array();
                  if (isset($item)) {
                      $resourceClass = $item->resourceClass();
                      if ($resourceClass) {
                          $atts = array('value' => $resourceClass->id());
                      }
                  }
            ?>
            <?php echo $this->resourceClassSelect('o:resource_class[o:id]', $atts); ?>
        </div>
    </div>
    <div id='properties'>
    </div>
<?php echo $this->propertySelector(); ?>
</fieldset>