<?php 
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>

<fieldset class="resource-values field template">
    <div class='field-meta'>
        <legend class='field-label'></legend>
        <a href="#" class="collapse o-icon-down" aria-label="Collapse"></a>
        <div class="collapsible">
            <div class='field-description'></div>
            <div class='field-term' title="Property term for development use"></div>
        </div>
    </div>
    <div class='inputs'>
        <div class="values">
            <p class="no-values">Select the first value type.</p>
        </div>
        <div class="add-values">
            <label class="add-value o-icon-add"><?php echo $this->translate('Add value'); ?></label>
            <a href="#" class="add-value button o-icon-literal"><?php echo $this->translate('Text'); ?></a>
            <a href="#" class="add-value button o-icon-resource"><?php echo $this->translate('Omeka Resource'); ?></a>
            <a href="#" class="add-value button o-icon-uri"><?php echo $this->translate('URI'); ?></a>
        </div>
    </div>
</fieldset>

<fieldset class="literal value template">
    <input type="hidden" class="property" />
    <input type='hidden' class='value-id' name='' value='' />
    
    <div class="input-header">
        <span class='restore-value'>Value to be removed</span>
        <ul class='actions'>
            <li>
                <a class='o-icon-delete remove-value' href='#' title='Remove value' aria-label='Remove value'></a>
            </li>
            <li>
                <a class='o-icon-undo restore-value' href='#' title='Undo remove value' aria-label='Undo remove value'></a>
            </li>
        </ul>
    </div>

    <legend class="o-icon-text"><?php echo $this->translate('Text value'); ?></legend>

    <label class='value-language o-icon-language' for=''><?php echo $this->translate('Language'); ?></label>
    <input class='value-language' type='text' name=''/>

    <!-- input for the property value -->
    <textarea name="" class="input-value"></textarea>
</fieldset>

<fieldset class="resource value template">
    <input type="hidden" class="property" />
    <input type='hidden' class='value-id' name='' value='' />
    
    <div class="input-header">
        <span class='restore-value'>Value to be removed</span>
        <ul class='actions'>
            <li>
                <a class='o-icon-delete remove-value' href='#' title='Remove value' aria-label='Remove value'></a>
            </li>
            <li>
                <a class='o-icon-undo restore-value' href='#' title='Undo remove value' aria-label='Undo remove value'></a>
            </li>
        </ul>
    </div>
    
    <div class="input-body">
        <legend class="o-icon-resource"><?php echo $this->translate('Omeka resource'); ?></legend>
        <span class="default"><?php echo $this->translate('No resource selected'); ?></span>
    
        <p class="selected-resource">
            <span class="o-title"></span>
            <input type="hidden" class="value" />
        </p>
    
        <a href="#item-resource-select" 
            class="o-icon-items button resource-select"
            data-sidebar-content-url="<?php echo $escapeAttr($this->url('admin/default',
                array(
                    'controller' => 'item',
                    'action'     => 'sidebar-select'
                ),
                false)); ?>"
           >Items</a>
        <a href="#itemset-resource-select" 
            class="o-icon-item-sets button resource-select"
            data-sidebar-content-url="<?php echo $escapeAttr($this->url('admin/default',
                array(
                    'controller' => 'item-set',
                    'action'     => 'sidebar-select'
                ),
                false)); ?>"
           >Item Sets</a>
    </div>
</fieldset>

<fieldset class="uri value template">
    <input type="hidden" class="property" />
    <input type='hidden' class='value-id' name='' value='' />
    
    <div class="input-header">
        <span class='restore-value'><?php echo $this->translate('Value to be removed'); ?></span>
        <ul class='actions'>
            <li>
                <a class='o-icon-delete remove-value' href='#' title='Remove value' aria-label='Remove value'></a>
            </li>
            <li>
                <a class='o-icon-undo restore-value' href='#' title='Undo remove value' aria-label='Undo remove value'></a>
            </li>
        </ul>
    </div>

    <legend class="o-icon-uri"><?php echo $this->translate('External resource'); ?></legend>
    <div class="input">
        <label class="value">Url</label>
        <input type="text" class='value' />
    </div>
    <div class="input">
        <label class="value-label">Label</label>
        <textarea class="value-label" rows="1"></textarea>
    </div>
</fieldset>
