<fieldset id='<?php echo $id; ?>' class='<?php echo $class; ?>'>
    <div class="non-properties">
        <div class="resource-values field" id="resource-template" >
            <div class="field-meta">
                <label class='field-label'>Resource Template</label>
                <a href="#" class="expand o-icon-right" aria-title="Expand"></a>
                <div class='field-description'>A pre-defined template for resource creation.</div>
            </div>
            <div class="inputs">
                <?php $atts = array();
                      if (isset($resource)) {
                          $resourceTemplate = $resource->resourceTemplate();
                          if ($resourceTemplate) {
                              $atts = array('value' => $resource->resourceTemplate()->id());
                          }
                      }
                ?>
                <?php $select = $this->resourceTemplateSelect('o:resource_template[o:id]', $atts); ?>
                <?php if ($select) {
                          echo $select;
                      } else {
                          $resourceTemplatesUrl = $this->url('admin') . '/resource_template';
                          echo "<span class=\"no-templates\">No resource templates available</span>";
                      }
    
                      ?>
            </div>
        </div>
    
        <div class="resource-values field" id="resource-class">
            <div class="field-meta">
                <label class="field-label">Class</label>
                <a href="#" class="expand o-icon-right" aria-title="Expand"></a>
                <div class='field-description'> A type for the resource. Different types have different default properties attached to them. </div>
            </div>
            <div class="inputs">
                <?php $atts = array();
                      if (isset($resource)) {
                          $resourceClass = $resource->resourceClass();
                          if ($resourceClass) {
                              $atts = array('value' => $resourceClass->id());
                          }
                      }
                ?>
                <?php echo $this->resourceClassSelect('o:resource_class[o:id]', $atts); ?>
            </div>
        </div>
    </div>
    <div id='properties'>
    </div>
<?php 
    if (isset($propertySelectorText)) {
        echo $this->propertySelector($propertySelectorText);
    } else {
        echo $this->propertySelector();
    }
?>
</fieldset>