<?php
$resourceTemplateSelect = $form->get('o:resource_template[o:id]');
$resourceClassSelect = $form->get('o:resource_class[o:id]');
if (isset($resource)) {
    if ($resourceTemplate = $resource->resourceTemplate()) {
        $resourceTemplateSelect->setValue($resourceTemplate->id());
    }
    if ($resourceClass = $resource->resourceClass()) {
        $resourceClassSelect->setValue($resourceClass->id());
    }
} else {
    // Set the logged in user's default template when adding a resource.
    $resourceTemplateSelect->setValue($this->userSetting('default_resource_template'));
}
?>
<fieldset id="resource-values"
    class="section active"
    aria-labelledby="resource-values-label"
    data-resource-id="<?php echo isset($resource) ? $resource->id() : ''; ?>">
    <div class="non-properties">
        <?php if ($resourceTemplateSelect->getValueOptions()): ?>
        <?php echo $this->formRow($resourceTemplateSelect); ?>
        <?php endif; ?>
        <?php echo $this->formRow($resourceClassSelect); ?>
    </div>
    <div id="properties"></div>
    <?php echo $this->propertySelector(); ?>
    <button id="property-selector-button" class="mobile-only" data-watch-target="#properties"><?php echo $this->translate('Add property'); ?></button>
    <?php echo $this->partial('common/resource-select-sidebar'); ?>
</fieldset>
