<?php
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>
<?php foreach ($values as $term => $property): ?>
<div class="property">
    <h4><?php echo $escape($property['property']->label()); ?></h4>
    <?php foreach ($property['values'] as $value): ?>
        <?php if ('resource' == $value->type()): ?>
        <div class="value <?php echo $escapeAttr($value->resource()->resourceName()); ?>"><?php echo $value; ?></div>
        <?php else: ?>
        <div class="value"><?php echo $value; ?></div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<?php endforeach; ?>
