<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->dataType()->prepareForm();

$defaultDataTypes = $this->setting('resource_default_datatypes') ?: ['literal', 'resource', 'uri'];

$icons = [
    'resource:item' => 'items',
    'resource:itemset' => 'item-sets',
    'resource:media' => 'media',
];
?>

<div class="resource-values field template" data-template-id="" role="group">
    <div class="field-meta">
        <div class="field-label"></div>
        <a href="#" class="collapse" aria-label="<?php echo $escape($translate('Collapse')); ?>"></a>
        <div class="collapsible">
            <div class="field-description"></div>
            <div class="field-term" title="<?php echo $escape($translate('Property term for development use')); ?>"></div>
        </div>
    </div>
    <div class="inputs">
        <div class="values">
            <p class="no-values"><?php echo $translate('Select the first value type.'); ?></p>
        </div>
        <div class="add-values default-selector">
            <label class="o-icon-add"><?php echo $translate('Add value'); ?></label>
            <?php foreach ($defaultDataTypes as $dataType): ?>
            <?php $typeData = $this->dataType()->getDataType($dataType); ?>
            <?php if (!$typeData) continue; ?>
            <?php $icon = isset($icons[$dataType]) ? $icons[$dataType] : strtok($dataType, ':'); ?>
            <a href="#" class="add-value button o-icon-<?= $icon ?>" data-type="<?= $dataType ?>"><?php echo $dataType === 'resource' ? $translate('Omeka resource') : $translate($typeData->getLabel()); ?></a>
            <?php endforeach; ?>
        </div>
        <div class="add-values multiple-selector" style="display:none">
            <label class="o-icon-add"><?php echo $translate('Add value'); ?></label>
        </div>
        <div class="add-values single-selector" style="display:none">
            <label class="o-icon-add"><?php echo $translate('Add value'); ?></label>
            <a href="#" class="add-value button"><?php echo $translate('Add value'); ?></a>
        </div>
    </div>
</div>

<?php echo $this->dataType()->getTemplates(); ?>
