<div id="select-resource" class='sidebar'>
    <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text">Close Me</span></a>
    <div class="sidebar-content">
    </div>
    <div id="resource-details" class="sidebar">
        <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text">Close Me</span></a>

        <div class='sidebar-content'>
            <div id="resource-details-content">
            </div>
        </div>
        <div id="select-item">
            <a href="#" class="button">Select resource</a>
        </div>
    </div>
</div>