<?php
$translate = $this->plugin('translate');
?>
<?php $this->headScript()->appendFile($this->assetUrl('js/resource-selector.js', 'Omeka')); ?>
<div id="select-resource" class='sidebar' tabindex="-1">
    <div class="sidebar-content">
    </div>
</div>
<div id="resource-details" class="sidebar">
    <div id="resource-details-main" class="confirm-main">
        <button type="button" class="sidebar-close o-icon-close" title="<?php echo $translate('Close'); ?>" aria-label="<?php echo $translate('Close'); ?>"></button>

        <div class='sidebar-content'>
            <div id="resource-details-content">
            </div>
        </div>
    </div>
    <div id="select-item" class="confirm-panel">
        <button type="button" class="button"><?php echo $translate('Select resource'); ?></button>
    </div>
</div>
