<?php 
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
$formPropertyInputs = $this->plugin('formPropertyInputs');
$formErrors = $this->plugin('formElementErrors');
?>

<?php foreach ($form->getFieldsets() as $term => $fieldset): ?>
    <div class="resource-values field" data-property-qname='<?php echo $fieldset->getOption('data-property-qname'); ?>' data-property-id='<?php echo $fieldset->getOption('data-property-id'); ?>'>

        <div class="field-actions">
            <a href="#" class="add-value button o-icon-add"><span class="screen-reader-text">Add Value</span></a>
        </div>
        <div class='field-meta'>
        <?php echo $formLabel($fieldset); ?>
            <div class='field-description'>
                <p class="o-icon-info"><span class="screen-reader-text">More Info</span></p>
                <p><?php  echo $fieldset->getOption('comment'); ?></p>
            </div>
        </div>

        <div class='inputs'>
            <?php foreach ($fieldset->getElements() as $name => $element): ?>
                <div class='value'>
                <?php echo $formPropertyInputs($element); ?>
                <button class="remove-value">Remove value</button>
                </div>
            <?php endforeach; ?>
        </div>
        <?php
        echo $formErrors($element);
        ?>
    </div>
<?php endforeach; ?>
