<?php
$thumbnailId = $showThumbnail ? $site->thumbnailId() : null;
$summary = $showSummary ? $site->summary() : null;
?>
<div class="site">
    <?php if ($thumbnailId):
    $asset = $this->api()->read('assets', $thumbnailId)->getContent(); ?>
    <p class="site-thumbnail"><?php echo $this->thumbnail($asset, 'square', ['class' => 'site-thumbnail-image']); ?></p>
    <?php endif; ?>
    <?php echo $this->hyperlink($site->title(), $site->siteUrl(), ['class' => 'site-link']); ?>
    <?php if ($summary): ?>
    <p class="site-summary"><?php echo nl2br($this->escapeHtml($summary)); ?></p>
    <?php endif; ?>
</div>
