<?php
if ('sorted-asc' == $class) {
    $title = $this->translate('Switch to descending order');
} elseif ('sorted-desc' == $class) {
    $title = $this->translate('Switch to ascending order');
} else {
    $title = sprintf($this->translate('Sort by %s'), $label);
}
?>
<a href="<?php echo $this->escapeHtml($url); ?>"
    class="<?php echo $this->escapeHtml($class); ?>"
    title="<?php echo $this->escapeHtml($title); ?>">
    <?php echo $this->escapeHtml($label); ?>
</a>
