<?php
if ('sorted-asc' == $class) {
    $title = $this->translate('Switch to descending order');
} elseif ('sorted-desc' == $class) {
    $title = $this->translate('Switch to ascending order');
} else {
    $title = $this->translate("Sort by $this->escapeHtml($label)");
}
?>
<a href="<?php echo $this->escapeHtmlAttr($url); ?>"
    class="<?php echo $this->escapeHtmlAttr($class); ?>"
    title="<?php echo $this->escapeHtmlAttr($title); ?>">
    <?php echo $this->escapeHtml($label); ?>
</a>
