<?php $escape = $this->plugin('escapeHtml'); ?>
<div id="user-bar">
    <span class="site-title">
        <a href="<?php echo $site->adminUrl('show'); ?>"><?php echo $site->title(); ?></a>
        <?php if ($site->userIsAllowed('update')): ?>
        <a href="<?php echo $site->adminUrl(); ?>" class="o-icon-edit" aria-label="<?php echo $this->translate('Edit'); ?>"></a>
        <?php endif; ?>
    </span>
    <span class="user-id">
    <?php 
    echo sprintf($this->translate('Signed in as %s'),  '<a href="' . $this->url('admin/id', [
        'controller' => 'user',
        'id' => $this->identity()->getId(),
    ]) . '">' . $escape($this->identity()->getName()) . '</a>'); 
    ?>
    </span>
    <span class="logout"><a href="<?php echo $this->url('logout'); ?>"><?php echo $this->translate('Logout'); ?></a></span>
</div>
