<?php
$dataTypeName = (strpos('resource', $dataType->getName()) !== false) ? 'resource' : $dataType->getName();
?>
<div class="value-annotation">
    <h4 class="value-annotation-heading"></h4>
    <div class="value" data-data-type="<?php echo $dataTypeName; ?>" data-data-type-label="<?php echo $dataType->getLabel(); ?>" data-data-type-icon="" role="group">
        <?php echo $dataType->valueAnnotationForm($this); ?>
        <div class="input-footer">
            <span class="restore-value"><?php echo $this->translate('Value to be removed'); ?></span>
            <ul class="actions">
                <li><?php echo $this->hyperlink('', '#', ['class' => 'o-icon-delete value-annotation-remove', 'title' => $this->translate('Remove value'), 'aria-label' => $this->translate('Remove value')]); ?></li>
                <li><?php echo $this->hyperlink('', '#', ['class' => 'o-icon-undo value-annotation-restore', 'title' => $this->translate('Restore value'), 'aria-label' => $this->translate('Restore value'), 'style' => 'display: none;']); ?></li>
                <li><?php echo $this->hyperlink('', '#', ['class' => 'o-icon-public value-annotation-visibility', 'title' => $this->translate('Make public'), 'aria-label' => $this->translate('Make public')]); ?></li>
            </ul>
            <input type="hidden" class="is_public" data-value-key="is_public">
            <input type="hidden" class="data_type" data-value-key="type" value="<?php echo $this->escapeHtml($dataType->getName()); ?>">
            <input type="hidden" class="property_id" data-value-key="property_id">
            <input type="hidden" class="property_term" data-value-key="property_term">
        </div>
    </div>
</div>
