<?php
$this->htmlElement('body')->appendAttribute('class', 'sites add');
$form->prepare();
?>
<h1><?php echo $this->escapeHtml($this->translate('Add Site')); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->escapeHtml($this->translate('Submit')); ?></button>
</div>
<?php echo $this->formElements($form); ?>
<?php echo $this->form()->closeTag(); ?>
