<?php
$this->htmlElement('body')->appendAttribute('class', 'sites add');
$form->prepare();
?>
<h1><?php echo $this->escapeHtml(sprintf($this->translate('Edit Site “%s”'), $site->title())); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->escapeHtml($this->translate('Save changes')); ?></button>
</div>
<?php echo $this->formElements($form); ?>
<?php echo $this->form()->closeTag(); ?>
