<?php
$this->htmlElement('body')->appendAttribute('class', 'sites show');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>
<h1><?php echo sprintf($this->translate('Site: “%s”'), $escape($site->title())); ?></h1>
<div id="page-actions">
    <a class="button" href="<?php echo $escapeAttr($site->url('edit')); ?>">
        <?php echo $this->translate('Edit Site'); ?>
    </a>
</div>

<div class="property">
    <h4><?php echo $this->translate('Slug'); ?></h4>
    <div class="value"><?php echo $escape($site->slug()); ?></div>
</div>
<div class="property">
    <h4><?php echo $this->translate('Theme'); ?></h4>
    <div class="value"><?php echo $escape($site->theme()); ?></div>
</div>
