<?php
$title = $this->setting('installation_title', 'Omeka S');
echo $this->pageTitle($this->translate('Admin Dashboard'));
?>

<div id="dashboard">
    <p><?php echo sprintf($this->translate('Welcome to the %s admin dashboard!'), $title); ?></p>
    <div id="manage-resources" class="panel">
        <h2><?php echo $this->translate('Manage Resources'); ?></h2>
        <div class="items resource row">
            <?php echo $this->hyperlink($this->translate(sprintf('Items (%s)', $itemCount)), $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'])); ?>
            <?php echo $this->hyperlink('', $this->url('admin/default', ['controller' => 'item', 'action' => 'add']), ['class' => 'add button', 'title' => $this->translate('Add new item')]); ?>
        </div>
        <div class="item-sets resource row">
            <?php echo $this->hyperlink($this->translate(sprintf('Item sets (%s)', $itemSetCount)), $this->url('admin/default', ['controller' => 'item-set', 'action' => 'browse'])); ?>
            <?php echo $this->hyperlink('', $this->url('admin/default', ['controller' => 'item-set', 'action' => 'add']), ['class' => 'add button', 'title' => $this->translate('Add new item set')]); ?>
        </div>
        <div class="vocabularies resource row">
            <?php echo $this->hyperlink($this->translate(sprintf('Vocabularies (%s)', $vocabularyCount)), $this->url('admin/default', ['controller' => 'vocabulary', 'action' => 'browse'])); ?>
            <?php echo $this->hyperlink('', $this->url('admin/default', ['controller' => 'vocabulary', 'action' => 'import']), ['class' => 'add button', 'title' => $this->translate('Import new vocabulary')]); ?>
        </div>
        <div class="resource-templates resource row">
            <?php echo $this->hyperlink($this->translate(sprintf('Resource Templates (%s)', $resourceTemplateCount)), $this->url('admin/default', ['controller' => 'resource-template', 'action' => 'browse'])); ?>
            <?php echo $this->hyperlink('', $this->url('admin/default', ['controller' => 'resource-template', 'action' => 'add']), ['class' => 'add button', 'title' => $this->translate('Add new resource template')]); ?>
        </div>
        <?php $this->trigger('view.manage-resources.after'); ?>
    </div>

    <div id="manage-sites" class="panel">
        <h2><?php echo $this->translate('Manage Sites'); ?></h2>
        <?php foreach ($sites as $site): ?>
        <div class="site row">
            <span class="site-name"><a href="<?php echo $site->siteUrl(); ?>"><?php echo $site->title(); ?></a></span>
            <span class="site-edit"><a href="<?php echo $site->adminUrl(); ?>" class="o-icon-edit button" title="<?php echo $this->translate('Edit'); ?>"></a></span>
        </div>
        <?php endforeach; ?>
        <?php echo $this->hyperlink($this->translate('Add site'), $this->url('admin/site/add'), ['class' => 'add button']); ?>
    </div>
    <?php $this->trigger('view.manage-sites.after'); ?>

</div>

<?php $this->trigger('view.browse.after'); ?>
