<?php
return [
    'session' => [
        'config' => [],
        'save_handler' => null,
    ],
    'listeners' => [
        'ModuleRouteListener',
        'Omeka\MvcExceptionListener',
        'Omeka\MvcListeners',
    ],
    'view_manager' => [
        'display_not_found_reason' => true,
        'display_exceptions' => true,
        'doctype' => 'HTML5',
        'not_found_template' => 'error/404',
        'exception_template' => 'error/index',
        'template_path_stack' => [
            OMEKA_PATH . '/application/view',
        ],
        'strategies' => [
            'Omeka\ViewApiJsonStrategy',
        ],
    ],
    'assets' => [
        'use_externals' => true,
        'externals' => [
            'Omeka' => [
                'vendor/jquery/jquery.min.js' => '//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js',
            ],
        ],
    ],
    'permissions' => [
        'acl_resources' => [
            'Omeka\Module\Manager',
        ],
    ],
    'temp_dir' => sys_get_temp_dir(),
    'file_store' => [
        'local' => [
            'base_path' => null,
            'base_uri' => null,
        ],
    ],
    'entity_manager' => [
        'is_dev_mode' => false,
        'mapping_classes_paths' => [
            OMEKA_PATH . '/application/src/Entity',
        ],
        'resource_discriminator_map' => [
            'Omeka\Entity\Item' => 'Omeka\Entity\Item',
            'Omeka\Entity\Media' => 'Omeka\Entity\Media',
            'Omeka\Entity\ItemSet' => 'Omeka\Entity\ItemSet',
        ],
        'filters' => [
            'resource_visibility' => 'Omeka\Db\Filter\ResourceVisibilityFilter',
        ],
        'functions' => [
             'datetime' => [
                'convert_tz' => 'DoctrineExtensions\Query\Mysql\ConvertTz',
                'date' => 'DoctrineExtensions\Query\Mysql\Date',
                'date_format' => 'DoctrineExtensions\Query\Mysql\DateFormat',
                'dateadd' => 'DoctrineExtensions\Query\Mysql\DateAdd',
                'datesub' => 'DoctrineExtensions\Query\Mysql\DateSub',
                'datediff' => 'DoctrineExtensions\Query\Mysql\DateDiff',
                'day' => 'DoctrineExtensions\Query\Mysql\Day',
                'dayname' => 'DoctrineExtensions\Query\Mysql\DayName',
                'dayofweek' => 'DoctrineExtensions\Query\Mysql\DayOfWeek',
                'dayofyear' => 'DoctrineExtensions\Query\Mysql\DayOfYear',
                'div' => 'DoctrineExtensions\Query\Mysql\Div',
                'from_unixtime' => 'DoctrineExtensions\Query\Mysql\FromUnixtime',
                'hour' => 'DoctrineExtensions\Query\Mysql\Hour',
                'last_day' => 'DoctrineExtensions\Query\Mysql\LastDay',
                'minute' => 'DoctrineExtensions\Query\Mysql\Minute',
                'now' => 'DoctrineExtensions\Query\Mysql\Now',
                'month' => 'DoctrineExtensions\Query\Mysql\Month',
                'monthname' => 'DoctrineExtensions\Query\Mysql\MonthName',
                'second' => 'DoctrineExtensions\Query\Mysql\Second',
                'strtodate' => 'DoctrineExtensions\Query\Mysql\StrToDate',
                'time' => 'DoctrineExtensions\Query\Mysql\Time',
                'timediff' => 'DoctrineExtensions\Query\Mysql\TimeDiff',
                'timestampadd' => 'DoctrineExtensions\Query\Mysql\TimestampAdd',
                'timestampdiff' => 'DoctrineExtensions\Query\Mysql\TimestampDiff',
                'timetosec' => 'DoctrineExtensions\Query\Mysql\TimeToSec',
                'week' => 'DoctrineExtensions\Query\Mysql\Week',
                'weekday' => 'DoctrineExtensions\Query\Mysql\WeekDay',
                'year' => 'DoctrineExtensions\Query\Mysql\Year',
                'yearweek' => 'DoctrineExtensions\Query\Mysql\YearWeek',
                'unix_timestamp' => 'DoctrineExtensions\Query\Mysql\UnixTimestamp',
            ],
            'numeric' => [
                'acos' => 'DoctrineExtensions\Query\Mysql\Acos',
                'asin' => 'DoctrineExtensions\Query\Mysql\Asin',
                'atan2' => 'DoctrineExtensions\Query\Mysql\Atan2',
                'atan' => 'DoctrineExtensions\Query\Mysql\Atan',
                'bit_count' => 'DoctrineExtensions\Query\Mysql\BitCount',
                'bit_xor' => 'DoctrineExtensions\Query\Mysql\BitXor',
                'ceil' => 'DoctrineExtensions\Query\Mysql\Ceil',
                'cos' => 'DoctrineExtensions\Query\Mysql\Cos',
                'cot' => 'DoctrineExtensions\Query\Mysql\Cot',
                'floor' => 'DoctrineExtensions\Query\Mysql\Floor',
                'pi' => 'DoctrineExtensions\Query\Mysql\Pi',
                'power' => 'DoctrineExtensions\Query\Mysql\Power',
                'quarter' => 'DoctrineExtensions\Query\Mysql\Quarter',
                'rand' => 'DoctrineExtensions\Query\Mysql\Rand',
                'round' => 'DoctrineExtensions\Query\Mysql\Round',
                'stddev' => 'DoctrineExtensions\Query\Mysql\StdDev',
                'sin' => 'DoctrineExtensions\Query\Mysql\Sin',
                'std' => 'DoctrineExtensions\Query\Mysql\Std',
                'tan' => 'DoctrineExtensions\Query\Mysql\Tan',
            ],
            'string' => [
                'ascii' => 'DoctrineExtensions\Query\Mysql\Ascii',
                'binary' => 'DoctrineExtensions\Query\Mysql\Binary',
                'char_length' => 'DoctrineExtensions\Query\Mysql\CharLength',
                'concat_ws' => 'DoctrineExtensions\Query\Mysql\ConcatWs',
                'countif' => 'DoctrineExtensions\Query\Mysql\CountIf',
                'crc32' => 'DoctrineExtensions\Query\Mysql\Crc32',
                'degrees' => 'DoctrineExtensions\Query\Mysql\Degrees',
                'field' => 'DoctrineExtensions\Query\Mysql\Field',
                'find_in_set' => 'DoctrineExtensions\Query\Mysql\FindInSet',
                'greatest' => 'DoctrineExtensions\Query\Mysql\Greatest',
                'group_concat' => 'DoctrineExtensions\Query\Mysql\GroupConcat',
                'ifelse' => 'DoctrineExtensions\Query\Mysql\IfElse',
                'ifnull' => 'DoctrineExtensions\Query\Mysql\IfNull',
                'least' => 'DoctrineExtensions\Query\Mysql\Least',
                'lpad' => 'DoctrineExtensions\Query\Mysql\Lpad',
                'match' => 'DoctrineExtensions\Query\Mysql\MatchAgainst',
                'md5' => 'DoctrineExtensions\Query\Mysql\Md5',
                'nullif' => 'DoctrineExtensions\Query\Mysql\NullIf',
                'radians' => 'DoctrineExtensions\Query\Mysql\Radians',
                'regexp' => 'DoctrineExtensions\Query\Mysql\Regexp',
                'replace' => 'DoctrineExtensions\Query\Mysql\Replace',
                'rpad' => 'DoctrineExtensions\Query\Mysql\Rpad',
                'sha1' => 'DoctrineExtensions\Query\Mysql\Sha1',
                'sha2' => 'DoctrineExtensions\Query\Mysql\Sha2',
                'soundex' => 'DoctrineExtensions\Query\Mysql\Soundex',
                'substring_index' => 'DoctrineExtensions\Query\Mysql\SubstringIndex',
                'uuid_short' => 'DoctrineExtensions\Query\Mysql\UuidShort',
                'hex' => 'DoctrineExtensions\Query\Mysql\Hex',
                'unhex' => 'DoctrineExtensions\Query\Mysql\Unhex',
            ],
        ],
        'proxy_paths' => [
            OMEKA_PATH . '/application/data/doctrine-proxies',
        ],
    ],
    'installer' => [
        'pre_tasks' => [
            'Omeka\Installation\Task\CheckEnvironmentTask',
            'Omeka\Installation\Task\CheckDirPermissionsTask',
            'Omeka\Installation\Task\CheckDbConfigurationTask',
        ],
        'tasks' => [
            'Omeka\Installation\Task\DestroySessionTask',
            'Omeka\Installation\Task\ClearCacheTask',
            'Omeka\Installation\Task\InstallSchemaTask',
            'Omeka\Installation\Task\RecordMigrationsTask',
            'Omeka\Installation\Task\InstallDefaultVocabulariesTask',
            'Omeka\Installation\Task\InstallDefaultTemplatesTask',
            'Omeka\Installation\Task\CreateFirstUserTask',
            'Omeka\Installation\Task\AddDefaultSettingsTask',
        ],
    ],
    'translator' => [
        'locale' => 'en_US',
        'translation_file_patterns' => [
            [
                'type' => 'gettext',
                'base_dir' => OMEKA_PATH . '/application/language',
                'pattern' => '%s.mo',
                'text_domain' => null,
            ],
        ],
    ],
    'logger' => [
        'log' => false,
        'path' => OMEKA_PATH . '/logs/application.log',
        'priority' => \Zend\Log\Logger::NOTICE,
    ],
    'http_client' => [
        'adapter' => 'Zend\Http\Client\Adapter\Socket',
        'sslcapath' => null,
        'sslcafile' => null,
    ],
    'cli' => [
        'execute_strategy' => 'exec',
        'phpcli_path' => null,
    ],
    'thumbnails' => [
        'types' => [
            'large' => [
                'strategy' => 'default',
                'constraint' => 800,
                'options' => [],
            ],
            'medium' => [
                'strategy' => 'default',
                'constraint' => 400,
                'options' => [],
            ],
            'square' => [
                'strategy' => 'square',
                'constraint' => 200,
                'options' => [
                    'gravity' => 'center',
                ],
            ],
        ],
        'fallbacks' => [
            'default' => ['thumbnails/default.png', 'Omeka'],
            'fallbacks' => [
                'image' => ['thumbnails/image.png', 'Omeka'],
                'video' => ['thumbnails/video.png', 'Omeka'],
                'audio' => ['thumbnails/audio.png', 'Omeka'],
            ],
        ],
        'thumbnailer_options' => [
            'imagemagick_dir' => null,
            'page' => 0,
        ],
    ],
    'service_manager' => [
        'abstract_factories' => [
            'Zend\Navigation\Service\NavigationAbstractServiceFactory',
        ],
        'factories' => [
            'Omeka\Acl' => 'Omeka\Service\AclFactory',
            'Omeka\ApiAdapterManager' => 'Omeka\Service\ApiAdapterManagerFactory',
            'Omeka\ApiManager' => 'Omeka\Service\ApiManagerFactory',
            'Omeka\AuthenticationService' => 'Omeka\Service\AuthenticationServiceFactory',
            'Omeka\EntityManager' => 'Omeka\Service\EntityManagerFactory',
            'Omeka\Installer' => 'Omeka\Service\InstallerFactory',
            'Omeka\Logger' => 'Omeka\Service\LoggerFactory',
            'Omeka\MigrationManager' => 'Omeka\Service\MigrationManagerFactory',
            'Omeka\ViewApiJsonStrategy' => 'Omeka\Service\ViewApiJsonStrategyFactory',
            'Omeka\HttpClient' => 'Omeka\Service\HttpClientFactory',
            'Omeka\Mailer' => 'Omeka\Service\MailerFactory',
            'Omeka\HtmlPurifier' => 'Omeka\Service\HtmlPurifierFactory',
            'Omeka\BlockLayoutManager' => 'Omeka\Service\BlockLayoutManagerFactory',
            'Omeka\DataTypeManager' => 'Omeka\Service\DataTypeManagerFactory',
            'Omeka\Cli' => 'Omeka\Service\CliFactory',
            'Omeka\Paginator' => 'Omeka\Service\PaginatorFactory',
            'Omeka\RdfImporter' => 'Omeka\Service\RdfImporterFactory',
            'Omeka\Site\ThemeManager' => 'Omeka\Service\ThemeManagerFactory',
            'Omeka\Site\NavigationLinkManager' => 'Omeka\Service\NavigationLinkManagerFactory',
            'Omeka\Site\NavigationTranslator' => 'Omeka\Service\SiteNavigationTranslatorFactory',
            'Omeka\File\Thumbnailer\ImageMagick' => 'Omeka\Service\File\Thumbnailer\ImageMagickFactory',
            'Omeka\File\Thumbnailer\Gd' => 'Omeka\Service\File\Thumbnailer\GdFactory',
            'Omeka\File\Thumbnailer\Imagick' => 'Omeka\Service\File\Thumbnailer\ImagickFactory',
            'Omeka\File\Store\Local' => 'Omeka\Service\File\Store\LocalFactory',
            'Omeka\File\MediaTypeMap' => 'Omeka\Service\MediaTypeMapFactory',
            'Omeka\File\ThumbnailManager' => 'Omeka\Service\File\ThumbnailManagerFactory',
            'Omeka\File\TempFileFactory' => 'Omeka\Service\File\TempFileFactoryFactory',
            'Omeka\File\Downloader' => 'Omeka\Service\File\DownloaderFactory',
            'Omeka\File\Uploader' => 'Omeka\Service\File\UploaderFactory',
            'Omeka\File\Validator' => 'Omeka\Service\File\ValidatorFactory',
            'Omeka\Settings' => 'Omeka\Service\Settings\SettingsFactory',
            'Omeka\Settings\Site' => 'Omeka\Service\Settings\SiteSettingsFactory',
            'Omeka\Settings\User' => 'Omeka\Service\Settings\UserSettingsFactory',
            'Omeka\Job\Dispatcher' => 'Omeka\Service\Job\DispatcherFactory',
            'Omeka\Job\DispatchStrategy\PhpCli' => 'Omeka\Service\Job\DispatchStrategy\PhpCliFactory',
            'Omeka\Job\DispatchStrategy\Synchronous' => 'Omeka\Service\Job\DispatchStrategy\SynchronousFactory',
            'Omeka\Media\Ingester\Manager' => 'Omeka\Service\Media\Ingester\ManagerFactory',
            'Omeka\Media\Renderer\Manager' => 'Omeka\Service\Media\Renderer\ManagerFactory',
            'Omeka\Media\FileRenderer\Manager' => 'Omeka\Service\Media\FileRenderer\ManagerFactory',
        ],
        'invokables' => [
            'ModuleRouteListener' => 'Zend\Mvc\ModuleRouteListener',
            'Omeka\MvcExceptionListener' => 'Omeka\Mvc\ExceptionListener',
            'Omeka\MvcListeners' => 'Omeka\Mvc\MvcListeners',
            'Omeka\ViewApiJsonRenderer' => 'Omeka\View\Renderer\ApiJsonRenderer',
        ],
        'delegators' => [
            'Zend\I18n\Translator\TranslatorInterface' => [
                'Omeka\Service\Delegator\TranslatorDelegatorFactory',
            ],
        ],
        'aliases' => [
            'Omeka\File\Store' => 'Omeka\File\Store\Local',
            'Omeka\File\Thumbnailer' => 'Omeka\File\Thumbnailer\ImageMagick',
            'Omeka\Job\DispatchStrategy' => 'Omeka\Job\DispatchStrategy\PhpCli',
            'Omeka\JobDispatcher' => 'Omeka\Job\Dispatcher',
            'Zend\Authentication\AuthenticationService' => 'Omeka\AuthenticationService',
        ],
        'shared' => [
            'Omeka\Paginator' => false,
            'Omeka\HttpClient' => false,
        ],
    ],
    'controllers' => [
        'invokables' => [
            'Omeka\Controller\Index' => 'Omeka\Controller\IndexController',
            'Omeka\Controller\Maintenance' => 'Omeka\Controller\MaintenanceController',
            'Omeka\Controller\Site\Index' => 'Omeka\Controller\Site\IndexController',
            'Omeka\Controller\Site\Item' => 'Omeka\Controller\Site\ItemController',
            'Omeka\Controller\Site\ItemSet' => 'Omeka\Controller\Site\ItemSetController',
            'Omeka\Controller\Site\Media' => 'Omeka\Controller\Site\MediaController',
            'Omeka\Controller\Site\Page' => 'Omeka\Controller\Site\PageController',
            'Omeka\Controller\Admin\Asset' => 'Omeka\Controller\Admin\AssetController',
            'Omeka\Controller\Admin\Index' => 'Omeka\Controller\Admin\IndexController',
            'Omeka\Controller\Admin\Property' => 'Omeka\Controller\Admin\PropertyController',
            'Omeka\Controller\Admin\ResourceClass' => 'Omeka\Controller\Admin\ResourceClassController',
            'Omeka\Controller\Admin\Media' => 'Omeka\Controller\Admin\MediaController',
            'Omeka\Controller\Admin\Setting' => 'Omeka\Controller\Admin\SettingController',
            'Omeka\Controller\SiteAdmin\Page' => 'Omeka\Controller\SiteAdmin\PageController',
        ],
        'factories' => [
            'Omeka\Controller\Login' => 'Omeka\Service\Controller\LoginControllerFactory',
            'Omeka\Controller\Api' => 'Omeka\Service\Controller\ApiControllerFactory',
            'Omeka\Controller\Install' => 'Omeka\Service\Controller\InstallControllerFactory',
            'Omeka\Controller\Migrate' => 'Omeka\Service\Controller\MigrateControllerFactory',
            'Omeka\Controller\Admin\Module' => 'Omeka\Service\Controller\Admin\ModuleControllerFactory',
            'Omeka\Controller\Admin\User' => 'Omeka\Service\Controller\Admin\UserControllerFactory',
            'Omeka\Controller\Admin\Job' => 'Omeka\Service\Controller\Admin\JobControllerFactory',
            'Omeka\Controller\Admin\ResourceTemplate' => 'Omeka\Service\Controller\Admin\ResourceTemplateControllerFactory',
            'Omeka\Controller\Admin\SystemInfo' => 'Omeka\Service\Controller\Admin\SystemInfoControllerFactory',
            'Omeka\Controller\Admin\Vocabulary' => 'Omeka\Service\Controller\Admin\VocabularyControllerFactory',
            'Omeka\Controller\Admin\Item' => 'Omeka\Service\Controller\Admin\ItemControllerFactory',
            'Omeka\Controller\Admin\ItemSet' => 'Omeka\Service\Controller\Admin\ItemSetControllerFactory',
            'Omeka\Controller\SiteAdmin\Index' => 'Omeka\Service\Controller\SiteAdmin\IndexControllerFactory',
        ],
    ],
    'controller_plugins' => [
        'invokables' => [
            'messenger' => 'Omeka\Mvc\Controller\Plugin\Messenger',
            'setBrowseDefaults' => 'Omeka\Mvc\Controller\Plugin\SetBrowseDefaults',
            'currentSite' => 'Omeka\Mvc\Controller\Plugin\CurrentSite',
        ],
        'factories' => [
            'api' => 'Omeka\Service\ControllerPlugin\ApiFactory',
            'jobDispatcher' => 'Omeka\Service\ControllerPlugin\JobDispatcherFactory',
            'logger' => 'Omeka\Service\ControllerPlugin\LoggerFactory',
            'paginator' => 'Omeka\Service\ControllerPlugin\PaginatorFactory',
            'translate' => 'Omeka\Service\ControllerPlugin\TranslateFactory',
            'getForm' => 'Omeka\Service\ControllerPlugin\GetFormFactory',
            'userIsAllowed' => 'Omeka\Service\ControllerPlugin\UserIsAllowedFactory',
            'mailer' => 'Omeka\Service\ControllerPlugin\MailerFactory',
            'settings' => 'Omeka\Service\ControllerPlugin\SettingsFactory',
            'siteSettings' => 'Omeka\Service\ControllerPlugin\SiteSettingsFactory',
            'userSettings' => 'Omeka\Service\ControllerPlugin\UserSettingsFactory',
            'status' => 'Omeka\Service\ControllerPlugin\StatusFactory',
            'viewHelpers' => 'Omeka\Service\ControllerPlugin\ViewHelpersFactory',
        ],
    ],
    'api_adapters' => [
        'invokables' => [
            'users' => 'Omeka\Api\Adapter\UserAdapter',
            'vocabularies' => 'Omeka\Api\Adapter\VocabularyAdapter',
            'resource_classes' => 'Omeka\Api\Adapter\ResourceClassAdapter',
            'resource_templates' => 'Omeka\Api\Adapter\ResourceTemplateAdapter',
            'properties' => 'Omeka\Api\Adapter\PropertyAdapter',
            'items' => 'Omeka\Api\Adapter\ItemAdapter',
            'media' => 'Omeka\Api\Adapter\MediaAdapter',
            'item_sets' => 'Omeka\Api\Adapter\ItemSetAdapter',
            'modules' => 'Omeka\Api\Adapter\ModuleAdapter',
            'sites' => 'Omeka\Api\Adapter\SiteAdapter',
            'site_pages' => 'Omeka\Api\Adapter\SitePageAdapter',
            'site_item_sets' => 'Omeka\Api\Adapter\SiteItemSetAdapter',
            'jobs' => 'Omeka\Api\Adapter\JobAdapter',
            'resources' => 'Omeka\Api\Adapter\ResourceAdapter',
            'assets' => 'Omeka\Api\Adapter\AssetAdapter',
        ],
    ],
    'view_helpers' => [
        'invokables' => [
            'pageTitle' => 'Omeka\View\Helper\PageTitle',
            'htmlElement' => 'Omeka\View\Helper\HtmlElement',
            'hyperlink' => 'Omeka\View\Helper\Hyperlink',
            'messages' => 'Omeka\View\Helper\Messages',
            'sortLink' => 'Omeka\View\Helper\SortLink',
            'sortSelector' => 'Omeka\View\Helper\SortSelector',
            'propertySelector' => 'Omeka\View\Helper\PropertySelector',
            'itemSetSelector' => 'Omeka\View\Helper\ItemSetSelector',
            'formPropertyInputs' => 'Omeka\View\Helper\PropertyInputs',
            'searchFilters' => 'Omeka\View\Helper\SearchFilters',
            'blockAttachmentsForm' => 'Omeka\View\Helper\BlockAttachmentsForm',
            'blockShowTitleSelect' => 'Omeka\View\Helper\BlockShowTitleSelect',
            'ckEditor' => 'Omeka\View\Helper\CkEditor',
            'sitePagePagination' => 'Omeka\View\Helper\SitePagePagination',
            'sectionNav' => 'Omeka\View\Helper\SectionNav',
            'uploadLimit' => 'Omeka\View\Helper\UploadLimit',
            'formRecaptcha' => 'Omeka\Form\View\Helper\FormRecaptcha',
            'formCkeditor' => 'Omeka\Form\View\Helper\FormCkeditor',
            'formCkeditorInline' => 'Omeka\Form\View\Helper\FormCkeditorInline',
            'formRestoreTextarea' => 'Omeka\Form\View\Helper\FormRestoreTextarea',
            'queryToHiddenInputs' => 'Omeka\View\Helper\QueryToHiddenInputs',
            'formAsset' => 'Omeka\Form\View\Helper\FormAsset',
            'themeSettingAssetUrl' => 'Omeka\View\Helper\ThemeSettingAssetUrl',
            'formColorPicker' => 'Omeka\Form\View\Helper\FormColorPicker',
            'thumbnail' => 'Omeka\View\Helper\Thumbnail',
        ],
        'factories' => [
            'api' => 'Omeka\Service\ViewHelper\ApiFactory',
            'assetUrl' => 'Omeka\Service\ViewHelper\AssetUrlFactory',
            'blockLayout' => 'Omeka\Service\ViewHelper\BlockLayoutFactory',
            'blockThumbnailTypeSelect' => 'Omeka\Service\ViewHelper\BlockThumbnailTypeSelectFactory',
            'dataType' => 'Omeka\Service\ViewHelper\DataTypeFactory',
            'i18n' => 'Omeka\Service\ViewHelper\I18nFactory',
            'media' => 'Omeka\Service\ViewHelper\MediaFactory',
            'navigationLink' => 'Omeka\Service\ViewHelper\NavigationLinkFactory',
            'pagination' => 'Omeka\Service\ViewHelper\PaginationFactory',
            'params' => 'Omeka\Service\ViewHelper\ParamsFactory',
            'setting' => 'Omeka\Service\ViewHelper\SettingFactory',
            'userSetting' => 'Omeka\Service\ViewHelper\UserSettingFactory',
            'siteSetting' => 'Omeka\Service\ViewHelper\SiteSettingFactory',
            'themeSetting' => 'Omeka\Service\ViewHelper\ThemeSettingFactory',
            'trigger' => 'Omeka\Service\ViewHelper\TriggerFactory',
            'userIsAllowed' => 'Omeka\Service\ViewHelper\UserIsAllowedFactory',
            'deleteConfirm' => 'Omeka\Service\ViewHelper\DeleteConfirmFactory',
            'resourceClassSelect' => 'Omeka\Service\ViewHelper\ResourceClassSelectFactory',
            'propertySelect' => 'Omeka\Service\ViewHelper\PropertySelectFactory',
            'itemSetSelect' => 'Omeka\Service\ViewHelper\ItemSetSelectFactory',
            'siteSelect' => 'Omeka\Service\ViewHelper\SiteSelectFactory',
            'resourceSelect' => 'Omeka\Service\ViewHelper\ResourceSelectFactory',
            'jsTranslate' => 'Omeka\Service\ViewHelper\JsTranslateFactory',
            'lang' => 'Omeka\Service\ViewHelper\LangFactory',
        ],
        'delegators' => [
            'Zend\Form\View\Helper\FormElement' => [
                'Omeka\Service\Delegator\FormElementDelegatorFactory',
            ],
            'Zend\Form\View\Helper\FormSelect' => [
                'Omeka\Service\Delegator\FormSelectDelegatorFactory',
            ],
            'Zend\Form\View\Helper\FormRow' => [
                'Omeka\Service\Delegator\FormRowDelegatorFactory',
            ],
            'Zend\View\Helper\Navigation' => [
                'Omeka\Service\Delegator\NavigationDelegatorFactory',
            ],
        ],
    ],
    'form_elements' => [
        'initializers' => [
            'Omeka\Form\Initializer\Csrf',
        ],
        'factories' => [
            'Omeka\Form\ResourceForm' => 'Omeka\Service\Form\ResourceFormFactory',
            'Omeka\Form\UserForm' => 'Omeka\Service\Form\UserFormFactory',
            'Omeka\Form\SettingForm' => 'Omeka\Service\Form\SettingFormFactory',
            'Omeka\Form\ModuleStateChangeForm' => 'Omeka\Service\Form\ModuleStateChangeFormFactory',
            'Omeka\Form\SiteForm' => 'Omeka\Service\Form\SiteFormFactory',
            'Omeka\Form\SiteSettingsForm' => 'Omeka\Service\Form\SiteSettingsFormFactory',
            'Omeka\Form\Element\ResourceSelect' => 'Omeka\Service\Form\Element\ResourceSelectFactory',
            'Omeka\Form\Element\ResourceClassSelect' => 'Omeka\Service\Form\Element\ResourceClassSelectFactory',
            'Omeka\Form\Element\PropertySelect' => 'Omeka\Service\Form\Element\PropertySelectFactory',
            'Omeka\Form\Element\ItemSetSelect' => 'Omeka\Service\Form\Element\ItemSetSelectFactory',
            'Omeka\Form\Element\SiteSelect' => 'Omeka\Service\Form\Element\SiteSelectFactory',
            'Omeka\Form\Element\LocaleSelect' => 'Omeka\Service\Form\Element\LocaleSelectFactory',
            'Omeka\Form\Element\Recaptcha' => 'Omeka\Service\Form\Element\RecaptchaFactory',
            'Omeka\Form\Element\HtmlTextarea' => 'Omeka\Service\Form\Element\HtmlTextareaFactory',
            'Omeka\Form\Element\Ckeditor' => 'Omeka\Service\Form\Element\CkeditorFactory',
            'Omeka\Form\Element\CkeditorInline' => 'Omeka\Service\Form\Element\CkeditorInlineFactory',
        ],
    ],
    'data_types' => [
        'invokables' => [
            'literal' => 'Omeka\DataType\Literal',
            'uri' => 'Omeka\DataType\Uri',
            'resource' => 'Omeka\DataType\Resource\All',
            'resource:item' => 'Omeka\DataType\Resource\Item',
            'resource:itemset' => 'Omeka\DataType\Resource\ItemSet',
            'resource:media' => 'Omeka\DataType\Resource\Media',
        ],
    ],
    'block_layouts' => [
        'factories' => [
            'html' => 'Omeka\Service\BlockLayout\HtmlFactory',
        ],
        'invokables' => [
            'pageTitle' => 'Omeka\Site\BlockLayout\PageTitle',
            'media' => 'Omeka\Site\BlockLayout\Media',
            'browsePreview' => 'Omeka\Site\BlockLayout\BrowsePreview',
            'itemShowCase' => 'Omeka\Site\BlockLayout\ItemShowcase',
            'tableOfContents' => 'Omeka\Site\BlockLayout\TableOfContents',
            'lineBreak' => 'Omeka\Site\BlockLayout\LineBreak',
            'itemWithMetadata' => 'Omeka\Site\BlockLayout\ItemWithMetadata',
        ],
        'sorted_names' => [
            'html',
        ],
    ],
    'navigation_links' => [
        'invokables' => [
            'page' => 'Omeka\Site\Navigation\Link\Page',
            'url' => 'Omeka\Site\Navigation\Link\Url',
            'browse' => 'Omeka\Site\Navigation\Link\Browse',
            'browseItemSets' => 'Omeka\Site\Navigation\Link\BrowseItemSets',
        ],
    ],
    'media_ingesters' => [
        'factories' => [
            'upload' => 'Omeka\Service\Media\Ingester\UploadFactory',
            'url' => 'Omeka\Service\Media\Ingester\UrlFactory',
            'html' => 'Omeka\Service\Media\Ingester\HtmlFactory',
            'iiif' => 'Omeka\Service\Media\Ingester\IIIFFactory',
            'oembed' => 'Omeka\Service\Media\Ingester\OEmbedFactory',
            'youtube' => 'Omeka\Service\Media\Ingester\YoutubeFactory',
        ],
    ],
    'media_renderers' => [
        'invokables' => [
            'oembed' => 'Omeka\Media\Renderer\OEmbed',
            'youtube' => 'Omeka\Media\Renderer\Youtube',
            'html' => 'Omeka\Media\Renderer\Html',
            'iiif' => 'Omeka\Media\Renderer\IIIF',
        ],
        'factories' => [
            'file' => 'Omeka\Service\Media\Renderer\FileFactory',
        ],
    ],
    'file_renderers' => [
        'invokables' => [
            'fallback' => 'Omeka\Media\FileRenderer\FallbackRenderer',
            'thumbnail' => 'Omeka\Media\FileRenderer\ThumbnailRenderer',
            'audio' => 'Omeka\Media\FileRenderer\AudioRenderer',
            'video' => 'Omeka\Media\FileRenderer\VideoRenderer',
        ],
        'aliases' => [
            'audio/ogg' => 'audio',
            'audio/x-aac' => 'audio',
            'audio/mpeg' => 'audio',
            'audio/mp4' => 'audio',
            'audio/x-wav' => 'audio',
            'audio/x-aiff' => 'audio',
            'application/ogg' => 'video',
            'video/mp4' => 'video',
            'video/quicktime' => 'video',
            'video/x-msvideo' => 'video',
            'video/ogg' => 'video',
            'video/webm' => 'video',
            'mp3' => 'audio',
        ],
    ],
    'oembed' => [
        'whitelist' => [
            '#^https?://(www\.)?youtube\.com/watch.*$#i',
            '#^https?://(www\.)?youtube\.com/playlist.*$#i',
            '#^https?://youtu\.be/.*$#i',
            '#^http://blip.tv/*$#',
            '#^https?://(.+\.)?vimeo\.com/.*$#i',
            '#^https?://(www\.)?dailymotion\.com/.*$#i',
            '#^http://dai.ly/*$#',
            '#^https?://(www\.)?flickr\.com/.*$#i',
            '#^https?://flic\.kr/.*$#i',
            '#^https?://(.+\.)?smugmug\.com/.*$#i',
            '#^https?://(www\.)?hulu\.com/watch/.*$#i',
            '#^http://revision3.com/*$#',
            '#^http://i*.photobucket.com/albums/*$#',
            '#^http://gi*.photobucket.com/groups/*$#',
            '#^https?://(www\.)?scribd\.com/doc/.*$#i',
            '#^https?://wordpress.tv/.*$#i',
            '#^https?://(.+\.)?polldaddy\.com/.*$#i',
            '#^https?://poll\.fm/.*$#i',
            '#^https?://(www\.)?funnyordie\.com/videos/.*$#i',
            '#^https?://(www\.)?twitter\.com/.+?/status(es)?/.*$#i',
            '#^https?://(www\.)?soundcloud\.com/.*$#i',
            '#^https?://(www\.)?slideshare\.net/.*$#i',
            '#^https?://(www\.)?rdio\.com/.*$#i',
            '#^https?://rd\.io/x/.*$#i',
            '#^https?://(open|play)\.spotify\.com/.*$#i',
            '#^https?://(.+\.)?imgur\.com/.*$#i',
            '#^https?://(www\.)?meetu(\.ps|p\.com)/.*$#i',
            '#^https?://(www\.)?issuu\.com/.+/docs/.+$#i',
            '#^https?://(www\.)?collegehumor\.com/video/.*$#i',
            '#^https?://(www\.)?mixcloud\.com/.*$#i',
            '#^https?://(www\.|embed\.)?ted\.com/talks/.*$#i',
            '#^https?://(www\.)?(animoto|video214)\.com/play/.*$#i',
        ],
    ],
    'mail' => [
        'transport' => [
            'type' => 'sendmail',
            'options' => [],
        ],
        'default_message_options' => [
            'encoding' => 'UTF-8',
        ],
    ],
    'js_translate_strings' => [
        'Something went wrong', // @translate
        'Make private', // @translate
        'Make public', // @translate
        'Expand', // @translate
        'Collapse', // @translate
        'You have unsaved changes.', // @translate
        'Restore item set', // @translate
        'Close icon set', // @translate
        'Open icon set', // @translate
        '[Untitled]', // @translate
        'Failed loading resource template from API', // @translate
        'Restore property', // @translate
        'There are no available pages.', // @translate
        'Please enter a valid language tag', // @translate
    ],
];
