<?php
$translate = $this->plugin('translate');
?>
<h1><?php echo $translate('Omeka S encountered an error'); ?></h1>

<?php if (ini_get('display_errors')): ?>
<p>
<strong><?php echo $this->escapeHtml(get_class($this->exception)); ?></strong><br>
<?php echo $this->escapeHtml($this->exception->getMessage()); ?>
</p>
<p><?php echo $translate('Details:'); ?></p>
<pre>
<?php echo $this->escapeHtml($this->exception); ?>
</pre>
<?php endif; ?>
