<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/collecting.css', 'Collecting'));
echo $this->pageTitle(sprintf($this->translate('Collecting Form: “%s”'), $cForm->label()));
$itemSetLabel = $cForm->itemSet()
    ? $cForm->itemSet()->displayTitle()
    : $this->translate('[none]');
?>

<div id="page-actions">
    <?php if ($cForm->userIsAllowed('update')): ?>
    <?php echo $cForm->link($this->translate('Edit form'), 'edit', ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<div class="breadcrumbs">
    <a href="<?php echo $this->url('admin/site/slug/collecting', [], true); ?>" class="o-icon-left"><?php echo $this->translate('Back to collecting forms list'); ?></a>
</div>

<nav class="section-nav">
    <?php echo $this->navigation('Laminas\Navigation\Collecting')->menu(); ?>
</nav>

<div class="property">
    <h4><?php echo $this->translate('Label'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($cForm->label()); ?></div>
</div>

<div class="property">
    <h4><?php echo $this->translate('Anonymity Type'); ?></h4>
    <div class="value"><?php echo $this->translate($this->collecting()->anonTypeValue($cForm->anonType())); ?></div>
</div>

<div class="property">
    <h4><?php echo $this->translate('Item Set'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($itemSetLabel); ?></div>
</div>

<br>
<h3><?php echo $this->translate('Prompts'); ?></h3>

<?php if ($prompts = $cForm->prompts()): ?>

<table id="prompts-table" class="browse tablesaw" data-tablesaw-mode="stack">
    <thead>
    <tr>
        <th><?php echo $this->translate('Type'); ?></th>
        <th><?php echo $this->translate('Text'); ?></th>
        <th><?php echo $this->translate('Required?'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($prompts as $prompt): ?>
    <tr>
        <td><?php echo $this->escapeHtml($this->translate($prompt->displayType())); ?></td>
        <td><?php echo $this->escapeHtml($prompt->displayText()); ?></td>
        <td><?php echo $prompt->required() ? $this->translate('Yes') : $this->translate('No'); ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>

<p><?php echo $this->translate('This form has no prompts.'); ?></p>

<?php endif; ?>
