<?php
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>
<legend><?php echo $this->translate('Media'); ?></legend>
<div id="add-media-field" class="field">
    <div class="field-meta">
        <label for="new-media-type">
            <?php echo $this->translate('Add New Media'); ?> 
        </label>
    </div>
    <div class="inputs">
        <select id="new-media-type">
            <option value=""><?php echo $this->translate('Select media type'); ?></option>
            <?php foreach ($mediaForms as $type => $form): ?>
            <option value="<?php echo $escapeAttr($type); ?>"><?php echo $escape($form['label']); ?></option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
<?php foreach ($mediaForms as $type => $form): ?>
<span
    id="media-template-<?php echo $escapeAttr($type); ?>"
    data-template="<?php echo $escapeAttr($form['form']); ?>"
></span>
<?php endforeach; ?>

<?php if ($resource && $resource->media()): ?>
    <?php foreach ($resource->media() as $media): ?>
    <div class="media value row">
        <ul class='actions'>
            <li>
                <a class='o-icon-delete remove-value' href='#' title='Remove value' aria-label='Remove value'></a>
            </li>
            <li>
                <a class='o-icon-undo restore-value' href='#' title='Undo remove value' aria-label='Undo remove value'></a>
            </li>
        </ul>
        <span class='restore-value'>Media to be removed</span>
        <img src="<?php echo $media->thumbnailUrl('square'); ?>">
        <span class="resource-name"><?php echo $media->displayTitle('[Untitled]'); ?></span>
        <input type="hidden" name="o:media[][o:id]" value="<?php echo $escapeAttr($media->id()); ?>">
    </div>
    <?php endforeach; ?>
<?php endif; ?>

<script type="text/javascript">
var index = 0;
$('#new-media-type').change(function () {
    var type = $(this).val();
    if (!type) {
        return;
    }

    var template = $('#media-template-' + type).data('template');
    $('#add-media-field').before(
        $.parseHTML(template.replace(/__index__/g, index++))
    );
    $(this).val('');
});
</script>
