<?php
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$this->headScript()->appendFile($this->assetUrl('js/sortable.js', 'Omeka'));
?>
<legend><?php echo $this->translate('Media'); ?></legend>
<?php foreach ($mediaForms as $type => $form): ?>
<span
    id="media-template-<?php echo $escapeAttr($type); ?>"
    data-template="<?php echo $escapeAttr($form['form']); ?>"
></span>
<?php endforeach; ?>

<div id="media-list">
<?php if ($resource && $resource->media()): ?>
    <?php foreach ($resource->media() as $media): ?>
    <div class="media value row">
        <ul class='actions'>
            <li>
                <a class='o-icon-delete remove-value' href='#' title='Remove value' aria-label='Remove value'></a>
            </li>
            <li>
                <a class='o-icon-undo restore-value' href='#' title='Undo remove value' aria-label='Undo remove value'></a>
            </li>
        </ul>
        <span class='restore-value'>Media to be removed</span>
        <img src="<?php echo $media->thumbnailUrl('square'); ?>">
        <span class="resource-name"><?php echo $media->displayTitle(); ?></span>
        <input type="hidden" name="o:media[][o:id]" value="<?php echo $escapeAttr($media->id()); ?>">
        <span class="sortable-handle"></span>
    </div>
    <?php endforeach; ?>
<?php endif; ?>
</div>

<div class="active sidebar">
    <label for="new-media-type">
        <?php echo $this->translate('Add New Media'); ?> 
    </label>
    <select id="new-media-type">
        <option value=""><?php echo $this->translate('Select media type'); ?></option>
        <?php foreach ($mediaForms as $type => $form): ?>
        <option value="<?php echo $escapeAttr($type); ?>"><?php echo $escape($form['label']); ?></option>
        <?php endforeach; ?>
    </select>
</div>

<script type="text/javascript">

var list = document.getElementById('media-list');
new Sortable(list, {
    draggable: ".media",
    handle: ".sortable-handle"
});

var index = <?php echo ($resource) ? count($resource->media()) : 0; ?>;

$('#new-media-type').change(function () {
    var type = $(this).val();
    if (!type) {
        return;
    }

    var template = $('#media-template-' + type).data('template');
    $('#media-list').append(
        $.parseHTML(template.replace(/__index__/g, index++))
    );
    $(this).val('');
    $('html, body').animate({
        scrollTop: ($('.media-field-wrapper').last().offset().top -100)
    },200);
});

$('#item-media').on('click', 'a.remove-new-media-field', function (e) {
    e.preventDefault();
    $(this).parents(".media-field-wrapper").remove();
});

</script>
