<?php
$this->htmlElement('body')->appendAttribute('class', 'add item sidebar-open');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'));
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
?>
<?php 
if (isset($errors)) {
    print_r($errors);
}
?>
<h1><?php echo $this->translate('Add item'); ?></h1>

<nav class="section-nav">
    <ul>
        <li><a href="#" class="resource-values section active">Values</a></li>
        <li><a href="#" class="item-media section">Media</a></li>
        <li><a href="#" class="item-visibility section">Visibility</a></li>
    </ul>
</nav>

<form method='post' id='add-item'>
    <?php 
    
        //produces a <fieldset> with the id and class atts passed in.
        //on, e.g., the item add/edit pages, the id will work with the classes on 
        //the nav lis above. (see globals.js)  
        echo $this->partial(
                'common/resource-fields.phtml',
                array('id' => 'resource-values', 'class' => 'section active' )
                );
    ?>

    <fieldset id="save-sidebar">
        <input type="submit" name="add-item-submit" value="Create item" />
        <a href="#" class="cancel button">Cancel</a>
    </fieldset>
    <?php echo $this->formElement($form->get('csrf')); ?>
</form>

<!-- 
the sidebar and templates are not going into the fields partial because
they exist outside the form, and the partial needs to work with 
multiple resource fieldsets (item and media, e.g.)
-->

<?php 
        echo $this->partial('common/resource-form-templates.phtml');
?>