<?php
$this->htmlElement('body')->appendAttribute('class', 'add items');
?>

<?php echo $this->pageTitle($this->translate('New item'), 1, $this->translate('Items')); ?>
<?php $this->trigger('view.add.before'); ?>
<?php
echo $this->partial('omeka/admin/item/form.phtml', [
    'form' => $form,
    'item' => null,
    'mediaForms' => $mediaForms,
    'submitLabel' => $this->translate('Add'),
    'sectionNavEvent' => 'view.add.section_nav',
    'action' => 'add',
]);
?>

<?php $this->trigger('view.add.after'); ?>
