<?php
echo $this->pageTitle($this->translate('Batch Edit Items'));
$propertySelect = $this->propertySelect([
    'name' => 'value[__INDEX__][property_id]',
    'options' => ['empty_option' => 'Select property'],
]);
$valueField = <<<VALUE
<div class="field">
    <div class="field-meta">
        <label>Add value</label>
    </div>
    <div class="inputs">
        $propertySelect
        <select name="value[__INDEX__][type]">
            <option value="">Select type</option>
            <option value="literal">Literal</option>
            <option value="uri">URI</option>
            <option value="resource">Resource</option>
        </select>
        <input type="text" name="value[__INDEX__][value]">
        <button type="button" class="remove-value-button">Remove this value</button>
    </div>
</div>
VALUE;
?>

<?php echo $this->form()->openTag($form); ?>

<?php foreach ($resourceIds as $resourceId): ?>
<input type="hidden" name="resource_ids[]" value="<?php echo $resourceId; ?>">
<?php endforeach; ?>
<input type="hidden" name="query" value="<?php echo $this->escapeHtml(json_encode($query)); ?>">

<div id="page-actions">
     <input type="submit" name="batch_update" value="Save">
</div>

<?php echo $this->formRow($form->get('is_public')); ?>
<?php echo $this->formRow($form->get('resource_template')); ?>
<?php echo $this->formRow($form->get('resource_template_unset')); ?>
<?php echo $this->formRow($form->get('resource_class')); ?>
<?php echo $this->formRow($form->get('resource_class_unset')); ?>
<?php echo $this->formRow($form->get('add_to_item_set[]')); ?>
<?php echo $this->formRow($form->get('remove_from_item_set[]')); ?>
<?php echo $this->formRow($form->get('clear_property_values[]')); ?>

<div id="values" data-template="<?php echo $this->escapeHtml($valueField); ?>"></div>
<button type="button" id="add-value-button">Add another value</button>

<?php echo $this->formRow($form->get('csrf')); ?>
<?php echo $this->form()->closeTag();; ?>

<script>
$(document).ready(function() {
    var values = $('#values');
    var valueTemplate = values.data('template');
    var index = 0;
    var addValue = function() {
        values.append($.parseHTML(valueTemplate.replace(/__INDEX__/g, index++)));
    }
    addValue();
    $('#add-value-button').on('click', function(e) {
        addValue();
    });
    $('.remove-value-button').on('click', function(e) {
        $(this).closest('.field').remove();
    });
});
</script>
