<?php
echo $this->pageTitle($this->translate('Batch Edit Items'));
$propertySelect = $this->propertySelect([
    'name' => 'value[__INDEX__][property_id]',
    'options' => ['empty_option' => 'Select property'],
]);
$templateLiteral = <<<VALUE
<div class="field">
    <div class="field-meta">
        <label>Add text value</label>
    </div>
    <div class="inputs">
        $propertySelect
        <textarea name="value[__INDEX__][value]"></textarea>
        <input type="hidden" name="value[__INDEX__][type]" value="literal">
        <button type="button" class="remove-value-button">Remove this value</button>
    </div>
</div>
VALUE;
$templateResource = <<<VALUE
<div class="field">
    <div class="field-meta">
        <label>Add resource value</label>
    </div>
    <div class="inputs">
        $propertySelect
        <input type="text" name="value[__INDEX__][value_resource_id]" placeholder="Resource ID">
        <input type="hidden" name="value[__INDEX__][type]" value="resource">
        <button type="button" class="remove-value-button">Remove this value</button>
    </div>
</div>
VALUE;
$templateUri = <<<VALUE
<div class="field">
    <div class="field-meta">
        <label>Add URI value</label>
    </div>
    <div class="inputs">
        $propertySelect
        <input type="text" name="value[__INDEX__][id]" placeholder="URI">
        <input type="text" name="value[__INDEX__][label]" placeholder="Label">
        <input type="hidden" name="value[__INDEX__][type]" value="uri">
        <button type="button" class="remove-value-button">Remove this value</button>
    </div>
</div>
VALUE;
?>

<?php echo $this->form()->openTag($form); ?>

<?php foreach ($resourceIds as $resourceId): ?>
<input type="hidden" name="resource_ids[]" value="<?php echo $resourceId; ?>">
<?php endforeach; ?>
<input type="hidden" name="query" value="<?php echo $this->escapeHtml(json_encode($query)); ?>">

<div id="page-actions">
     <input type="submit" name="batch_update" value="Save">
</div>

<?php echo $this->formRow($form->get('is_public')); ?>
<?php echo $this->formRow($form->get('resource_template')); ?>
<?php echo $this->formRow($form->get('resource_template_unset')); ?>
<?php echo $this->formRow($form->get('resource_class')); ?>
<?php echo $this->formRow($form->get('resource_class_unset')); ?>
<?php echo $this->formRow($form->get('add_to_item_set[]')); ?>
<?php echo $this->formRow($form->get('remove_from_item_set[]')); ?>
<?php echo $this->formRow($form->get('clear_property_values[]')); ?>

<div id="values"
    data-template-literal="<?php echo $this->escapeHtml($templateLiteral); ?>"
    data-template-resource="<?php echo $this->escapeHtml($templateResource); ?>"
    data-template-uri="<?php echo $this->escapeHtml($templateUri); ?>"
></div>
<button type="button" class="add-value-button" data-type="literal">Add text value</button>
<button type="button" class="add-value-button" data-type="resource">Add resource value</button>
<button type="button" class="add-value-button" data-type="uri">Add URI value</button>

<?php echo $this->formRow($form->get('csrf')); ?>
<?php echo $this->form()->closeTag();; ?>

<script>
$(document).ready(function() {
    var values = $('#values');
    var templateLiteral = values.data('template-literal');
    var templateResource = values.data('template-resource');
    var templateUri = values.data('template-uri');
    var index = 0;
    var addValue = function(type) {
        switch (type) {
            case 'resource':
                template = templateResource;
                break;
            case 'uri':
                template = templateUri;
                break;
            case 'literal':
            default:
                template = templateLiteral;
        }
        values.append($.parseHTML(template.replace(/__INDEX__/g, index++)));
    }
    addValue('literal');
    $('.add-value-button').on('click', function(e) {
        addValue($(this).data('type'));
    });
    $('.remove-value-button').on('click', function(e) {
        $(this).closest('.field').remove();
    });
});
</script>
