<?php
$this->htmlElement('body')->appendAttribute('class', 'items browse');
$escape = $this->plugin('escapeHtml');
$sortHeadings = [
    [
        'label' => $this->translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $this->translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $this->translate('Owner'),
        'value' => 'owner_name'
    ],
    [
        'label' => $this->translate('Date Created'),
        'value' => 'created'
    ],
];
?>

<?php echo $this->pageTitle($this->translate('Items')); ?>

<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
<?php echo $this->pagination(); ?>
<?php echo $this->hyperlink($this->translate('Advanced search'), $this->url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']); ?>
<?php echo $this->sortSelector($sortHeadings); ?>
</div>

<form method="post" id="batch-form">

<div id="page-actions">
    <?php if ($this->userIsAllowed('Omeka\Api\Adapter\ItemAdapter', 'batch_update')): ?>
    <input type="submit" name="update_selected" value="Edit selected" formaction="<?php echo $escape($this->url(null, ['action' => 'batch-edit'], true)); ?>">
    <input type="submit" name="update_all" value="Edit all" formaction="<?php echo $escape($this->url(null, ['action' => 'batch-edit-all'], true)); ?>">
    <a class="delete button sidebar-content" data-sidebar-content-url="<?php echo $escape($this->url(null, ['action' => 'batch-delete-confirm'], true)); ?>">Delete selected</a>
    <?php endif; ?>
    <?php if ($this->userIsAllowed('Omeka\Api\Adapter\ItemAdapter', 'create')): ?>
    <?php echo $this->hyperlink($this->translate('Add new item'), $this->url(null, ['action' => 'add'], true), ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<?php if ($items): ?>
<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><input type="checkbox" class="select-all"></th>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Class'); ?></th>
            <th><?php echo $this->translate('Owner'); ?></th>
            <th><?php echo $this->translate('Date Created'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $item): ?>
        <?php
        if ($owner = $item->owner()) {
            $ownerText = $this->hyperlink(
                $owner->name(),
                $this->url('admin/id', [
                    'controller' => 'user',
                    'action' => 'show',
                    'id' => $owner->id()]
                )
            );
        } else {
            $ownerText = $this->translate('[no owner]');
        }
        ?>
        <tr>
            <td><?php if ($item->userIsAllowed('update') || $item->userIsAllowed('delete')): ?>
                <input type="checkbox" name="resource_ids[]" value="<?php echo $item->id(); ?>">
            <?php endif; ?></td>
            <td>
                <ul class="actions">
                    <?php if ($item->userIsAllowed('update')): ?>
                    <li><?php echo $item->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'aria-label' => $this->translate('Edit'),
                        'title' => $this->translate('Edit'),
                    ]); ?></li>
                    <?php endif; ?>
                    <?php if ($item->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($item->url('delete-confirm')); ?>"
                        class="o-icon-delete sidebar-content"
                        aria-label="<?php echo $escape($this->translate('Delete')); ?>"
                        title="<?php echo $escape($this->translate('Delete')); ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($item->url('show-details')); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escape($this->translate('Details')); ?>"
                        title="<?php echo $escape($this->translate('Details')); ?>"></a></li>
                </ul>
                <?php if ($media = $item->primaryMedia()): ?>
                <img src="<?php echo $escape($media->thumbnailUrl('square')); ?>">
                <?php endif; ?>
                <span class="resource-name">
                    <?php echo $item->link($item->displayTitle()); ?>
                </span>
                <?php if (!$item->isPublic()): ?>
                    <span class="o-icon-private"></span>
                <?php endif; ?>
            </td>
            <td><?php echo $escape($item->displayResourceClassLabel()); ?></td>
            <td><?php echo $ownerText; ?></td>
            <td><?php echo $escape($this->i18n()->dateFormat($item->created())); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div class="sidebar-content"></div>
</div>

<script>
$('.sidebar').on('submit', '#confirm-batch-delete', function(e) {
    var confirmBatchForm = $(this);
    var batchForm = $('#batch-form');
    batchForm.find('input:checked').each(function() {
        confirmBatchForm.append($(this).clone().attr('type', 'hidden'));
    });
});
</script>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any items.'); ?></p>
</div>

<?php endif; ?>


