<?php
$this->htmlElement('body')->appendAttribute('class', 'items browse');
$confirmForm->prepare();
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>

<h1><?php echo $escape($this->translate('Items')); ?></h1>

<div id="page-actions">
    <?php if ($this->userIsAllowed('Omeka\Api\Adapter\ItemAdapter', 'create')): ?>
    <?php echo $this->hyperlink($this->translate('Add new item'), $this->url(null, array('action' => 'add'), true), array('class' => 'button')); ?>
    <?php endif; ?>
    <?php echo $this->hyperlink($this->translate('Search items'), $this->url(null, array('action' => 'search'), true), array('class' => 'button')); ?>
</div>

<?php if (count($items) > 0): ?>

<?php echo $this->pagination(); ?>

<table>
    <thead>
        <tr>
            <th><?php echo $this->sortLink($this->translate('Title'), 'dcterms:title'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Class'), 'resource_class_label'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Date Created'), 'created'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $item): ?>
        <tr>
            <td>
                <?php if ($media = $item->primaryMedia()): ?>
                <img src="<?php echo $escapeAttr($media->thumbnailUrl('square')); ?>">
                <?php endif; ?>
                <span class="resource-name">
                    <?php echo $item->link($item->displayTitle()); ?>
                </span>
                <ul class="actions">
                    <?php if ($item->userIsAllowed('update')): ?>
                    <li><?php echo $item->link('', 'edit', array(
                        'class' => 'o-icon-edit',
                        'aria-label' => $this->translate('Edit'),
                        'title' => $this->translate('Edit'),
                    )); ?></li>
                    <?php endif; ?>
                    <?php if ($item->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escapeAttr($item->url('show-details')); ?>"
                        data-sidebar-confirm-url="<?php echo $escapeAttr($item->url('delete')); ?>"
                        class="o-icon-delete sidebar-confirm"
                        aria-label="<?php echo $escapeAttr($this->translate('Delete')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Delete')); ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escapeAttr($item->url('show-details')); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escapeAttr($this->translate('Details')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Details')); ?>"></a></li>
                </ul>
            </td>
            <td><?php echo $escape($item->displayResourceClassLabel()); ?></td>
            <td><?php echo $escape($this->i18n()->dateFormat($item->created())); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->pagination(); ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escapeAttr($this->translate('Close')); ?>"
        title="<?php echo $escapeAttr($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $escape($this->translate('Delete Item')); ?></h2>
        <p><?php echo $escape($this->translate('Are you sure you would like to delete this item?')); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $escape($this->translate('Omeka could not find any items.')); ?></p>
</div>

<?php endif; ?>

<?php $this->trigger('view.browse.after'); ?>
