<?php
$this->htmlElement('body')->appendAttribute('class', 'edit item sidebar-open');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$deleteButton = '<a href="#" class="delete button sidebar-confirm" 
    data-sidebar-confirm-url="' . $escapeAttr($item->url('delete')) . 
    '">' . $escape('Delete') . '</a>';
?>

<script type='text/javascript'>
var valuesJson = <?php echo json_encode($item->values()); ?>;
</script>

<h1><?php echo $this->translate('Edit Item'); ?>: &ldquo;<?php echo $escape($item->displayTitle()); ?>&rdquo;</h1>

<?php
echo $this->partial('omeka/admin/item/form.phtml', array(
    'form' => $form,
    'item' => $item,
    'mediaForms' => $mediaForms,
    'submitLabel' => $this->translate('Save'),
    'deleteButton' => $deleteButton
));
?>

<div id="delete" class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escapeAttr($this->translate('Close')); ?>"
        title="<?php echo $escapeAttr($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $this->translate('Delete Item'); ?></h2>
        <p><?php echo $this->translate('Are you sure you would like to delete this item?'); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
</div>
