<?php
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/chosen/chosen.jquery.min.js', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('js/chosen/chosen.min.css', 'Omeka'));
$form->prepare();
$escapeAttr = $this->plugin('escapeHtmlAttr');
$escape = $this->plugin('escapeHtml');
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
?>


<?php echo $this->form()->openTag($form); ?>

<nav class="section-nav">
    <ul>
        <li class="active"><a href="#resource-values">Values</a></li>
        <li><a href="#item-media">Media</a></li>
        <li><a href="#item-sets">Item Sets</a></li>
    </ul>
</nav>

    <?php
    //produces a <fieldset> with the id and class atts passed in.
    //on, e.g., the item add/edit pages, the id will work with the classes on
    //the nav lis above. (see globals.js)
    echo $this->partial(
        'common/resource-fields.phtml',
        array(
            'id'                   => 'resource-values',
            'class'                => 'section active',
            'form'                 => $form,
            'resource'             => $item,
            'propertySelectorText' => 'Click on a property to add it to the add panel'
        )
    );
    ?>

    <fieldset id="item-media" class="section">
        <?php
        echo $this->partial('omeka/admin/item/add-media',
            array(
                'mediaForms' => $mediaForms,
                'resource' => $item
            )
        );
        ?>
    </fieldset>
    <fieldset id='item-sets' class='section'>
        <?php echo $this->formField($form->get('o:item_set')); ?>
    </fieldset>

    <fieldset id="page-actions">
        <div class="o-icon-view visibility">
            <label for="o:is_public"><?php echo $escape('Public'); ?></label>
            <input type="checkbox" id="o:is_public" name="o:is_public" <?php echo ($item && $item->isPublic()) ? 'checked' : ''; ?>>
        </div>
        
        <button type="submit" name="add-item-submit" value="<?php echo $escapeAttr($submit_label); ?>"><?php echo $escape($submitLabel); ?></button>
    </fieldset>
    <?php echo $formElement($form->get('csrf')); ?>
</form>

<?php
/*
 * the sidebar and templates are not going into the fields partial because
 * they exist outside the form, and the partial needs to work with
 * multiple resource fieldsets (item and media, e.g.)
 */
echo $this->partial('common/resource-form-templates.phtml');
?>

<script type="text/javascript">
jQuery(document).ready(function ($) {
    $('#select-item-set').chosen({width: '100%'});
});
</script>
