<?php
$this->headScript()->appendFile($this->assetUrl('js/item-manage-sites.js', 'Omeka'));
$siteRepresentations = $item
    ? $item->sites()
    : $this->api()->search('sites', ['assign_new_items' => true])->getContent();
$sites = [];
foreach ($siteRepresentations as $siteRepresentation) {
  $sites[] = [
    'id' => $siteRepresentation->id(),
    'title' => $siteRepresentation->title(),
    'email' => $siteRepresentation->owner(),
  ];
}

foreach($sites as $site) {
  echo '<p>' . $site['title'] . '</p>';
}
$siteTemplate = '
<tr class="site-row">
    <td class="site-title"></td>
    <td class="site-owner-email">__owner-email__</td>
    <td>
        <ul class="actions">
            <li>' . $this->hyperlink('', '#', ['class' => 'o-icon-delete', 'title' => $this->translate('Unassign from site')]) . '</li>
        </ul>
        <input type="hidden" name="o:site[]" class="site-id">
    </td>
</tr>';
?>
<table id="item-sites" data-item-sites="<?php echo $this->escapeHtml(json_encode($sites)); ?>" data-row-template="<?php echo $this->escapeHtml($siteTemplate); ?>" data-tablesaw-mode="stack" class="tablesaw tablesaw-stack <?php echo ($item && $sites) ? '' : 'empty'; ?>">
    <thead>
    <tr>
        <th><?php echo $this->translate('Title'); ?></th>
        <th><?php echo $this->translate('Owner'); ?></th>
        <th></th>
    </tr>
    </thead>
    <tbody id="site-rows"></tbody>
</table>

<div class="no-resources">
    <p><?php echo $this->translate('This item is part of no sites. Add it to a site using the interface to the right.'); ?></p>
</div>

<button id="site-selector-button" class="mobile-only"><?php echo $this->translate('Assign to site'); ?></button>

<?php echo $this->siteSelector(); ?>
