<?php
if ($item) {
    $siteRepresentations = $item->sites();
} else {
    $siteRepresentations = $this->api()->search('sites', ['assign_new_items' => true])->getContent();

    $userDefaultSites = $this->userSetting('default_item_sites');
    if (is_array($userDefaultSites)) {
        $userDefaultSiteRepresentations = $this->api()->search('sites', ['id' => $userDefaultSites])->getContent();
        $siteRepresentations = array_merge($siteRepresentations, $userDefaultSiteRepresentations);
    }
}

$sites = [];
foreach ($siteRepresentations as $siteRepresentation) {
    $id = $siteRepresentation->id();
    $sites[$id] = [
        'id' => $id,
        'title' => $siteRepresentation->title(),
        'email' => $siteRepresentation->owner(),
    ];
}

$siteTemplate = '
<tr class="resource-row">
    <td class="data-value" data-row-key="child-search"></td>
    <td class="data-value" data-row-key="resource-email"></td>
    <td>
        <ul class="actions">
            <li>' . $this->hyperlink('', '#', ['class' => 'o-icon-delete', 'title' => $this->translate('Unassign from site')]) . '</li>
        </ul>
        <input type="hidden" name="o:site[]" class="resource-id">
    </td>
</tr>';
?>
<table id="item-sites" data-existing-rows="<?php echo $this->escapeHtml(json_encode(array_values($sites))); ?>" data-row-template="<?php echo $this->escapeHtml($siteTemplate); ?>" data-tablesaw-mode="stack" class="selector-table tablesaw tablesaw-stack <?php echo ($item && (count($sites) > 0)) ? '' : 'empty'; ?>">
    <thead>
    <tr>
        <th><?php echo $this->translate('Title'); ?></th>
        <th><?php echo $this->translate('Owner'); ?></th>
        <th></th>
    </tr>
    </thead>
    <tbody class="resource-rows"></tbody>
</table>

<div class="no-resources">
    <p><?php echo $this->translate('This item is part of no sites. Add it to a site using the interface to the right.'); ?></p>
</div>

<button id="site-selector-button" class="mobile-only"><?php echo $this->translate('Assign to site'); ?></button>

<?php echo $this->siteSelector(); ?>

<script>
  Omeka.initializeSelector('#item-sites', '#site-selector');
</script>
