<?php
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>
<table id="item-item-sets" class="<?php echo ($item && $item->itemSets()) ? '' : 'empty'; ?>">
    <thead>
    <tr>
        <th><?php echo $this->translate('Title'); ?></th>
        <th><?php echo $this->translate('Owner'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php if ($item && $item->itemSets()): ?>
    <?php foreach ($item->itemSets() as $itemSet): ?>
    <tr>
        <td><?php echo $escape($itemSet->displayTitle()); ?></td>
        <td><?php echo $escape($itemSet->owner()->name()); ?></td>
        <td><ul class="actions">
            <li><a 
                class="o-icon-delete" 
                href="#" 
                title=" <?php echo $escapeAttr($this->translate('Remove item set')); ?>" 
                aria-label=" <?php echo $escape($this->translate('Remove item set')); ?>">
            </a></li>
        </ul><input type="hidden" name="o:item_set[]" value="<?php echo $escapeAttr($itemSet->id()) ?>"></td>
    </tr>
    <?php endforeach; ?>
    <?php endif; ?>
    </tbody>
</table>

<div class="no-resources">
    <p><?php echo $this->translate('This item is part of no item sets. Add it to an item set using the interface to the right.'); ?></p>
</div>


<?php
$itemSetTemplate = '
<tr>
    <td>__item-set-title__</td>
    <td>__owner-email__</td>
    <td><ul class="actions">
        <li><a class="o-icon-delete" href="#" title="Remove item set" aria-label="Remove item set"></a></li>
    </ul><input type="hidden" name="o:item_set[]" value="__item-set-id__"></td>
</tr>';
?>
<span id="item-set-template" data-template="<?php echo $escapeAttr($itemSetTemplate); ?>"></span>

<?php echo $this->itemSetSelector(); ?>

<script>
// Add the selected item set to the edit panel.
$('#item-set-selector .selector-child').click(function(event) {
    event.preventDefault();

    $('#item-item-sets').removeClass('empty');
    var itemSetId = $(this).data('item-set-id');
    var itemSetTitle = $(this).data('child-label');
    var ownerEmail = $(this).data('owner-email');

    if ($('input[value="' + itemSetId + '"]').length === 0) {
        var template = $('#item-set-template').data('template');
        template = template.replace(/__item-set-title__/g, itemSetTitle);
        template = template.replace(/__item-set-id__/g, itemSetId);
        template = template.replace(/__owner-email__/g, ownerEmail);
    
        $('#item-item-sets > tbody:last').append($.parseHTML(template));
    }
});

// Remove an item set from the edit panel.
$('#item-item-sets').on('click', '.o-icon-delete', function(event) {
    event.preventDefault();

    var removeLink = $(this);
    var itemSetRow = $(this).closest('tr');
    var itemSetInput = removeLink.closest('td').find('input');

    // Remove the item set input from the form.
    itemSetRow.data('item-set-input', itemSetInput);
    itemSetInput.remove();

    // Undo remove item set link.
    var undoRemoveLink = $('<a>', {
        href: '#',
        class: 'fa fa-undo',
        title: 'Undo remove item set',
        click: function(event) {
            event.preventDefault();
            itemSetRow.toggleClass('delete');
            $(this).closest('td').append(itemSetInput);
            removeLink.show();
            $(this).remove();
        },
    });

    itemSetRow.toggleClass('delete');
    undoRemoveLink.insertAfter(removeLink);
    removeLink.hide();
});
</script>
