<?php
$this->htmlElement('body')->appendAttribute('class', 'items search');
?>
<?php echo $this->pageTitle($this->translate('Advanced search'), 1, $this->translate('Items')); ?>
<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
<?php echo $this->partial(
    'common/advanced-search',
    ['query' => $this->params()->fromQuery(), 'resourceType' => 'item']
); ?>
<div id="page-actions">
    <input type="submit" name="submit" value="<?php echo $this->escapeHtml($this->translate('Search')); ?>">
</div>
</form>
