<?php 
$escape = $this->plugin('escapeHtml');
 ?>
<div class="resource-details" data-resource-values="<?php echo $this->escapeHtmlAttr($values); ?>">
    <?php if ($linkTitle): ?>
    <h2 class="o-title"><?php echo $item->link($item->displayTitle()); ?></h2>
    <?php else: ?>
    <h2 class="o-title"><?php echo $escape($item->displayTitle()); ?></h2>
    <?php endif; ?>
    <div class="o-description"><?php echo $escape($item->displayDescription()); ?></div>
    <div class="meta-group">
        <h4>Visibility</h4>
        <div class="value"><?php echo ($item->isPublic()) ? $this->translate('Public') : $this->translate('Private'); ?></div>
    </div>
    <?php $itemsets = $item->itemSets(); ?>
    <?php if (count($itemsets) > 0): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Item Sets'); ?></h4>
        <?php foreach ($itemsets as $itemset): ?>
        <div class="value item-sets"><?php echo $itemset->link($itemset->displayTitle()); ?></div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
    <?php if ($item->media()): ?>
    <div class="meta-group">
        <h4><?php echo $this->translate('Media'); ?></h4>
        <?php foreach ($item->media() as $media): ?>
        <div class="value">
            <a href="<?php echo $media->url(); ?>">
                <img src="<?php echo $this->escapeHtmlAttr($media->thumbnailUrl('square')); ?>">
                <span class="file-name"><?php echo $escape($media->displayTitle()); ?>
            </a>
        </div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
</div>
