<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'items show');
if ($owner = $item->owner()) {
    $ownerText = $escape($item->owner()->name());
} else {
    $ownerText = $translate('[no owner]');
}

$sectionNavs = [
    'item-metadata' => $translate('Metadata'),
    'item-linked' => $translate('Linked resources'),
];
?>
<?php echo $this->pageTitle($item->displayTitle(), 1, $translate('Items')); ?>
<div id="page-actions">
    <?php if ($item->userIsAllowed('update')): ?>
    <?php echo $item->link($translate('Edit item'), 'edit', ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<?php echo $this->sectionNav($sectionNavs, 'view.show.section_nav', $item); ?>

<div id="item-metadata" class="active section">
    <?php if ( $item->resourceClass()): ?>
        <div class="meta-group">
            <h4><?php echo $translate('Class'); ?></h4>
            <div class="value"><?php echo $escape($translate($item->resourceClass()->label())); ?></div>
        </div>
    <?php endif; ?>
    <?php echo $item->displayValues(); ?>
</div>

<div id="item-linked" class="section">
    <?php
    $page = $this->params()->fromQuery('page', 1);
    $property = $this->params()->fromQuery('property');
    $subjectValues = $item->displaySubjectValues($page, 25, $property);
    ?>
    <?php if ($subjectValues): ?>
        <p><?php echo $translate('The following resources link to this item:'); ?></p>
        <?php echo $subjectValues; ?>
    <?php else: ?>
        <div class="no-resources">
            <p><?php echo $translate('No resources link to this item.'); ?></p>
        </div>
    <?php endif; ?>
</div>


<div class="sidebar active">
    <?php echo $this->thumbnail($item, 'square'); ?>
    <div class="meta-group">
        <h4><?php echo $translate('Visibility'); ?></h4>
        <div class="value"><?php echo ($item->isPublic()) ? $escape($translate('Public')) : $escape($translate('Private')); ?></div>
    </div>
    <?php $itemsets = $item->itemSets(); ?>
    <?php if (count($itemsets) > 0): ?>
    <div class="meta-group">
        <h4><?php echo $translate('Item sets'); ?></h4>
        <?php foreach ($itemsets as $itemset): ?>
        <div class="value item-sets"><?php echo $itemset->link($itemset->displayTitle()); ?></div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
    <div class="meta-group">
        <h4><?php echo $translate('Created'); ?></h4>
        <div class="value"><?php echo $escape($this->i18n()->dateFormat($item->created())); ?></div>
    </div>
    <div class="meta-group">
        <h4><?php echo $translate('Owner'); ?></h4>
        <div class="value"><?php echo $ownerText; ?></div>
    </div>
    <?php if ($item->media()): ?>
    <div class="meta-group">
        <h4><?php echo $translate('Media'); ?></h4>
        <?php foreach ($item->media() as $media): ?>
        <div class="value">
            <?php echo $media->linkPretty(); ?>
        </div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
    <?php $this->trigger('view.show.sidebar'); ?>
</div>
<?php $this->trigger('view.show.after'); ?>
