<?php
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$itemsFound = count($items) > 0;
?>

<div id="item-results">
    <h3><?php echo $this->translate('Select item'); ?></h3>
    
    <div class="search-nav">
        <div id="sidebar-resource-search" class="resource-search" data-search-url="<?php echo $escape($this->url(null, [], [], true)); ?>">
            <input type="text" name="search" id="resource-list-search" value="<?php echo $escape($search); ?>">
            <button type="button" class="o-icon-search"><?php echo $this->translate('Search'); ?></button>
            <div class="resource-search-filters">
                <a href="#"
                    class="<?php echo ($resourceClassId || $itemSetId) ? 'collapse' : 'expand'; ?>"
                    aria-label="<?php echo ($resourceClassId || $itemSetId) ? $this->translate('Collapse') : $this->translate('Expand'); ?>"><?php echo $this->translate('Filter search'); ?>
                </a>
                <div class="collapsible">
                <?php
                echo $this->resourceClassSelect([
                    'name' => 'resource_class_id',
                    'options' => [
                        'empty_option' => '',
                    ],
                    'attributes' => [
                        'id' => 'filter-resource-class',
                        'class' => 'chosen-select',
                        'value' => $resourceClassId,
                        'data-placeholder' => 'Filter by class', // @translate
                    ],
                ]);
                echo $this->itemSetSelect([
                    'name' => 'item_set_id',
                    'options' => [
                        'empty_option' => '',
                    ],
                    'attributes' => [
                        'id' => 'filter-item-set',
                        'class' => 'chosen-select',
                        'value' => $itemSetId,
                        'data-placeholder' => 'Filter by item set', // @translate
                    ],
                ]);
                ?>
                </div>
            </div>
        </div>
        <?php if ($itemsFound): ?>
        <?php echo $this->pagination('common/sidebar-pagination.phtml'); ?>
        <?php endif; ?>
    </div>

    <?php if ($itemsFound): ?>
    <button type="button" class="quick-select-toggle"><?php echo $this->translate('Quick add'); ?></button>
    
    <div class="resource-list">
        <?php foreach ($items as $item):?>
        <div class="resource item" data-resource-values="<?php echo $escape(json_encode($item->valueRepresentation())); ?>">
            <div class="select-resource-checkbox-wrapper">
              <input type="checkbox" class="select-resource-checkbox" name="resource_ids[]" value="<?php echo $item->id(); ?>">
            </div>
            <?php
            $content = sprintf(
                '%s<span class="resource-name">%s</span>',
                $this->thumbnail($item, 'square'),
                $escape($item->displayTitle())
            );
            if ($showDetails):
                $attrs = [
                    'class' => 'sidebar-content select-resource resource-link',
                    'data-sidebar-content-url' => $item->url('show-details'),
                    'data-sidebar-selector' => '#resource-details',
                ];
            else:
                $attrs = [
                    'class' => 'select-resource resource-link',
                ];
            endif;
            echo $hyperlink->raw($content, '#', $attrs);
            ?>
        </div>
        <?php endforeach; ?>
    </div>
    <?php else: ?>
    <span class="no-resources"><?php echo $this->translate(sprintf('No %s found.', $this->translate('items'))); ?></span>
    <?php endif; ?>
</div>

<div class="confirm-panel">
    <button type="button" class="select-resources-button">Add selected</button>
</div>
