<?php if ($user): ?>
    <p><strong>Current User</strong>: <?php echo $user->getUsername(); ?></p>
<?php else: ?>
    <p>No authenticated user.</p>
<?php endif; ?>

<?php if (isset($errorMessages)): ?>
<pre><?php print_r($errorMessages); ?></pre>
<?php endif; ?>
<?php if (isset($successMessages)): ?>
<pre><?php print_r($successMessages); ?></pre>
<?php endif; ?>

<?php if (!$auth->hasIdentity()): ?>
<form method="post">
    <label>Username: <input type="text" name="username"></label>
    <label>Password: <input type="password" name="password"></label>
    <button name="action" value="login">Log In</button>
</form>
<?php else: ?>
<form method="post">
    <button name="action" value="logout">Log Out</button>
</form>
<?php endif; ?>
