<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'site-pages add');
$form->prepare();
?>
<?php echo $this->pageTitle($translate('New page'), 1, $translate('Pages')); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <?php echo $this->cancelButton(); ?>
    <button><?php echo $translate('Add'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>
