<?php
$this->htmlElement('body')->appendAttribute('class', 'sites add');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$form->prepare();
?>
<h1><?php echo $this->escapeHtml(sprintf($this->translate('Edit Site: "%s"'), $site->title())); ?></h1>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <a href="#" class="delete button sidebar-confirm" data-sidebar-confirm-url="<?php echo $escapeAttr($site->url('delete')); ?>">Delete</a>
    <button><?php echo $this->escapeHtml($this->translate('Save')); ?></button>
</div>
<nav class="section-nav">
    <ul>
        <li class="active"><a href="#admin"><?php echo $this->translate('Admin'); ?></a></li>
        <li><a href="#pages"><?php echo $this->translate('Pages'); ?></a></li>
        <li><a href="#permissions"><?php echo $this->translate('User permissions'); ?></a></li>
    </ul>
</nav>
<fieldset id="admin" class="section active">
<legend><?php echo $this->translate('Admin'); ?></legend>
<?php echo $this->formElements($form); ?>
</fieldset>
<fieldset id="pages" class="section">
<legend><?php echo $this->translate('Pages'); ?></legend>
<?php echo $site->link('Add a Page', 'add-page', array('class' => 'button')); ?>

<?php
$pages = $site->pages();
if ($pages):
?>
    <table id="page-list">
        <thead>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Slug'); ?></th>
        </thead>
        <tbody>
<?php foreach ($pages as $page): ?>
        <tr>
            <td>
                <?php echo $page->title(); ?>
                <ul class="actions">
                    <li><?php echo $page->link('', 'edit', array(
                        'class' => 'o-icon-edit',
                        'aria-label' => $this->translate('Edit'),
                        'title' => $this->translate('Edit'),
                    )); ?></li>
                </ul>
            </td>
            <td><?php echo $page->slug(); ?></td>
        </tr>
<?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
</fieldset>
<fieldset id="permissions" class="section">
<?php $sitePermissions = $site->sitePermissions(); ?>
    <table id="site-user-permissions" class="<?php echo (count($sitePermissions) > 0) ? '' : 'empty'; ?>">
        <thead>
            <tr>
                <th scope="col"><?php echo $this->translate('User'); ?></th>
                <th scope="col"><?php echo $this->translate('Admin'); ?></th>
                <th scope="col"><?php echo $this->translate('Attach'); ?></th>
                <th scope="col"><?php echo $this->translate('Edit'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $index = 1;
            foreach($sitePermissions as $sitePermission): 
            $user = $sitePermission->user();
            $admin = ($sitePermission->admin()) ? 'checked' : '';
            $edit = ($sitePermission->edit()) ? 'checked' : '';
            $attach = ($sitePermission->attach()) ? 'checked' : '';
            ?>
            <tr class="user value">
                <td data-user-id="<?php echo $escape($user->id()); ?>" data-permission-id="<?php echo $index; ?>">
                    <span class="restore-value"><?php echo $this->translate('User to be removed'); ?></span>
                    <ul class="actions">
                        <li><a href="#" class="o-icon-delete" aria-label="<?php echo $this->translate('Delete'); ?>"></a></li>
                        <li><a href="#" class="o-icon-undo" aria-label="<?php echo $this->translate('Restore'); ?>"></a></li>
                    </ul>
                    <?php echo $escape($user->name()); ?> (<?php echo $escape($user->email()); ?>)
                    <input type="hidden" name="o:site_permission[<?php echo $index; ?>][o:user][o:id]" value="<?php echo $escape($user->id()); ?>">
                </td>
                <td>
                    <input type="checkbox" name="o:site_permission[<?php echo $index; ?>][o:admin]" <?php echo $admin; ?> value="1">
                </td>
                <td><input type="checkbox" name="o:site_permission[<?php echo $index; ?>][o:edit]" <?php echo $edit; ?> value="1"></td>
                <td><input type="checkbox" name="o:site_permission[<?php echo $index; ?>][o:attach]" <?php echo $attach; ?> value="1"></td>
                <?php $index++; ?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="no-resources">
        <p><?php echo $this->translate('This site has no users. Add users using the interface to the right.'); ?></p>
    </div>

    <div id="site-user-selector" class="selector sidebar">
        <p><?php echo $this->translate('Click on a user to add them to the site.'); ?></p>
        <input type="text" class="selector-filter" placeholder="Filter users">
        <ul id="new-site-user">
            <li class="show"><?php echo $this->translate('All Users'); ?> (<?php echo count($users); ?>)
                <ul>
                <?php
                    $usersByInitial = array();
                    $initial = substr($users[0]->name(), 0, 1);
                    foreach ($users as $user) {
                        $userInitial = substr($user->name(), 0, 1);
                        if ($userInitial !== $initial) {
                            $initial = $userInitial;
                        }
                        $usersByInitial[$initial][] = $user;
                    }
                ?>
                <?php foreach ($usersByInitial as $initial => $users): ?>
                    <li class="selector-parent"><span>
                        <?php echo $initial; ?></span> 
                        (<span class="selector-child-count"><?php echo count($usersByInitial[$initial]); ?></span>)
                        <ul>
                        <?php foreach($users as $user): ?>
                            <li class="selector-child" data-child-label="<?php echo $escape($user->name() . ' (' . $user->email() . ')'); ?>" data-user-id="<?php echo $escape($user->id()); ?>"><span><?php echo $escape($user->name()); ?><br><?php echo $escape($user->email()); ?></span></li>
                        <?php endforeach; ?>
                        </ul>
                <?php endforeach; ?>
                </ul>
            </li>
        </ul>
    </div>
</fieldset>
<?php echo $this->form()->closeTag(); ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escapeAttr($this->translate('Close')); ?>"
        title="<?php echo $escapeAttr($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $escape($this->translate('Delete Site')); ?></h2>
        <p><?php echo $escape($this->translate('Are you sure you would like to delete this site?')); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php
$userRowTemplate = '
<tr class="user value">
    <td data-user-id="__user-id__" data-permission-id="__index__">
        <span class="restore-value">' . $this->translate('User to be removed') . '</span>
        <ul class="actions">
            <li><a href="#" class="o-icon-delete" aria-label="' . $this->translate('Delete') . '"></a></li>
            <li><a href="#" class="o-icon-undo" aria-label="' . $this->translate('Restore') . '"></a></li>
        </ul>
        <input type="hidden" name="o:site_permission[__index__][o:user][o:id]" value="__user-id__">
    </td>
    <td>
        <input type="checkbox" name="o:site_permission[__index__][o:admin]" value="1">
    </td>
    <td><input type="checkbox" name="o:site_permission[__index__][o:edit]" value="1"></td>
    <td><input type="checkbox" name="o:site_permission[__index__][o:attach]" value="1"></td>
</tr>
';
?>

<span id="user-row-template" data-template="<?php echo $escapeAttr($userRowTemplate); ?>">

<script>
$('#permissions').on('click', '.o-icon-delete,.o-icon-undo', function(e) {
    e.preventDefault();
    $(this).parents('tr').toggleClass('delete');
});

$('#permissions').on('click', '.o-icon-delete', function() {
    var userRow = $(this).parents('tr');
    userRow.find('input[type="hidden"]').remove();
});

$('#permissions').on('click', '.o-icon-undo', function() {
    var userCell = $(this).parents('td');
    var userId = userCell.data('user-id');
    var userHiddenInput = $('<input type="hidden" name="o:site_permission[2][o:user][o:id]">');
    userHiddenInput.val(userId);
    userCell.append(userHiddenInput);
});

$('#permissions .selector .selector-child').click(function() {
    var user = $(this);
    var userId = user.data('user-id');
    if ($('td[data-user-id="' + userId + '"]').length == 0) {
        if ($('#site-user-permissions').hasClass('empty')) {
            var index = 1;
        } else {
            var index = $('#permissions tbody tr:last-of-type td:first-of-type').data('permission-id');
            index++;
        }
        var template = $('#user-row-template').data('template');
        template = template.replace(/__index__/g, index);
        template = template.replace(/__user-id__/g, userId);
        template = $($.parseHTML(template));
        template.find('.actions').after(user.data('child-label'));
        $('#permissions tbody').append(template);
    }
    $('#site-user-permissions').removeClass('empty');
});

$('.section-nav a[href="#permissions"]').click(function() {
    $('body').addClass('sidebar-open');
    $('#permissions .sidebar').addClass('active');
});

$('.section-nav a:not([href="#permissions"])').click(function() {
    $('body').removeClass('sidebar-open');
    $('#permissions .sidebar').removeClass('active');
});
</script>
