<?php
$this->htmlElement('body')->appendAttribute('class', 'sites browse');
$confirmForm->prepare();
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
?>

<?php echo $this->pageTitle($this->translate('Sites')); ?>

<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Add new site'), $this->url('admin/site/add'), array('class' => 'button')); ?>
</div>

<?php if (count($sites) > 0): ?>

<?php echo $this->pagination(); ?>

<table>
    <thead>
        <tr>
            <th><?php echo $this->sortLink($this->translate('Title'), 'title'); ?></th>
            <th><?php echo $this->sortLink($this->translate('Owner'), 'owner_name'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($sites as $site): ?>
        <tr>
            <td>
                <span class="resource-name">
                    <?php echo $site->link($site->title()); ?>
                </span>
                <ul class="actions">
                    <li><?php echo $site->link('', null, array(
                        'class' => 'o-icon-edit',
                        'aria-label' => $this->translate('Edit'),
                        'title' => $this->translate('Edit'),
                    )); ?></li>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escapeAttr($site->url('show-details')); ?>"
                        data-sidebar-confirm-url="<?php echo $escapeAttr($site->url('delete')); ?>"
                        class="o-icon-delete sidebar-confirm"
                        aria-label="<?php echo $escapeAttr($this->translate('Delete')); ?>"
                        title="<?php echo $escapeAttr($this->translate('Delete')); ?>"></a></li>
                </ul>
            </td>
            <td>
                <?php
                $owner = $site->owner();
                echo $this->hyperlink($owner->name(), $this->url(
                    'admin/id',
                    array(
                        'controller' => 'user',
                        'action' => 'show',
                        'id' => $owner->id()
                    )
                )); ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php echo $this->pagination(); ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escapeAttr($this->translate('Close')); ?>"
        title="<?php echo $escapeAttr($this->translate('Close')); ?>"></a>
    <div id="sidebar-confirm">
        <h2><?php echo $this->translate('Delete Site'); ?></h2>
        <p><?php echo $this->translate('Are you sure you would like to delete this site?'); ?></p>
        <?php echo $this->form($confirmForm); ?>
    </div>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('Omeka could not find any sites.'); ?></p>
</div>

<?php endif; ?>
