<?php
$this->htmlElement('body')->appendAttribute('class', 'sites site-settings');
$form->prepare();
?>
<?php echo $this->pageTitle($site->title(), 1, $this->translate('Sites')); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Save'); ?></button>
</div>
<?php echo $this->formCollection($form); ?>
<?php echo $this->form()->closeTag(); ?>
