<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'sites site-settings');
$form->prepare();
?>
<?php echo $this->pageTitle($site->title(), 1, $translate('Sites')); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <?php echo $this->cancelButton(); ?>
    <button><?php echo $translate('Save'); ?></button>
</div>
<?php echo $this->formCollection($form); ?>
<?php echo $this->form()->closeTag(); ?>
