<?php
$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('css/asset-form.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'sites theme-settings');
?>
<?php echo $this->pageTitle($theme->getName(), 1, $translate('Theme'), $translate('Configure')); ?>
<?php if(isset($this->form)): ?>
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); ?>
    <div id="page-actions">
        <?php echo $this->cancelButton(); ?>
        <button><?php echo $translate('Save'); ?></button>
    </div>
    <?php echo $this->formCollection($form, false); ?>
    <?php echo $this->form()->closeTag(); ?>
<?php else: ?>
    <p><?php echo $translate('The current theme has no configuration options.'); ?></p>
<?php endif; ?>
