<?php $this->htmlElement('body')->appendAttribute('class', 'sites theme-resource-pages'); ?>
<?php echo $this->pageTitle($theme->getName(), 1, $this->translate('Theme'), $this->translate('Configure resource pages')); ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formCollection($form, false); ?>

<div id="page-actions">
    <?php echo $this->cancelButton(); ?>
    <button><?php echo $this->translate('Save'); ?></button>
</div>

<?php
echo $this->sectionNav([
    'item-section' => $this->translate('Item page'),
    'media-section' => $this->translate('Media page'),
    'item-set-section' => $this->translate('Item set page'),
]);
?>

<div id="item-section" class="section active">
    <ul id="item-block-layouts" class="block-layouts" data-block-layout-template="<?php echo $this->escapeHtml('<li class="block-layout"><span class="block-layout-label"></span><a href="#" class="o-icon-delete block-layout-remove"></a><input type="hidden" class="block-layout-input" name="block_layouts[items][]"></li>'); ?>"></ul>
</div>

<div id="media-section" class="section">
    <ul id="media-block-layouts" class="block-layouts" data-block-layout-template="<?php echo $this->escapeHtml('<li class="block-layout"><span class="block-layout-label"></span><a href="#" class="o-icon-delete block-layout-remove"></a><input type="hidden" class="block-layout-input" name="block_layouts[media][]"></li>'); ?>"></ul>
</div>

<div id="item-set-section" class="section">
    <ul id="item-set-block-layouts" class="block-layouts" data-block-layout-template="<?php echo $this->escapeHtml('<li class="block-layout"><span class="block-layout-label"></span><a href="#" class="o-icon-delete block-layout-remove"></a><input type="hidden" class="block-layout-input" name="block_layouts[item_sets][]"></li>'); ?>"></ul>
</div>

<?php echo $this->form()->closeTag(); ?>

<div id="item-block-layout-selector" class="sidebar">
    <h3><?php echo $this->translate('Add a new block'); ?></h3>
    <?php foreach ($blockLayoutManager->getAllForResource('items') as $blockLayoutName => $blockLayout): ?>
    <button type="button" class="option" value="<?php echo $this->escapeHtml($blockLayoutName); ?>">
        <?php echo $this->translate($blockLayout->getLabel()); ?>
    </button>
    <?php endforeach; ?>
</div>

<div id="media-block-layout-selector" class="sidebar">
    <h3><?php echo $this->translate('Add a new block'); ?></h3>
    <?php foreach ($blockLayoutManager->getAllForResource('media') as $blockLayoutName => $blockLayout): ?>
    <button type="button" class="option" value="<?php echo $this->escapeHtml($blockLayoutName); ?>">
        <?php echo $this->translate($blockLayout->getLabel()); ?>
    </button>
    <?php endforeach; ?>
</div>

<div id="item-set-block-layout-selector" class="sidebar">
    <h3><?php echo $this->translate('Add a new block'); ?></h3>
    <?php foreach ($blockLayoutManager->getAllForResource('item_sets') as $blockLayoutName => $blockLayout): ?>
    <button type="button" class="option" value="<?php echo $this->escapeHtml($blockLayoutName); ?>">
        <?php echo $this->translate($blockLayout->getLabel()); ?>
    </button>
    <?php endforeach; ?>
</div>

<script>
$(document).ready(function() {
    const resourcePageConfig = $('#resource-page-config-form').data('resourcePageConfig');
    const blockLayoutLabels = $('#resource-page-config-form').data('blockLayoutLabels');
    // Add a block layout to a list.
    const addBlockLayout = function(blockLayouts, blockLayoutName) {
        const blockLayout = $(blockLayouts.data('blockLayoutTemplate'));
        blockLayout.find('.block-layout-label').text(blockLayoutLabels[blockLayoutName]);
        blockLayout.find('.block-layout-input').val(blockLayoutName);
        blockLayouts.append(blockLayout);
    };
    // Populate the block layout lists on load.
    $.each(resourcePageConfig['block_layouts']['items'], function(key, blockLayoutName) {
        const blockLayouts = $('#item-block-layouts');
        addBlockLayout(blockLayouts, blockLayoutName);
        $('#item-block-layout-selector').find(`button.option[value="${blockLayoutName}"]`).prop('disabled', true);
    })
    $.each(resourcePageConfig['block_layouts']['media'], function(key, blockLayoutName) {
        const blockLayouts = $('#media-block-layouts');
        addBlockLayout(blockLayouts, blockLayoutName);
        $('#media-block-layout-selector').find(`button.option[value="${blockLayoutName}"]`).prop('disabled', true);
    })
    $.each(resourcePageConfig['block_layouts']['item_sets'], function(key, blockLayoutName) {
        const blockLayouts = $('#item-set-block-layouts');
        addBlockLayout(blockLayouts, blockLayoutName);
        $('#item-set-block-layout-selector').find(`button.option[value="${blockLayoutName}"]`).prop('disabled', true);
    })
    // Open the correct sidebar on load.
    switch (window.location.hash.substr(1)) {
        case 'media-section':
            Omeka.openSidebar($('#media-block-layout-selector'));
            break;
        case 'item-set-section':
            Omeka.openSidebar($('#item-set-block-layout-selector'));
            break;
        case 'item-section':
        default:
            Omeka.openSidebar($('#item-block-layout-selector'));
    }
    // Handle navigation switch.
    $('#item-section-label').on('click', function(e) {
        Omeka.closeSidebar($('.sidebar'));
        Omeka.openSidebar($('#item-block-layout-selector'));
    });
    $('#media-section-label').on('click', function(e) {
        Omeka.closeSidebar($('.sidebar'));
        Omeka.openSidebar($('#media-block-layout-selector'));
    });
    $('#item-set-section-label').on('click', function(e) {
        Omeka.closeSidebar($('.sidebar'));
        Omeka.openSidebar($('#item-set-block-layout-selector'));
    });
    // Handle a block layout button click.
    $('button.option').on('click', function(e) {
        const thisBlockLayoutButton = $(this);
        const blockLayoutName = thisBlockLayoutButton.val();
        const blockLayouts = $('.section.active .block-layouts');
        addBlockLayout(blockLayouts, blockLayoutName);
        thisBlockLayoutButton.prop('disabled', true);
    });
});
</script>
