<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/asset-form.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'sites theme-settings');
?>
<?php echo $this->pageTitle($theme->getName(), 1, $this->translate('Theme'), $this->translate('Configure')); ?>
<?php if(isset($this->form)): ?>
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); ?>
    <div id="page-actions">
        <button><?php echo $this->translate('Save'); ?></button>
    </div>
    <?php echo $this->formCollection($form, false); ?>
    <?php echo $this->form()->closeTag(); ?>
<?php else: ?>
    <p><?php echo $this->translate('The current theme has no configuration options.'); ?></p>
<?php endif; ?>
