<?php
$this->htmlElement('body')->appendAttribute('class', 'sites theme');
?>
<h1><?php echo sprintf($this->translate('Theme Settings') . ': "%s"', $theme->getName()); ?></h1>
<?php if(isset($this->form)): ?>
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); ?>
    <div id="page-actions">
        <button><?php echo $this->translate('Save'); ?></button>
    </div>
    <?php echo $this->formCollection($form, false); ?>
    <?php echo $this->form()->closeTag(); ?>
<?php else: ?>
    <p><?php echo $this->translate('The current theme has no configuration options.'); ?></p>
<?php endif; ?>
