<?php
$this->headScript()->appendFile($this->assetUrl('js/site-users.js', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'sites users');
$form->prepare();
$escape = $this->plugin('escapeHtml');
$delete = $this->translate('Delete');
$restore = $this->translate('Restore');
$roles = [
    'viewer' => $this->translate('Viewer'),
    'editor' => $this->translate('Editor'),
    'admin' => $this->translate('Admin'),
];
?>

<?php echo $this->pageTitle($this->translate('User permissions'), 1, $this->translate('Sites')); ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formCollection($form, false); ?>

<div id="page-actions">
    <button><?php echo $this->translate('Save'); ?></button>
</div>

<?php $sitePermissions = $site->sitePermissions(); ?>
    <table id="site-user-permissions" class="tablesaw tablesaw-stack <?php echo count($sitePermissions) ? '' : 'empty'; ?>" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th scope="col"><?php echo $this->translate('User'); ?></th>
                <th scope="col"><?php echo $this->translate('Role'); ?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $index = 0;
            foreach($sitePermissions as $sitePermission):
            $user = $sitePermission->user();
            ?>
            <tr class="user value">
                <td class="user-meta">
                    <span class="restore-value"><?php echo $this->translate('User to be removed'); ?></span>
                    <span class="user-name"><?php echo $escape($user->name()); ?> (<?php echo $escape($user->email()); ?>)</span>
                    <input type="hidden" class="user-id" name="o:site_permission[<?php echo $index; ?>][o:user][o:id]" value="<?php echo $escape($user->id()); ?>">
                </td>
                <td><select name="o:site_permission[<?php echo $index; ?>][o:role]">
                    <?php
                    foreach ($roles as $key => $value):
                    $selected = $key === $sitePermission->role() ? true : false;
                    ?>
                    <option value="<?php echo $key; ?>"<?php echo $selected ? ' selected' : null; ?>><?php echo $value; ?></option>
                    <?php endforeach; ?>
                </select></td>
                <td>
                    <ul class="actions">
                        <li><a href="#" class="o-icon-delete" aria-label="<?php echo $delete; ?>" title="<?php echo $delete; ?>"></a></li>
                        <li><a href="#" class="o-icon-undo" aria-label="<?php echo $restore; ?>" title="<?php echo $restore; ?>"></a></li>
                    </ul>
                </td>
                <?php $index++; ?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="no-resources">
        <p><?php echo $this->translate('This site has no users. Add users using the interface to the right.'); ?></p>
    </div>
    <div id="site-user-selector" class="selector sidebar active">
        <h3><?php echo $this->translate('Click on a user to add them to the site.'); ?></h3>
        <input type="text" class="selector-filter" placeholder="<?php echo $this->translate('Filter users'); ?>">
        <ul id="new-site-user">
            <li class="total-count-heading"><?php echo $this->translate('All users'); ?> (<?php echo count($users); ?>)
                <ul class="selectable-list">
                    <?php
                    $usersByInitial = [];
                    $initial = substr(strtoupper($users[0]->name()), 0, 1);
                    foreach ($users as $user) {
                        $userInitial = substr(strtoupper($user->name()), 0, 1);
                        if ($userInitial !== $initial) {
                            $initial = $userInitial;
                        }
                        $usersByInitial[$initial][] = $user;
                    }
                    ?>
                <?php foreach ($usersByInitial as $initial => $users): ?>
                    <li class="selector-parent">
                        <span><?php echo $initial; ?></span>
                        (<span class="selector-child-count"><?php echo count($usersByInitial[$initial]); ?></span>)
                        <ul>
                        <?php foreach($users as $user): ?>
                            <li class="selector-child" data-child-search="<?php echo $escape($user->name() . ' (' . $user->email() . ')'); ?>" data-user-id="<?php echo $escape($user->id()); ?>"><span><?php echo $escape($user->name()); ?><br><?php echo $escape($user->email()); ?></span></li>
                        <?php endforeach; ?>
                        </ul>
                    </li>
                <?php endforeach; ?>
                </ul>
            </li>
        </ul>
    </div>

<?php echo $this->form()->closeTag(); ?>

<?php
$userRowTemplate = '
<tr class="user value">
    <td class="user-meta">
        <span class="restore-value">' . $this->translate('User to be removed') . '</span>
        <span class="user-name"></span>
        <input type="hidden" class="user-id" name="o:site_permission[__index__][o:user][o:id]">
    </td>
    <td><select name="o:site_permission[__index__][o:role]">';
foreach ($roles as $key => $value) {
    $userRowTemplate .= '<option value="' . $key . '">' . $value . '</option>';
}
$userRowTemplate .= '</select></td>
    <td>
        <ul class="actions">
            <li><a href="#" class="o-icon-delete" aria-label="' . $delete . '" title="' . $delete . '"></a></li>
            <li><a href="#" class="o-icon-undo" aria-label="' . $restore . '" title="' . $restore . '"></a></li>
        </ul>
    </td>
</tr>
';
?>

<span id="user-row-template" data-template="<?php echo $escape($userRowTemplate); ?>"></span>
