<?php
$this->headScript()->appendFile($this->assetUrl('js/asset-form.js', 'Omeka'));
$asset = null;
$value = $element->getValue();
if ($value) {
    try {
        $response = $this->api()->read('assets', $value);
        $asset = $response->getContent();
    } catch (Omeka\Api\Exception\NotFoundException $e) {
        $element->setValue(null);
    }
}
?>
<div class="asset-form-element<?php if (!$asset) echo ' empty'; ?>">
    <span class="selected-asset">
    <?php
    if ($asset) {
        echo $asset->name();
    }
    ?>
    </span>
    <span class="no-selected-asset">
        <?php echo $this->translate('[No asset selected]'); ?>
    </span>
    <button type="button"
        class="asset-form-select"
        data-sidebar-content-url="<?php echo $this->escapeHtml($this->url('admin/default', ['controller' => 'asset', 'action' => 'sidebar-select'])); ?>"
    >
        <?php echo $this->translate('Select'); ?>
    </button>
    <button type="button"
        class="asset-form-clear red button"
    >
        <?php echo $this->translate('Clear'); ?>
    </button>
    <?php echo $this->formHidden($element); ?>
</div>
