<?php
$this->htmlElement('body')->appendAttribute('class', 'add item-set sidebar-open');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'));
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
?>
<h1><?php echo $this->translate('Add Item Set'); ?></h1>

<nav class="section-nav">
    <ul>
        <li><a href="#resource-values" class="active">Values</a></li>
        <li><a href="#item-media">Media</a></li>
        <li><a href="#item-visibility">Visibility</a></li>
    </ul>
</nav>

<form method='post' id='add-item-set'>
    <?php 
    
        //produces a <fieldset> with the id and class atts passed in.
        //on, e.g., the item add/edit pages, the id will work with the classes on 
        //the nav lis above. (see globals.js)  
        echo $this->partial(
                'common/resource-fields.phtml',
                array(
                    'id' => 'resource-values',
                    'class' => 'section active',
                    'form' => $form
                ));
    ?>

    <fieldset id="page-actions">
        <input type="submit" name="add-item-submit" value="Create item set" />
        <a href="<?php echo $this->url('admin/default', array('controller'=>'item-set', 'action'=>'browse')); ?>" class="cancel button">Cancel</a>
    </fieldset>
    <?php echo $this->formElement($form->get('csrf')); ?>
</form>


<?php 
        echo $this->partial('common/resource-form-templates.phtml');
?>
