<?php
$this->htmlElement('body')->appendAttribute('class', 'add item-set sidebar-open');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'));
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
?>
<h1><?php echo $this->translate('Add Item Set'); ?></h1>


    <nav class="section-nav">
        <ul>
            <li class="active"><a href="#resource-values">Values</a></li>
        </ul>
    </nav>
<?php
echo $this->partial('omeka/admin/item-set/form.phtml', array(
    'form' => $form,
    'itemSet' => $itemSet,
    'submitLabel' => $this->translate('Save'),
    'deleteButton' => $deleteButton
));
?>
