<?php
$this->htmlElement('body')->appendAttribute('class', 'add item-set sidebar-open');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'));
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
?>
<h1><?php echo $this->translate('Add Item Set'); ?></h1>

<form method='post' id='add-item-set'>

    <nav class="section-nav">
        <ul>
            <li class="active"><a href="#resource-values">Values</a></li>
        </ul>
    </nav>

    <?php 
    
        //produces a <fieldset> with the id and class atts passed in.
        //on, e.g., the item add/edit pages, the id will work with the classes on 
        //the nav lis above. (see globals.js)  
        echo $this->partial(
                'common/resource-fields.phtml',
                array(
                    'id' => 'resource-values',
                    'class' => 'section active',
                    'form' => $form
                ));
    ?>

    <fieldset id="page-actions">
        <a href="#" class="o-icon-public button" aria-label="Make private" title="Make private"></a>
        <input type="hidden" name="o:is_public" value="1">
        <input type="submit" name="add-item-submit" value="Add item set" />
    </fieldset>
    <?php echo $this->formElement($form->get('csrf')); ?>
</form>


<?php 
        echo $this->partial('common/resource-form-templates.phtml');
?>
