<?php
$this->htmlElement('body')->appendAttribute('class', 'edit item-sets');
$escape = $this->plugin('escapeHtml');
$deleteButton = $itemSet->userIsAllowed('delete')
    ? '<a href="#" class="delete button">' . $this->translate('Delete') . '</a>'
    : null;
?>

<script type='text/javascript'>
var valuesJson = <?php echo json_encode($itemSet->values()); ?>;
</script>

<?php echo $this->pageTitle($itemSet->displayTitle(), 1, $this->translate('Item sets'), $this->translate('Edit')); ?>
<?php $this->trigger('view.edit.before'); ?>
<?php
echo $this->partial('omeka/admin/item-set/form.phtml', [
    'form' => $form,
    'itemSet' => $itemSet,
    'submitLabel' => $this->translate('Save'),
    'deleteButton' => $deleteButton,
    'sectionNavEvent' => 'view.edit.section_nav',
    'action' => 'edit',
]);
?>

<?php echo $this->deleteConfirm($itemSet, 'item set'); ?>

<?php $this->trigger('view.edit.after'); ?>
