<?php
$this->htmlElement('body')->appendAttribute('class', 'edit item-set sidebar-open');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'));
$form->prepare();
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
?>

<script type='text/javascript'>
var valuesJson = <?php echo $values; ?>;
var selectedItemValueJson;
</script>

<h1><?php echo $this->translate('Edit item set'); ?></h1>
<?php 
if (isset($errors)) {
    print_r($errors);
}
?>

<form method='post' id='edit-item-set'>

    <div class="o-icon-view visibility">
        <label for="o:is_public"><?php echo $escape('Public'); ?></label>
        <input type="checkbox" id="o:is_public" name="o:is_public" <?php echo ($itemSet->isPublic()) ? 'checked' : ''; ?>>
    </div>
    
    <a href="#" class="o-icon-delete delete"><?php echo $escape('Delete item'); ?></a>
    
    <nav class="section-nav">
        <ul>
            <li class="active"><a href="#resource-values">Values</a></li>
            <li><a href="#item-media">Media</a></li>
        </ul>
    </nav>
    <?php 
        //produces a <fieldset> with the id and class atts passed in.
        //on, e.g., the item add/edit pages, the id will work with the classes on 
        //the nav lis above. (see globals.js)  
        echo $this->partial(
                'common/resource-fields.phtml',
                array(
                    'id' => 'resource-values',
                    'class' => 'section active',
                    'form' => $form,
                    'resource' => $itemSet
                ));
    ?>

    <fieldset id="page-actions">
        <input type="submit" name="add-item-submit" value="Save changes" />
    </fieldset>
    <?php echo $this->formElement($form->get('csrf')); ?>
</form>


<?php 
        echo $this->partial('common/resource-form-templates.phtml');
?>
