<?php
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'));
$form->prepare();
$escape = $this->plugin('escapeHtml');
$formElement = $this->plugin('formElement');
?>

<?php echo $this->form()->openTag($form); ?>

<?php echo $this->sectionNav([
    'resource-values' => $this->translate('Values'),
], $sectionNavEvent); ?>

<?php $this->trigger("view.$action.form.before", ['form' => $form]); ?>

<?php echo $this->partial('common/resource-fields.phtml', [
    'form' => $form,
    'resource' => $itemSet,
]); ?>

<div id="page-actions">
    <?php if ($itemSet && $itemSet->isOpen()): ?>
    <a href="#"
        class="o-icon-unlock button"
        aria-label="<?php echo $escape($this->translate('Close item set')); ?>"
        title="<?php echo $escape($this->translate('Close item set')); ?>"></a>
    <input type="hidden" name="o:is_open" value="1">
    <?php else: ?>
    <a href="#"
        class="o-icon-lock button"
        aria-label="<?php echo $escape($this->translate('Open item set')); ?>"
        title="<?php echo $escape($this->translate('Open item set')); ?>"></a>
    <input type="hidden" name="o:is_open" value="0">
    <?php endif; ?>

    <?php if ($itemSet && $itemSet->isPublic() || !isset($itemSet) ): ?>
    <a href="#"
        class="o-icon-public button"
        aria-label="<?php echo $escape($this->translate('Make private')); ?>"
        title="<?php echo $escape($this->translate('Make private')); ?>"></a>
    <input type="hidden" name="o:is_public" value="1">
    <?php else: ?>
    <a href="#"
        class="o-icon-private button"
        aria-label="<?php echo $escape($this->translate('Make public')); ?>"
        title="<?php echo $escape($this->translate('Make public')); ?>"></a>
    <input type="hidden" name="o:is_public" value="0">
    <?php endif; ?>

    <?php echo (isset($deleteButton)) ? $deleteButton : ''; ?>
    <input type="submit" name="add-item-set-submit" value="<?php echo $this->translate('Save'); ?>">
</div>

<?php $this->trigger("view.$action.form.after", ['form' => $form]); ?>

<?php echo $formElement($form->get('csrf')); ?>

<?php echo $this->form()->closeTag(); ?>

<?php echo $this->partial('common/resource-form-templates.phtml'); ?>
