<?php
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'Omeka'));
$form->prepare();
$escapeAttr = $this->plugin('escapeHtmlAttr');
$escape = $this->plugin('escapeHtml');
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
?>


<?php echo $this->form()->openTag($form); ?>

<?php
//produces a <fieldset> with the id and class atts passed in.
//on, e.g., the item add/edit pages, the id will work with the classes on
//the nav lis above. (see globals.js)
echo $this->partial(
    'common/resource-fields.phtml',
    array(
        'id'                   => 'resource-values',
        'class'                => 'section active',
        'form'                 => $form,
        'resource'             => $itemSet,
        'propertySelectorText' => 'Click on a property to add it to the add panel'
    )
);
?>

    <fieldset id="page-actions">
        <?php if ($itemSet && $itemSet->isOpen()): ?>
        <a href="#" class="o-icon-unlock button" aria-label="Close item set" title="Close item set"></a>
        <input type="hidden" name="o:is_open" value="1">
        <?php else: ?>
        <a href="#" class="o-icon-lock button" aria-label="Open item set" title="Open item set"></a>
        <input type="hidden" name="o:is_open" value="0">
        <?php endif; ?>
        
        <?php if ($itemSet && $itemSet->isPublic()): ?>
        <a href="#" class="o-icon-public button" aria-label="Make private" title="Make private"></a>
        <input type="hidden" name="o:is_public" value="1">
        <?php else: ?>
        <a href="#" class="o-icon-private button" aria-label="Make public" title="Make public"></a>
        <input type="hidden" name="o:is_public" value="0">
        <?php endif; ?>
        
        <?php echo (isset($deleteButton)) ? $deleteButton : ''; ?>
        <input type="submit" name="add-item-submit" value="Save" />
    </fieldset>
<?php echo $formElement($form->get('csrf')); ?>

</form>

<?php
/*
 * the sidebar and templates are not going into the fields partial because
 * they exist outside the form, and the partial needs to work with
 * multiple resource fieldsets (item and media, e.g.)
 */
echo $this->partial('common/resource-form-templates.phtml');
?>