<?php
$this->htmlElement('body')->appendAttribute('class', 'item-sets search');
?>
<?php echo $this->pageTitle($this->translate('Advanced search'), 1, $this->translate('Item sets')); ?>
<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
<?php echo $this->partial(
    'common/advanced-search',
    ['query' => $this->params()->fromQuery(), 'resourceType' => 'itemSet']
); ?>
<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Reset'), $this->url(null, [], true), ['class' => 'button']); ?>
    <input type="submit" name="submit" value="<?php echo $this->escapeHtml($this->translate('Search')); ?>">
</div>
</form>
