<div class="resource-details" data-resource-values="<?php echo $this->escapeHtmlAttr($values); ?>">
    <?php if ($linkTitle): ?>
    <h2 class="o-title"><?php echo $itemSet->link(($itemSet->displayTitle())); ?></h2>
    <?php else: ?>
    <h2 class="o-title"><?php echo $this->escapeHTML($itemSet->displayTitle()); ?></h2>
    <?php endif; ?>
    <div class="o-description"><?php echo $this->escapeHTML($itemSet->displayDescription()); ?></div>
    <div class="property">
        <h4>Visibility</h4>
        <div class="value"><?php echo ($itemSet->isPublic()) ? $this->translate('Public') : $this->translate('Private'); ?></div>
        <div class="value"><?php echo ($itemSet->isOpen()) ? $this->escapeHtmlAttr($this->translate('Open to additions')) : $this->escapeHtmlAttr($this->translate('Closed to additions')); ?></div>
    </div>
</div>
