<div class="resource-details" data-resource-values="<?php echo $this->escapeHtmlAttr($values); ?>">
    <?php if ($linkTitle): ?>
    <h2 class="o-title"><?php echo $itemSet->link(($itemSet->displayTitle())); ?></h2>
    <?php else: ?>
    <h2 class="o-title"><?php echo $this->escapeHTML($itemSet->displayTitle()); ?></h2>
    <?php endif; ?>
    <div class="o-description"><?php echo $this->escapeHTML($itemSet->displayDescription()); ?></div>
    <?php echo $itemSet->displayValues(); ?>
</div>
