<?php
$this->htmlElement('body')->appendAttribute('class', 'item-sets show sidebar-open');
$escape = $this->plugin('escapeHtml');
$escapeAttr = $this->plugin('escapeHtmlAttr');
$viewItemsLink = $this->url(
    'admin/default', 
    array( 'controller' => 'item', 'action' => 'browse'), 
    array(
        'query' =>  array(
            'item_set_id' => $itemSet->id()
        )
    )
);
?>
<h1><?php echo $escape('Item Set'); ?>: &ldquo;<?php echo $escape($itemSet->displayTitle()); ?>&rdquo;</h1>
<div id="page-actions">
    <?php echo $itemSet->link($this->translate('Edit item set'), 'edit', array('class' => 'button')); ?>
    <a href="<?php echo $viewItemsLink; ?>" class="button"><?php echo $this->translate('View items'); ?></a>
</div>

<nav class="section-nav">
    <ul>
        <li class="active"><a href="#item-set-metadata"><?php echo $escape('Metadata'); ?></a></li>
        <li><a href="#item-set-linked"><?php echo $escape('Linked Resources'); ?></a></li>
    </ul>
</nav>

<div id="item-set-metadata" class="active section">
    <?php echo $itemSet->displayValues(); ?>
</div>

<div id="item-set-linked" class="section">
    <?php echo $itemSet->displayLinkedResources(); ?>
</div>

<div class="active sidebar">
    <div class="property">
        <h4>Date Created</h4>
        <div class="value"><?php echo $escape($this->i18n()->dateFormat($itemSet->created())); ?></div>
    </div>
    <div class="property">
        <h4>Owner</h4>
        <div class="value"><?php echo $itemSet->owner()->username(); ?></div>
    </div>
    <div class="property">
        <h4>Visibility</h4>
        <div class="value"><?php echo ($itemSet->isPublic()) ? $escapeAttr('Public') : $escapeAttr('Private'); ?></div>
    </div>
</div>