<h2><?php echo $this->escapeHtml($property->label()); ?></h2>
<div class="meta-group">
    <h4><?php echo $this->escapeHtml($this->translate('Vocabulary')); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($property->vocabulary()->label()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->escapeHtml($this->translate('Term')); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($property->term()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->escapeHtml($this->translate('Comment')); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($property->comment()); ?></div>
</div>
