<h3><?php echo $this->escapeHtml($this->translate($property->label())); ?></h3>
<div class="meta-group">
    <h4><?php echo $this->translate('Vocabulary'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($this->translate($property->vocabulary()->label())); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Term'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($property->term()); ?></div>
</div>
<div class="meta-group">
    <h4><?php echo $this->translate('Comment'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($this->translate($property->comment())); ?></div>
</div>
<?php $this->trigger('view.details', array('entity' => $property)); ?>
