<h2><?php echo $this->escapeHtml($property->label()); ?></h2>
<p><?php echo $this->escapeHtml($this->translate('Vocabulary')); ?>: <?php echo $this->escapeHtml($property->vocabulary()->label()); ?></p>
<p><?php echo $this->escapeHtml($this->translate('Term')); ?>: <?php echo $this->escapeHtml($property->term()); ?></p>
<p><?php echo $this->escapeHtml($this->translate('Comment')); ?>: <?php echo $this->escapeHtml($property->comment()); ?></p>
