<?php $escape = $this->plugin('escapeHtml'); ?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item-set show'); ?>

<header>
    <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
    <nav><?php echo $this->navigation('Zend\Navigation\Site')->menu(); ?></nav>
</header>

<div id="content" role="navigation">
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <?php echo $itemSet->displayValues(); ?>
    <?php $itemCount = $itemSet->itemCount(); ?>
    <?php if ($itemCount > 0): ?>
    <div class="items">
        <?php if ($itemCount < 5): ?>
        <h3><?php echo $this->translate(sprintf('All Items (%s)', $itemCount)); ?></h3>
        <?php else: ?>
        <h3><?php echo $this->translate('5 Most Recent Items'); ?></h3>
        <?php echo $this->hyperlink($this->translate(sprintf('View all %s items in set', $itemCount)), $this->url('site/resource', ['site-slug' => $site->slug(), 'controller' => 'item', 'action' => 'browse'], ['query' => ['item_set_id' => $itemSet->id()]])); ?>
        <?php endif; ?>
        <ul class="resource-list">
            <?php foreach ($items as $item): ?>
            <li class="item resource">
                <?php if ($primaryMedia = $item->primaryMedia()): ?>
                <img
                    src="<?php echo $escape($primaryMedia->thumbnailUrl('square')); ?>"
                    title="<?php echo $escape($primaryMedia->displayTitle()); ?>"
                    alt="<?php echo $escape($primaryMedia->mediaType()); ?> thumbnail"
                >
                <?php endif; ?>
                <h4><?php echo $item->link($item->displayTitle()); ?></h4>
                <div class="description"><?php echo $item->displayDescription(); ?></div>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
</div>
<?php $this->trigger('view.show.after'); ?>
